# 🚀 LAB GUIDE — PRODUCTION-GRADE GRAPHRAG VS FLAT RAG

**Thời lượng:** 120 phút  
**Môi trường:** Google Colab (T4 GPU khuyến nghị) + Neo4j AuraDB  
**Dữ liệu:** HackerNoon Tech Company News Data Dump (bản thu gọn do giảng viên cung cấp)  
**Công cụ:** Học viên được dùng AI Coding Agent, nhưng phải tự thiết kế, kiểm thử và giải thích logic.

## 🎯 Mục tiêu
1. Xây dựng Hybrid GraphRAG end-to-end.
2. Xử lý Coreference Resolution, Entity Resolution và Super-node Mitigation.
3. Bulk insert bằng `UNWIND`, không insert từng row.
4. So sánh Flat RAG và GraphRAG bằng Golden Dataset + LLM-as-a-Judge.
5. Đo quality, latency và token usage.
6. Giải thích kiến trúc và failure modes.

> Notebook là **reference lab guide**: có code khung chạy được nhưng vẫn yêu cầu học viên thay prompt/threshold/retrieval policy và thuyết minh lựa chọn.

## ⏳ Timeline

| Phút | Nội dung |
|---|---|
| 00–15 | Setup, load, dedup, chunk, coreference |
| 15–45 | NER/RE, entity resolution, Neo4j bulk insert |
| 45–75 | Flat RAG, graph traversal, hybrid retrieval |
| 75–105 | Golden Dataset, LLM-as-a-Judge, comparison |
| 105–120 | Failure-mode tests, bonus, export, thuyết minh |

### Scale guard
Trong lab 2 giờ, không nên gửi toàn bộ 350MB qua LLM. Mặc định dùng subset:
- `LAB_MAX_ARTICLES = 1500`
- `LAB_MAX_CHUNKS = 3000`
- `EXTRACTION_MAX_CHUNKS = 400`

Kiến trúc phải scale được; volume trong giờ lab chỉ dùng để chứng minh pipeline.

# PHẦN 1 — SETUP & PREPROCESSING

### Secrets trên Colab
Tạo:
- `NEO4J_URI`, `NEO4J_USER`, `NEO4J_PASSWORD`
- `GROQ_API_KEY`, `GROQ_MODEL`
- `HF_TOKEN` để stream dataset từ Hugging Face
- cho judge: `JUDGE_PROVIDER`, `JUDGE_MODEL`, và `OPENAI_API_KEY` nếu dùng OpenAI

Không hard-code API key vào notebook nộp bài.

In [1]:
#@title 1.1 — Install
%pip -q install neo4j pandas numpy pyarrow sentence-transformers faiss-cpu groq openai tqdm networkx spacy datasets langchain-community llama-index

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\NapoleDong\Documents\Vinuni\LABS\Day19-2A202601851-LeVanDong\.venv\Scripts\python.exe -m pip install --upgrade pip

In [2]:
#@title 1.2 — Imports & config
import os, re, json, time, random, hashlib, unicodedata
from pathlib import Path
from collections import defaultdict, Counter, deque
from difflib import SequenceMatcher

import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from neo4j import GraphDatabase
from sentence_transformers import SentenceTransformer
import faiss

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
pd.set_option("display.max_colwidth", 120)

def get_secret(name, default=None):
    try:
        from google.colab import userdata
        value = userdata.get(name)
        if value is not None:
            return value
    except Exception:
        pass
    return os.environ.get(name, default)

NEO4J_URI = get_secret("NEO4J_URI", "")
NEO4J_USER = get_secret("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = get_secret("NEO4J_PASSWORD", "")
NEO4J_DATABASE = get_secret("NEO4J_DATABASE", "neo4j")

GROQ_API_KEY = get_secret("GROQ_API_KEY", "")
GROQ_MODEL = get_secret("GROQ_MODEL", "")

JUDGE_PROVIDER = get_secret("JUDGE_PROVIDER", "openai").lower()
JUDGE_MODEL = get_secret("JUDGE_MODEL", "")
OPENAI_API_KEY = get_secret("OPENAI_API_KEY", "")
HF_TOKEN = get_secret("HF_TOKEN", "")

DATA_PATH = "hackernoon_subset.csv"
LAB_MAX_ARTICLES = 1500
LAB_MAX_CHUNKS = 3000
EXTRACTION_MAX_CHUNKS = 400
CHUNK_WORDS = 220
CHUNK_OVERLAP_WORDS = 40

C:\Users\NapoleDong\Documents\Vinuni\LABS\Day19-2A202601851-LeVanDong\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1.3 — Download HackerNoon Dataset bằng Hugging Face Streaming

Cell dưới đây stream trực tiếp dataset **`HackerNoon/tech-company-news-data-dump`** và ghi dần ra CSV, nên không cần tải toàn bộ dataset vào RAM.

### Hai cơ chế giới hạn

- `LIMIT_ROWS`: số dòng tối đa.
- `LIMIT_MB`: dung lượng file tối đa.
- `PRIORITIZE_MB = True`: ưu tiên dừng theo dung lượng MB.
- `PRIORITIZE_MB = False`: thanh tiến trình theo số dòng, nhưng **vẫn giữ hard-stop `LIMIT_ROWS`**.

### Lưu ý

- Đặt `HF_TOKEN` trong **Colab Secrets**, không hard-code token vào notebook.
- Nếu dataset yêu cầu quyền truy cập/gated access, hãy mở trang dataset trên Hugging Face và hoàn tất bước **Agree/Request access** trước.
- Sau khi cell hoàn tất, `DATA_PATH` mặc định đã trỏ tới `/content/hackernoon_subset.csv`, nên cell loader kế tiếp có thể chạy trực tiếp.

In [3]:
#@title 1.3 — Stream HackerNoon dataset -> CSV
import csv
import os
from datasets import load_dataset
from tqdm.auto import tqdm

DATASET_NAME = "HackerNoon/tech-company-news-data-dump"
OUTPUT_CSV = "hackernoon_subset.csv"

# Giới hạn cho bản lab. Có thể tăng sau buổi học.
LIMIT_ROWS = 5000
LIMIT_MB = 300

# True  -> progress/dừng ưu tiên theo MB
# False -> progress theo rows; vẫn có hard-stop LIMIT_ROWS
PRIORITIZE_MB = True

# Đọc từ Colab Secrets qua get_secret() ở cell config.
if not HF_TOKEN:
    raise ValueError(
        "Thiếu HF_TOKEN. Hãy thêm Hugging Face Access Token vào Colab Secrets với tên HF_TOKEN."
    )

print("Đang kết nối luồng dữ liệu (streaming)...")

try:
    dataset = load_dataset(
        DATASET_NAME,
        split="train",
        streaming=True,
        token=HF_TOKEN,
    )
    iterator = iter(dataset)

    first_row = next(iterator)
    headers = list(first_row.keys())

    print(f"Đang ghi dữ liệu vào: {OUTPUT_CSV}")

    rows_written = 0
    total_progress = LIMIT_MB if PRIORITIZE_MB else LIMIT_ROWS
    unit_progress = "MB" if PRIORITIZE_MB else "row"

    with open(OUTPUT_CSV, mode="w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers, extrasaction="ignore")
        writer.writeheader()
        writer.writerow(first_row)
        rows_written += 1

        # Flush để kích thước file phản ánh dữ liệu vừa ghi.
        f.flush()
        file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)

        with tqdm(
            total=total_progress,
            desc=f"Đang tải ({unit_progress})",
            unit=unit_progress,
        ) as pbar:
            if PRIORITIZE_MB:
                pbar.n = min(file_size_mb, LIMIT_MB)
                pbar.refresh()
            else:
                pbar.update(1)

            for row in iterator:
                writer.writerow(row)
                rows_written += 1

                # Kiểm tra dung lượng định kỳ để giảm overhead I/O.
                # Khi gần LIMIT_MB, kiểm tra mỗi row để dừng sát ngưỡng hơn.
                should_check_size = (
                    PRIORITIZE_MB
                    and (
                        rows_written % 100 == 0
                        or file_size_mb >= LIMIT_MB * 0.95
                    )
                )

                if should_check_size:
                    f.flush()
                    file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
                    pbar.n = min(round(file_size_mb, 2), LIMIT_MB)
                    pbar.refresh()
                elif not PRIORITIZE_MB:
                    pbar.update(1)

                # Hard-stop theo MB nếu đang ưu tiên dung lượng.
                if PRIORITIZE_MB and file_size_mb >= LIMIT_MB:
                    print(
                        f"\n[DỪNG] Đã đạt giới hạn dung lượng: "
                        f"{file_size_mb:.2f} MB "
                        f"(Tổng: {rows_written:,} dòng)"
                    )
                    break

                # Hard-stop theo số dòng trong mọi chế độ.
                if rows_written >= LIMIT_ROWS:
                    f.flush()
                    file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
                    print(
                        f"\n[DỪNG] Đã đạt giới hạn số dòng: "
                        f"{rows_written:,} dòng "
                        f"(Dung lượng: {file_size_mb:.2f} MB)"
                    )
                    break

        f.flush()

    final_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
    print(
        f"✅ Hoàn thành: {os.path.abspath(OUTPUT_CSV)}\n"
        f"   Rows: {rows_written:,}\n"
        f"   Size: {final_size_mb:.2f} MB"
    )

    # Đồng bộ đường dẫn cho cell loader tiếp theo.
    DATA_PATH = OUTPUT_CSV

except StopIteration:
    raise RuntimeError("Dataset stream rỗng: không lấy được dòng đầu tiên.")
except Exception as e:
    print(f"\n❌ Có lỗi xảy ra: {e}")
    print(
        "Kiểm tra: (1) HF_TOKEN, (2) quyền Agree/Access trên Hugging Face, "
        "(3) kết nối mạng của Colab."
    )
    raise

Đang kết nối luồng dữ liệu (streaming)...

Đang ghi dữ liệu vào: hackernoon_subset.csv

Đang tải (MB):   0%|          | 0/300 [00:00<?, ?MB/s]

Đang tải (MB):   0%|          | 0.0006494522094726562/300 [00:00<00:14, 21.28MB/s]

Đang tải (MB):   0%|          | 0.06/300 [00:00<00:10, 27.27MB/s]

Đang tải (MB):   0%|          | 0.12/300 [00:00<00:10, 29.39MB/s]

Đang tải (MB):   0%|          | 0.18/300 [00:00<00:10, 28.43MB/s]

Đang tải (MB):   0%|          | 0.24/300 [00:00<00:10, 29.64MB/s]

Đang tải (MB):   0%|          | 0.3/300 [00:00<00:09, 30.36MB/s]

Đang tải (MB):   0%|          | 0.35/300 [00:00<00:09, 30.13MB/s]

Đang tải (MB):   0%|          | 0.41/300 [00:00<00:09, 30.17MB/s]

Đang tải (MB):   0%|          | 0.47/300 [00:00<00:09, 30.70MB/s]

Đang tải (MB):   0%|          | 0.53/300 [00:00<00:09, 31.16MB/s]

Đang tải (MB):   0%|          | 0.59/300 [00:00<00:09, 31.02MB/s]

Đang tải (MB):   0%|          | 0.65/300 [00:00<00:09, 31.18MB/s]

Đang tải (MB):   0%|          | 0.71/300 [00:00<00:09, 31.37MB/s]

Đang tải (MB):   0%|          | 0.77/300 [00:00<00:09, 31.55MB/s]

Đang tải (MB):   0%|          | 0.83/300 [00:00<00:09, 31.41MB/s]

Đang tải (MB):   0%|          | 0.89/300 [00:00<00:09, 31.54MB/s]

Đang tải (MB):   0%|          | 0.95/300 [00:00<00:09, 31.56MB/s]

Đang tải (MB):   0%|          | 1.01/300 [00:00<00:09, 31.56MB/s]

Đang tải (MB):   0%|          | 1.07/300 [00:00<00:09, 31.37MB/s]

Đang tải (MB):   0%|          | 1.13/300 [00:00<00:09, 31.41MB/s]

Đang tải (MB):   0%|          | 1.19/300 [00:00<00:09, 31.52MB/s]

Đang tải (MB):   0%|          | 1.24/300 [00:00<00:09, 31.07MB/s]

Đang tải (MB):   0%|          | 1.3/300 [00:00<00:09, 31.17MB/s]

Đang tải (MB):   0%|          | 1.36/300 [00:00<00:09, 31.26MB/s]

Đang tải (MB):   0%|          | 1.42/300 [00:00<00:09, 31.26MB/s]

Đang tải (MB):   0%|          | 1.47/300 [00:00<00:09, 30.89MB/s]

Đang tải (MB):   1%|          | 1.53/300 [00:00<00:09, 30.90MB/s]

Đang tải (MB):   1%|          | 1.59/300 [00:00<00:09, 31.01MB/s]

Đang tải (MB):   1%|          | 1.64/300 [00:00<00:09, 30.93MB/s]

Đang tải (MB):   1%|          | 1.7/300 [00:00<00:09, 31.03MB/s]

Đang tải (MB):   1%|          | 1.76/300 [00:00<00:09, 31.07MB/s]

Đang tải (MB):   1%|          | 1.82/300 [00:00<00:09, 31.19MB/s]

Đang tải (MB):   1%|          | 1.87/300 [00:00<00:09, 31.16MB/s]

Đang tải (MB):   1%|          | 1.93/300 [00:00<00:09, 31.09MB/s]

Đang tải (MB):   1%|          | 1.99/300 [00:00<00:09, 31.07MB/s]

Đang tải (MB):   1%|          | 2.05/300 [00:00<00:09, 31.01MB/s]

Đang tải (MB):   1%|          | 2.1/300 [00:00<00:09, 30.78MB/s]

Đang tải (MB):   1%|          | 2.16/300 [00:00<00:09, 30.80MB/s]

Đang tải (MB):   1%|          | 2.22/300 [00:00<00:09, 30.90MB/s]

Đang tải (MB):   1%|          | 2.28/300 [00:00<00:09, 30.86MB/s]

Đang tải (MB):   1%|          | 2.34/300 [00:00<00:09, 30.87MB/s]

Đang tải (MB):   1%|          | 2.4/300 [00:00<00:09, 30.86MB/s]

Đang tải (MB):   1%|          | 2.46/300 [00:00<00:09, 30.91MB/s]

Đang tải (MB):   1%|          | 2.52/300 [00:00<00:09, 30.91MB/s]

Đang tải (MB):   1%|          | 2.58/300 [00:00<00:09, 30.85MB/s]

Đang tải (MB):   1%|          | 2.63/300 [00:00<00:09, 30.77MB/s]

Đang tải (MB):   1%|          | 2.69/300 [00:00<00:09, 30.90MB/s]

Đang tải (MB):   1%|          | 2.75/300 [00:00<00:09, 30.71MB/s]

Đang tải (MB):   1%|          | 2.81/300 [00:00<00:09, 30.68MB/s]

Đang tải (MB):   1%|          | 2.87/300 [00:00<00:09, 30.66MB/s]

Đang tải (MB):   1%|          | 2.92/300 [00:00<00:09, 30.56MB/s]

Đang tải (MB):   1%|          | 2.92/300 [00:00<00:09, 30.35MB/s]

[DỪNG] Đã đạt giới hạn số dòng: 5,000 dòng (Dung lượng: 2.92 MB)
✅ Hoàn thành: C:\Users\NapoleDong\Documents\Vinuni\LABS\Day19-2A202601851-LeVanDong\hackernoon_subset.csv
   Rows: 5,000
   Size: 2.92 MB

In [4]:
#@title 1.4 — Neo4j connection + schema
driver = None

def connect_neo4j():
    global driver
    if not NEO4J_URI or not NEO4J_PASSWORD:
        raise ValueError("Thiếu Neo4j secrets.")
    driver = GraphDatabase.driver(
        NEO4J_URI,
        auth=(NEO4J_USER, NEO4J_PASSWORD),
    )
    driver.verify_connectivity()
    print("✅ Neo4j connected.")

def run_cypher(query, **params):
    if driver is None:
        raise RuntimeError("Hãy chạy connect_neo4j() trước.")
    with driver.session(database=NEO4J_DATABASE) as session:
        result = session.run(query, **params)
        rows = [r.data() for r in result]
        result.consume()
    return rows

def setup_graph_schema():
    for stmt in [
        """
        CREATE CONSTRAINT entity_id IF NOT EXISTS
        FOR (n:Entity) REQUIRE n.id IS UNIQUE
        """,
        """
        CREATE INDEX entity_name_norm IF NOT EXISTS
        FOR (n:Entity) ON (n.name_norm)
        """,
        """
        CREATE INDEX company_name_norm IF NOT EXISTS
        FOR (n:Company) ON (n.name_norm)
        """,
        """
        CREATE INDEX person_name_norm IF NOT EXISTS
        FOR (n:Person) ON (n.name_norm)
        """,
        """
        CREATE INDEX technology_name_norm IF NOT EXISTS
        FOR (n:Technology) ON (n.name_norm)
        """,
    ]:
        run_cypher(stmt)
    print("✅ Schema ready.")

connect_neo4j()
setup_graph_schema()

✅ Neo4j connected.

✅ Schema ready.

In [5]:
#@title 1.5 — Loader + exact dedup + chunking
def norm_space(x):
    return re.sub(r"\s+", " ", str(x or "")).strip()

def sha1(x):
    return hashlib.sha1(str(x).encode("utf-8", errors="ignore")).hexdigest()

def pick_col(df, candidates, required=True):
    lookup = {str(c).lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lookup:
            return lookup[c.lower()]
    if required:
        raise KeyError(f"Missing one of columns: {candidates}")
    return None

def load_news(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    if path.suffix.lower() in {".jsonl", ".ndjson"}:
        return pd.read_json(path, lines=True)
    if path.suffix.lower() == ".json":
        return pd.read_json(path)
    if path.suffix.lower() in {".parquet", ".pq"}:
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported: {path.suffix}")

def standardize_news(raw):
    text_col = pick_col(raw, ["text", "content", "article", "body", "story", "description"])
    title_col = pick_col(raw, ["title", "headline"], required=False)
    date_col = pick_col(raw, ["published_date", "date", "published_at", "created_at"], required=False)
    id_col = pick_col(raw, ["id", "article_id", "story_id", "uuid"], required=False)

    df = pd.DataFrame()
    df["text"] = raw[text_col].fillna("").map(norm_space)
    df["title"] = raw[title_col].fillna("").map(norm_space) if title_col else ""

    if date_col:
        df["published_date"] = (
            pd.to_datetime(raw[date_col], errors="coerce", utc=True)
            .dt.strftime("%Y-%m-%d")
            .fillna("")
        )
    else:
        df["published_date"] = ""

    if id_col:
        df["article_id"] = raw[id_col].astype(str)
    else:
        df["article_id"] = [
            sha1(f"{t}\n{x}")[:20] for t, x in zip(df["title"], df["text"])
        ]

    df = df[df["text"].str.len() >= 80].copy()
    df["dedup_key"] = [
        sha1(norm_space(f"{t}\n{x}").lower())
        for t, x in zip(df["title"], df["text"])
    ]
    before = len(df)
    df = df.drop_duplicates("dedup_key").drop(columns="dedup_key").reset_index(drop=True)
    print(f"Exact dedup: {before:,} -> {len(df):,}")

    # --- Challenge A: Near Dedup (AnnoyAnn / FAISS) ---
    print("Running Near Dedup with faiss for Challenge A...")
    embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    texts_to_embed = df["title"].fillna("") + " " + df["text"].fillna("")
    vecs = embedder.encode(texts_to_embed.tolist(), batch_size=128, show_progress_bar=False, normalize_embeddings=True).astype("float32")
    
    index = faiss.IndexFlatIP(vecs.shape[1])
    index.add(vecs)
    sims, nbrs = index.search(vecs, 2)
    to_drop = set()
    for i in range(len(df)):
        if i in to_drop:
            continue
        j = nbrs[i][1]
        score = sims[i][1]
        if j != -1 and j != i and score >= 0.95:
            to_drop.add(j)
            
    df = df.drop(index=list(to_drop)).reset_index(drop=True)
    print(f"Near dedup: dropped {len(to_drop)} near-duplicates. -> {len(df):,}")
    # --- End Challenge A ---

    if LAB_MAX_ARTICLES and len(df) > LAB_MAX_ARTICLES:
        df = df.sample(LAB_MAX_ARTICLES, random_state=SEED).sort_index().reset_index(drop=True)
    return df

def chunk_text(text, size=220, overlap=40):
    words = norm_space(text).split()
    step = max(1, size - overlap)
    out = []
    for start in range(0, len(words), step):
        part = words[start:start+size]
        if not part:
            break
        out.append(" ".join(part))
        if start + size >= len(words):
            break
    return out

def build_chunks(news_df):
    rows = []
    for r in tqdm(news_df.itertuples(index=False), total=len(news_df), desc="Chunking"):
        for i, text in enumerate(chunk_text(r.text, CHUNK_WORDS, CHUNK_OVERLAP_WORDS)):
            rows.append({
                "chunk_id": f"{r.article_id}::c{i:04d}",
                "article_id": r.article_id,
                "title": r.title,
                "published_date": r.published_date,
                "text": text,
            })
            if LAB_MAX_CHUNKS and len(rows) >= LAB_MAX_CHUNKS:
                return pd.DataFrame(rows)
    return pd.DataFrame(rows)

raw_df = load_news(DATA_PATH)
news_df = standardize_news(raw_df)
chunks_df = build_chunks(news_df)
display(chunks_df.head())

Exact dedup: 2,675 -> 2,105
Running Near Dedup with faiss for Challenge A...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9374.27it/s]

Near dedup: dropped 32 near-duplicates. -> 2,073

Chunking:   0%|          | 0/1500 [00:00<?, ?it/s]

Chunking: 100%|██████████| 1500/1500 [00:00<00:00, 33436.02it/s]

,chunk_id,article_id,title,published_date,text
0,1a05beb7aa3071be6fd7::c0000,1a05beb7aa3071be6fd7,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications,2023-05-16,(Nasdaq: ON) a leader in intelligent power and sensing technologies today announced that Sineng Electric will integr...
1,8e922bc62b578e73e815::c0000,8e922bc62b578e73e815,Modernizing State Services: Harnessing Technology for Enhanced Public Service Delivery,2023-05-01,To deliver 21st-century government services Governors and cabinet members need leaders with technology expertise to ...
2,4bd7afdba71243b0dbcd::c0000,4bd7afdba71243b0dbcd,Terry Richardson On Why He Left AMD GreenPages’ Technology Chops And The AI Opportunity,2023-05-02,In February GreenPages acquired Toronto-based Zanaris an IT automation cloud and DevOps services firm ... Steve Burk...
3,6633c15d86f5e81f47b8::c0000,6633c15d86f5e81f47b8,5 Kubernetes technology vendors hot right now,2023-02-28,Kubernetes is a technology that has created a whole new ecosystem around itself and it is now a key plank in the Dev...
4,4ce72a4490a6a618e2d5::c0000,4ce72a4490a6a618e2d5,Bachelor of Science in Health Information Management,2023-08-16,Health information management (HIM) is a diverse yet evolving field that incorporates medicine management finance in...

### 🎯 AI Coding Agent Challenge A — Near Dedup
Exact hash không bắt được bài repost/near-duplicate.

Hãy dùng AI Agent thiết kế thêm **MinHash/LSH, SimHash hoặc embedding+ANN**.  
**Không chấp nhận** pairwise cosine `O(N²)` trên toàn dataset.

Trong báo cáo nêu:
1. threshold,
2. false positive,
3. cách audit cặp bị merge.

In [6]:
#@title 1.6 - LLM wrapper (Patched to use OpenAI for speed)
import openai, time, random, json
def parse_json_object(text):
    import re
    text = str(text).strip()
    text = re.sub(r'^```(?:json)?\s*', '', text, flags=re.I)
    text = re.sub(r'\s*```$', '', text)
    a, b = text.find('{'), text.rfind('}')
    if a < 0 or b <= a:
        raise ValueError('No JSON object found.')
    return json.loads(text[a:b+1])

def groq_chat(messages, model=None, json_mode=False, max_retries=4):
    client = openai.OpenAI(api_key=OPENAI_API_KEY)
    model = model or 'gpt-4o-mini'
    last = None
    for attempt in range(max_retries):
        try:
            kwargs = {'model': model, 'messages': messages, 'temperature': 0.0}
            if json_mode:
                kwargs['response_format'] = {'type': 'json_object'}
            resp = client.chat.completions.create(**kwargs)
            usage = {}
            if getattr(resp, 'usage', None):
                usage = {'total_tokens': getattr(resp.usage, 'total_tokens', None)}
            return resp.choices[0].message.content, usage
        except Exception as e:
            last = e
            print(f'OpenAI API error: {e}, retrying...')
            if attempt == max_retries - 1: break
            time.sleep(min(20, 2**attempt + random.random()))
    raise RuntimeError(last)

def groq_json(system, user, model=None):
    text, usage = groq_chat([{'role': 'system', 'content': system}, {'role': 'user', 'content': user}], model=model, json_mode=True)
    return parse_json_object(text), usage

## 1.7 — Coreference Resolution

Yêu cầu:
- chỉ resolve đại từ khi antecedent rõ trong cùng chunk,
- không invent fact,
- giữ nguyên số/ngày/ticker/product,
- ambiguity → giữ nguyên và log `unresolved_mentions`.

**Failure mode quan trọng:** false coreference → false edge.

In [7]:
#@title 1.7 — Coreference resolution theo batch
COREF_SYSTEM = """
You are a conservative coreference-resolution component for a knowledge-graph pipeline.
Resolve pronouns and generic references only when the antecedent is clearly supported in the same chunk.
Never invent facts. Preserve dates, numbers, tickers and product names.
Return strict JSON only.
""".strip()

def resolve_coref_batch(batch_df):
    payload = [{"chunk_id": r.chunk_id, "text": r.text}
               for r in batch_df.itertuples(index=False)]

    prompt = f"""
Resolve coreferences.

Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "resolved_text": "...",
      "unresolved_mentions": ["..."]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()

    obj, usage = groq_json(COREF_SYSTEM, prompt)
    by_id = {x.get("chunk_id"): x for x in obj.get("items", [])}

    rows = []
    for r in batch_df.itertuples(index=False):
        item = by_id.get(r.chunk_id, {})
        rows.append({
            "chunk_id": r.chunk_id,
            "resolved_text": norm_space(item.get("resolved_text") or r.text),
            "unresolved_mentions": item.get("unresolved_mentions", []),
        })
    return pd.DataFrame(rows), usage

def run_coref(chunks_subset, batch_size=5):
    out = []
    for start in tqdm(range(0, len(chunks_subset), batch_size), desc="Coref"):
        batch = chunks_subset.iloc[start:start+batch_size]
        try:
            df, _ = resolve_coref_batch(batch)
        except Exception:
            df = pd.DataFrame({
                "chunk_id": batch["chunk_id"].tolist(),
                "resolved_text": batch["text"].tolist(),
                "unresolved_mentions": [["COREF_BATCH_FAILED"] for _ in range(len(batch))],
            })
        out.append(df)
    return pd.concat(out, ignore_index=True)

extraction_source = chunks_df.head(EXTRACTION_MAX_CHUNKS).copy()
coref_df = run_coref(extraction_source)
extraction_source = extraction_source.merge(coref_df, on="chunk_id", how="left")

Coref:   0%|          | 0/80 [00:00<?, ?it/s]

Coref:   1%|▏         | 1/80 [00:04<06:28,  4.92s/it]

Coref:   2%|▎         | 2/80 [00:09<06:27,  4.97s/it]

Coref:   4%|▍         | 3/80 [00:14<06:24,  4.99s/it]

Coref:   5%|▌         | 4/80 [00:21<06:52,  5.43s/it]

Coref:   6%|▋         | 5/80 [00:26<06:50,  5.48s/it]

Coref:   8%|▊         | 6/80 [00:31<06:27,  5.24s/it]

Coref:   9%|▉         | 7/80 [00:35<06:06,  5.02s/it]

Coref:  10%|█         | 8/80 [00:42<06:44,  5.62s/it]

Coref:  11%|█▏        | 9/80 [00:47<06:19,  5.34s/it]

Coref:  12%|█▎        | 10/80 [00:52<06:05,  5.22s/it]

Coref:  14%|█▍        | 11/80 [01:00<06:59,  6.07s/it]

Coref:  15%|█▌        | 12/80 [01:05<06:38,  5.86s/it]

Coref:  16%|█▋        | 13/80 [01:10<06:13,  5.57s/it]

Coref:  18%|█▊        | 14/80 [01:14<05:36,  5.11s/it]

Coref:  19%|█▉        | 15/80 [01:18<05:12,  4.81s/it]

Coref:  20%|██        | 16/80 [01:23<05:08,  4.82s/it]

Coref:  21%|██▏       | 17/80 [01:27<04:47,  4.56s/it]

Coref:  22%|██▎       | 18/80 [01:33<04:57,  4.81s/it]

Coref:  24%|██▍       | 19/80 [01:39<05:14,  5.16s/it]

Coref:  25%|██▌       | 20/80 [01:43<04:56,  4.95s/it]

Coref:  26%|██▋       | 21/80 [01:49<05:00,  5.10s/it]

Coref:  28%|██▊       | 22/80 [01:53<04:44,  4.90s/it]

Coref:  29%|██▉       | 23/80 [02:01<05:32,  5.82s/it]

Coref:  30%|███       | 24/80 [02:09<06:06,  6.54s/it]

Coref:  31%|███▏      | 25/80 [02:14<05:24,  5.90s/it]

Coref:  32%|███▎      | 26/80 [02:18<04:57,  5.50s/it]

Coref:  34%|███▍      | 27/80 [02:23<04:42,  5.33s/it]

Coref:  35%|███▌      | 28/80 [02:27<04:15,  4.91s/it]

Coref:  36%|███▋      | 29/80 [02:31<03:58,  4.68s/it]

Coref:  38%|███▊      | 30/80 [02:35<03:46,  4.53s/it]

Coref:  39%|███▉      | 31/80 [02:41<04:05,  5.00s/it]

Coref:  40%|████      | 32/80 [02:49<04:37,  5.78s/it]

Coref:  41%|████▏     | 33/80 [02:56<04:47,  6.12s/it]

Coref:  42%|████▎     | 34/80 [03:00<04:11,  5.46s/it]

Coref:  44%|████▍     | 35/80 [03:05<03:58,  5.30s/it]

Coref:  45%|████▌     | 36/80 [03:09<03:34,  4.87s/it]

Coref:  46%|████▋     | 37/80 [03:13<03:18,  4.62s/it]

Coref:  48%|████▊     | 38/80 [03:17<03:08,  4.49s/it]

Coref:  49%|████▉     | 39/80 [03:23<03:25,  5.01s/it]

Coref:  50%|█████     | 40/80 [03:30<03:40,  5.51s/it]

Coref:  51%|█████▏    | 41/80 [03:38<04:01,  6.19s/it]

Coref:  52%|█████▎    | 42/80 [03:44<03:57,  6.25s/it]

Coref:  54%|█████▍    | 43/80 [03:48<03:29,  5.66s/it]

Coref:  55%|█████▌    | 44/80 [03:53<03:15,  5.43s/it]

Coref:  56%|█████▋    | 45/80 [03:58<03:01,  5.18s/it]

Coref:  57%|█████▊    | 46/80 [04:03<02:58,  5.26s/it]

Coref:  59%|█████▉    | 47/80 [04:06<02:34,  4.67s/it]

Coref:  60%|██████    | 48/80 [04:11<02:28,  4.63s/it]

Coref:  61%|██████▏   | 49/80 [04:18<02:42,  5.23s/it]

Coref:  62%|██████▎   | 50/80 [04:22<02:25,  4.85s/it]

Coref:  64%|██████▍   | 51/80 [04:26<02:19,  4.82s/it]

Coref:  65%|██████▌   | 52/80 [04:31<02:13,  4.77s/it]

Coref:  66%|██████▋   | 53/80 [04:35<02:04,  4.62s/it]

Coref:  68%|██████▊   | 54/80 [04:41<02:07,  4.90s/it]

Coref:  69%|██████▉   | 55/80 [04:45<01:56,  4.67s/it]

Coref:  70%|███████   | 56/80 [04:51<02:00,  5.01s/it]

Coref:  71%|███████▏  | 57/80 [04:55<01:47,  4.68s/it]

Coref:  72%|███████▎  | 58/80 [05:00<01:44,  4.75s/it]

Coref:  74%|███████▍  | 59/80 [05:05<01:42,  4.86s/it]

Coref:  75%|███████▌  | 60/80 [05:09<01:32,  4.64s/it]

Coref:  76%|███████▋  | 61/80 [05:15<01:38,  5.20s/it]

Coref:  78%|███████▊  | 62/80 [05:20<01:32,  5.11s/it]

Coref:  79%|███████▉  | 63/80 [05:26<01:28,  5.22s/it]

Coref:  80%|████████  | 64/80 [05:30<01:19,  4.95s/it]

Coref:  81%|████████▏ | 65/80 [05:35<01:12,  4.86s/it]

Coref:  82%|████████▎ | 66/80 [05:40<01:08,  4.89s/it]

Coref:  84%|████████▍ | 67/80 [05:46<01:10,  5.43s/it]

Coref:  85%|████████▌ | 68/80 [05:51<01:01,  5.09s/it]

Coref:  86%|████████▋ | 69/80 [05:55<00:53,  4.87s/it]

Coref:  88%|████████▊ | 70/80 [06:00<00:47,  4.79s/it]

Coref:  89%|████████▉ | 71/80 [06:04<00:42,  4.71s/it]

Coref:  90%|█████████ | 72/80 [06:10<00:39,  4.99s/it]

Coref:  91%|█████████▏| 73/80 [06:14<00:32,  4.65s/it]

Coref:  92%|█████████▎| 74/80 [06:18<00:28,  4.71s/it]

Coref:  94%|█████████▍| 75/80 [06:25<00:25,  5.12s/it]

Coref:  95%|█████████▌| 76/80 [06:30<00:20,  5.22s/it]

Coref:  96%|█████████▋| 77/80 [06:37<00:16,  5.61s/it]

Coref:  98%|█████████▊| 78/80 [06:43<00:11,  5.75s/it]

Coref:  99%|█████████▉| 79/80 [06:51<00:06,  6.60s/it]

Coref: 100%|██████████| 80/80 [06:57<00:00,  6.41s/it]

Coref: 100%|██████████| 80/80 [06:57<00:00,  5.22s/it]

# PHẦN 2 — TRIPLE EXTRACTION & NEO4J BULK INSERT (15–45')

## Graph schema
**Nodes:** `Company`, `Person`, `Technology` + base label `Entity`.

**Relations:** `ACQUIRED`, `DEVELOPED`, `INVESTED_IN`, `FOUNDED`, `WORKED_AT`, `PARTNERED_WITH`, `USES`, `LEADS`.

**Mỗi edge bắt buộc:** `source_chunk_id`, `published_date`; khuyến nghị thêm `evidence`, `confidence`.

> Relation type phải qua allowlist trước khi ghép vào Cypher.

In [8]:
#@title 2.1 — NER + RE extraction
ALLOWED_NODE_TYPES = {"Company", "Person", "Technology"}
ALLOWED_RELATIONS = {
    "ACQUIRED", "DEVELOPED", "INVESTED_IN", "FOUNDED",
    "WORKED_AT", "PARTNERED_WITH", "USES", "LEADS"
}

EXTRACT_SYSTEM = f"""
Extract a high-precision knowledge graph from tech-news text.
Allowed node types: {sorted(ALLOWED_NODE_TYPES)}
Allowed relations: {sorted(ALLOWED_RELATIONS)}
Use only explicitly supported facts. Prefer precision over recall.
Every relation needs short evidence. Return strict JSON only.
""".strip()

def extract_batch(batch_df):
    payload = [{
        "chunk_id": r.chunk_id,
        "published_date": r.published_date,
        "text": getattr(r, "resolved_text", None) or r.text,
    } for r in batch_df.itertuples(index=False)]

    prompt = f"""
Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "relations": [
        {{
          "source": "...",
          "source_type": "Company|Person|Technology",
          "relation": "ALLOWED_RELATION",
          "target": "...",
          "target_type": "Company|Person|Technology",
          "evidence": "...",
          "confidence": 0.0
        }}
      ]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()
    return groq_json(EXTRACT_SYSTEM, prompt)

def run_extraction(source_df, batch_size=4):
    meta = source_df.set_index("chunk_id")["published_date"].to_dict()
    triples, errors = [], []

    for start in tqdm(range(0, len(source_df), batch_size), desc="NER+RE"):
        batch = source_df.iloc[start:start+batch_size]
        try:
            obj, _ = extract_batch(batch)
        except Exception as e:
            errors.append({"start": start, "error": str(e)})
            continue

        for item in obj.get("items", []):
            cid = item.get("chunk_id")
            if cid not in meta:
                continue
            for x in item.get("relations", []):
                s, t = norm_space(x.get("source")), norm_space(x.get("target"))
                st, tt, rel = x.get("source_type"), x.get("target_type"), x.get("relation")
                if not s or not t:
                    continue
                if st not in ALLOWED_NODE_TYPES or tt not in ALLOWED_NODE_TYPES:
                    continue
                if rel not in ALLOWED_RELATIONS:
                    continue
                triples.append({
                    "source_raw": s,
                    "source_type": st,
                    "relation": rel,
                    "target_raw": t,
                    "target_type": tt,
                    "source_chunk_id": cid,
                    "published_date": meta[cid] or "",
                    "evidence": norm_space(x.get("evidence")),
                    "confidence": float(x.get("confidence") or 0.0),
                })

    return pd.DataFrame(triples), pd.DataFrame(errors)

raw_triples_df, extraction_errors_df = run_extraction(extraction_source)
display(raw_triples_df.head())

NER+RE:   0%|          | 0/100 [00:00<?, ?it/s]

NER+RE:   1%|          | 1/100 [00:04<08:10,  4.95s/it]

NER+RE:   2%|▏         | 2/100 [00:05<03:57,  2.43s/it]

NER+RE:   3%|▎         | 3/100 [00:09<05:08,  3.18s/it]

NER+RE:   4%|▍         | 4/100 [00:10<03:32,  2.22s/it]

NER+RE:   5%|▌         | 5/100 [00:14<04:40,  2.95s/it]

NER+RE:   6%|▌         | 6/100 [00:21<06:38,  4.24s/it]

NER+RE:   7%|▋         | 7/100 [00:26<07:09,  4.61s/it]

NER+RE:   8%|▊         | 8/100 [00:32<07:27,  4.87s/it]

NER+RE:   9%|▉         | 9/100 [00:38<08:16,  5.45s/it]

NER+RE:  10%|█         | 10/100 [00:39<06:03,  4.04s/it]

NER+RE:  11%|█         | 11/100 [00:45<06:36,  4.46s/it]

NER+RE:  12%|█▏        | 12/100 [00:47<05:28,  3.73s/it]

NER+RE:  13%|█▎        | 13/100 [00:48<04:26,  3.07s/it]

NER+RE:  14%|█▍        | 14/100 [00:49<03:24,  2.38s/it]

NER+RE:  15%|█▌        | 15/100 [00:53<03:58,  2.81s/it]

NER+RE:  16%|█▌        | 16/100 [00:54<03:00,  2.15s/it]

NER+RE:  17%|█▋        | 17/100 [00:56<03:10,  2.29s/it]

NER+RE:  18%|█▊        | 18/100 [01:01<04:11,  3.06s/it]

NER+RE:  19%|█▉        | 19/100 [01:07<05:17,  3.91s/it]

NER+RE:  20%|██        | 20/100 [01:09<04:35,  3.44s/it]

NER+RE:  21%|██        | 21/100 [01:14<05:08,  3.91s/it]

NER+RE:  22%|██▏       | 22/100 [01:19<05:32,  4.26s/it]

NER+RE:  23%|██▎       | 23/100 [01:24<05:45,  4.48s/it]

NER+RE:  24%|██▍       | 24/100 [01:30<06:14,  4.93s/it]

NER+RE:  25%|██▌       | 25/100 [01:32<05:00,  4.01s/it]

NER+RE:  26%|██▌       | 26/100 [01:36<04:46,  3.88s/it]

NER+RE:  27%|██▋       | 27/100 [01:38<04:04,  3.35s/it]

NER+RE:  28%|██▊       | 28/100 [01:44<05:11,  4.32s/it]

NER+RE:  29%|██▉       | 29/100 [01:48<04:52,  4.13s/it]

NER+RE:  30%|███       | 30/100 [01:49<03:41,  3.16s/it]

NER+RE:  31%|███       | 31/100 [01:56<04:53,  4.26s/it]

NER+RE:  32%|███▏      | 32/100 [01:57<03:43,  3.28s/it]

NER+RE:  33%|███▎      | 33/100 [01:58<02:48,  2.51s/it]

NER+RE:  34%|███▍      | 34/100 [02:01<03:10,  2.89s/it]

NER+RE:  35%|███▌      | 35/100 [02:02<02:30,  2.32s/it]

NER+RE:  36%|███▌      | 36/100 [02:03<02:00,  1.88s/it]

NER+RE:  37%|███▋      | 37/100 [02:09<03:16,  3.11s/it]

NER+RE:  38%|███▊      | 38/100 [02:10<02:29,  2.42s/it]

NER+RE:  39%|███▉      | 39/100 [02:14<02:52,  2.82s/it]

NER+RE:  40%|████      | 40/100 [02:16<02:35,  2.58s/it]

NER+RE:  41%|████      | 41/100 [02:19<02:38,  2.68s/it]

NER+RE:  42%|████▏     | 42/100 [02:19<02:00,  2.08s/it]

NER+RE:  43%|████▎     | 43/100 [02:22<02:13,  2.35s/it]

NER+RE:  44%|████▍     | 44/100 [02:23<01:45,  1.89s/it]

NER+RE:  45%|████▌     | 45/100 [02:26<01:51,  2.04s/it]

NER+RE:  46%|████▌     | 46/100 [02:26<01:29,  1.65s/it]

NER+RE:  47%|████▋     | 47/100 [02:35<03:15,  3.69s/it]

NER+RE:  48%|████▊     | 48/100 [02:36<02:37,  3.03s/it]

NER+RE:  49%|████▉     | 49/100 [02:37<02:00,  2.36s/it]

NER+RE:  50%|█████     | 50/100 [02:38<01:34,  1.89s/it]

NER+RE:  51%|█████     | 51/100 [02:41<01:57,  2.40s/it]

NER+RE:  52%|█████▏    | 52/100 [02:46<02:24,  3.01s/it]

NER+RE:  53%|█████▎    | 53/100 [02:47<01:50,  2.35s/it]

NER+RE:  54%|█████▍    | 54/100 [02:51<02:08,  2.80s/it]

NER+RE:  55%|█████▌    | 55/100 [02:56<02:44,  3.65s/it]

NER+RE:  56%|█████▌    | 56/100 [03:03<03:24,  4.65s/it]

NER+RE:  57%|█████▋    | 57/100 [03:04<02:30,  3.50s/it]

NER+RE:  58%|█████▊    | 58/100 [03:10<02:56,  4.20s/it]

NER+RE:  59%|█████▉    | 59/100 [03:18<03:35,  5.26s/it]

NER+RE:  60%|██████    | 60/100 [03:21<03:14,  4.86s/it]

NER+RE:  61%|██████    | 61/100 [03:22<02:20,  3.61s/it]

NER+RE:  62%|██████▏   | 62/100 [03:26<02:21,  3.71s/it]

NER+RE:  63%|██████▎   | 63/100 [03:33<02:48,  4.56s/it]

NER+RE:  64%|██████▍   | 64/100 [03:40<03:12,  5.34s/it]

NER+RE:  65%|██████▌   | 65/100 [03:43<02:39,  4.56s/it]

NER+RE:  66%|██████▌   | 66/100 [03:45<02:12,  3.89s/it]

NER+RE:  67%|██████▋   | 67/100 [03:49<02:09,  3.91s/it]

NER+RE:  68%|██████▊   | 68/100 [03:54<02:12,  4.15s/it]

NER+RE:  69%|██████▉   | 69/100 [03:58<02:08,  4.13s/it]

NER+RE:  70%|███████   | 70/100 [03:59<01:35,  3.17s/it]

NER+RE:  71%|███████   | 71/100 [03:59<01:10,  2.43s/it]

NER+RE:  72%|███████▏  | 72/100 [04:00<00:57,  2.06s/it]

NER+RE:  73%|███████▎  | 73/100 [04:04<01:10,  2.62s/it]

NER+RE:  74%|███████▍  | 74/100 [04:11<01:36,  3.69s/it]

NER+RE:  75%|███████▌  | 75/100 [04:13<01:24,  3.38s/it]

NER+RE:  76%|███████▌  | 76/100 [04:16<01:17,  3.21s/it]

NER+RE:  77%|███████▋  | 77/100 [04:22<01:35,  4.17s/it]

NER+RE:  78%|███████▊  | 78/100 [04:31<01:57,  5.36s/it]

NER+RE:  79%|███████▉  | 79/100 [04:37<01:58,  5.63s/it]

NER+RE:  80%|████████  | 80/100 [04:41<01:42,  5.11s/it]

NER+RE:  81%|████████  | 81/100 [04:47<01:42,  5.42s/it]

NER+RE:  82%|████████▏ | 82/100 [04:50<01:25,  4.76s/it]

NER+RE:  83%|████████▎ | 83/100 [04:55<01:24,  4.94s/it]

NER+RE:  84%|████████▍ | 84/100 [04:58<01:05,  4.10s/it]

NER+RE:  85%|████████▌ | 85/100 [05:00<00:53,  3.54s/it]

NER+RE:  86%|████████▌ | 86/100 [05:01<00:37,  2.68s/it]

NER+RE:  87%|████████▋ | 87/100 [05:01<00:27,  2.08s/it]

NER+RE:  88%|████████▊ | 88/100 [05:04<00:25,  2.16s/it]

NER+RE:  89%|████████▉ | 89/100 [05:04<00:19,  1.74s/it]

NER+RE:  90%|█████████ | 90/100 [05:08<00:22,  2.29s/it]

NER+RE:  91%|█████████ | 91/100 [05:10<00:21,  2.38s/it]

NER+RE:  92%|█████████▏| 92/100 [05:17<00:30,  3.77s/it]

NER+RE:  93%|█████████▎| 93/100 [05:25<00:34,  4.98s/it]

NER+RE:  94%|█████████▍| 94/100 [05:33<00:35,  5.93s/it]

NER+RE:  95%|█████████▌| 95/100 [05:39<00:29,  5.91s/it]

NER+RE:  96%|█████████▌| 96/100 [05:43<00:20,  5.23s/it]

NER+RE:  97%|█████████▋| 97/100 [05:49<00:16,  5.59s/it]

NER+RE:  98%|█████████▊| 98/100 [05:57<00:12,  6.17s/it]

NER+RE:  99%|█████████▉| 99/100 [05:58<00:04,  4.64s/it]

NER+RE: 100%|██████████| 100/100 [06:03<00:00,  4.72s/it]

NER+RE: 100%|██████████| 100/100 [06:03<00:00,  3.63s/it]

,source_raw,source_type,relation,target_raw,target_type,source_chunk_id,published_date,evidence,confidence
0,GreenPages,Company,ACQUIRED,Zanaris,Company,4bd7afdba71243b0dbcd::c0000,2023-05-02,"GreenPages acquired Toronto-based Zanaris, an IT automation cloud and DevOps services firm",1.0
1,Sineng Electric,Company,PARTNERED_WITH,onsemi,Company,1a05beb7aa3071be6fd7::c0000,2023-05-16,Sineng Electric will integrate onsemi EliteSiC silic,1.0
2,Kubernetes,Technology,DEVELOPED,DevOps,Technology,6633c15d86f5e81f47b8::c0000,2023-02-28,Kubernetes is now a key plank in the DevOps movement,1.0
3,Aeris Communications,Company,PARTNERED_WITH,Ericsson,Company,4f1346392056a403277d::c0000,2022-12-07,Aeris Communications and Ericsson are joining together,1.0
4,Stewart Information Services Corporation,Company,WORKED_AT,property and casualty insurance industry,Technology,e6f458adb39e8a23889e::c0000,2023-08-14,Stewart Information Services Corporation is in the property and casualty insurance industry.,1.0

## 2.2 — Entity Resolution bằng Vector Similarity

Pipeline:
1. Manual aliases cho ticker/tên rất phổ biến.
2. Embedding ANN candidate.
3. Lexical guard để giảm false merge.
4. Xuất audit table.

### 🎯 AI Coding Agent Challenge B
Cải tiến guard cho:
- ticker,
- suffix `Inc./Corp./Ltd.`,
- product chứa company name,
- người trùng họ/tên gần giống.

In [9]:
display(extraction_errors_df)

Empty DataFrame
Columns: []
Index: []

In [10]:
#@title 2.2 â‌— Entity resolution
import unicodedata, re
from collections import Counter, defaultdict
from difflib import SequenceMatcher
from sentence_transformers import SentenceTransformer
import faiss
import pandas as pd
from hashlib import sha1

CORP_SUFFIXES = {"inc","incorporated","corp","corporation","ltd","limited","llc","plc","co","company", "group", "holdings", "technologies", "tech"}
MANUAL_ALIASES = {
    "msft": "Microsoft", "microsoft corp": "Microsoft", "microsoft corporation": "Microsoft",
    "goog": "Google", "googl": "Google", "google llc": "Google", "alphabet": "Google", "alphabet inc": "Google",
    "meta platforms": "Meta", "meta platforms inc": "Meta", "fb": "Meta", "facebook": "Meta",
    "aapl": "Apple", "apple inc": "Apple",
    "amzn": "Amazon", "amazon.com": "Amazon", "amazon com inc": "Amazon",
    "tsla": "Tesla", "tesla inc": "Tesla",
    "nvda": "Nvidia", "nvidia corp": "Nvidia",
    "nflx": "Netflix", "netflix inc": "Netflix"
}

def norm_entity(name):
    s = unicodedata.normalize("NFKC", str(name)).lower()
    s = re.sub(r'%[^\w\s\-\.]', " ", s)
    return re.sub(r'\s+', " ", s).strip()

def strip_suffix(name):
    toks = norm_entity(name).replace(".", "").split()
    while toks and toks[-1] in CORP_SUFFIXES:
        toks.pop()
    return " ".join(toks)


def merge_guard(a, b):
    na, nb = strip_suffix(a), strip_suffix(b)
    if na == nb:
        return True
        
    wa, wb = na.split(), nb.split()
    
    # 1. Ticker guard: if one is a short ticker (<=4 chars without spaces) 
    # and the other is also short but different, or if it's not a known alias, reject.
    if (len(na) <= 4 and " " not in na) or (len(nb) <= 4 and " " not in nb):
        if na != nb:
            return False
            
    # 2. Product guard / subset guard: e.g. "apple" vs "apple vision pro"
    if set(wa).issubset(set(wb)) and len(wa) < len(wb):
        return False
    if set(wb).issubset(set(wa)) and len(wb) < len(wa):
        return False
        
    # 3. Person name guard: e.g. "john smith" vs "jane smith"
    if len(wa) == len(wb) and len(wa) > 1:
        # If they share the same length of words, but have a completely different word (e.g. first name mismatch)
        diff_count = sum(1 for x, y in zip(wa, wb) if x != y)
        if diff_count > 0:
            return False
            
    # Fallback lexical similarity
    return SequenceMatcher(None, na, nb).ratio() >= 0.72

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
embedder = None

def get_embedder():
    global embedder
    if embedder is None:
        embedder = SentenceTransformer(EMBED_MODEL)
    return embedder

class UF:
    def __init__(self, n):
        self.p = list(range(n))
    def find(self, x):
        if self.p[x] != x:
            self.p[x] = self.find(self.p[x])
        return self.p[x]
    def union(self, a, b):
        a, b = self.find(a), self.find(b)
        if a != b:
            self.p[b] = a

def build_resolution_map(raw_triples_df, threshold=0.90, top_k=5):
    mentions = []
    for r in raw_triples_df.itertuples(index=False):
        mentions += [(r.source_type, r.source_raw), (r.target_type, r.target_raw)]

    counts = Counter((t, norm_entity(n)) for t, n in mentions)
    display_name = {}
    for t, n in mentions:
        display_name.setdefault((t, norm_entity(n)), n)

    mapping, audit = {}, []

    for key in counts:
        t, norm = key
        if norm in MANUAL_ALIASES:
            mapping[key] = MANUAL_ALIASES[norm]
            audit.append({
                "type": t, "left": display_name[key],
                "right": MANUAL_ALIASES[norm],
                "similarity": 1.0, "decision": "MERGE_MANUAL"
            })

    for typ in sorted(ALLOWED_NODE_TYPES):
        keys = [k for k in counts if k[0] == typ and k not in mapping]
        if not keys:
            continue
        names = [display_name[k] for k in keys]
        vecs = get_embedder().encode(
            names, batch_size=128, show_progress_bar=False,
            normalize_embeddings=True
        ).astype("float32")

        index = faiss.IndexFlatIP(vecs.shape[1])
        index.add(vecs)
        sims, nbrs = index.search(vecs, min(top_k, len(names)))
        uf = UF(len(names))

        for i in range(len(names)):
            for score, j in zip(sims[i], nbrs[i]):
                if j < 0 or i >= j or float(score) < threshold:
                    continue
                ok = merge_guard(names[i], names[j])
                audit.append({
                    "type": typ, "left": names[i], "right": names[j],
                    "similarity": float(score),
                    "decision": "MERGE_VECTOR" if ok else "REJECT_GUARD"
                })
                if ok:
                    uf.union(i, j)

        groups = defaultdict(list)
        for i in range(len(names)):
            groups[uf.find(i)].append(i)

        for idxs in groups.values():
            best = sorted(
                idxs,
                key=lambda i: (-counts[keys[i]], len(names[i]), names[i].lower())
            )[0]
            canonical = names[best]
            for i in idxs:
                mapping[keys[i]] = canonical

    for key in counts:
        mapping.setdefault(key, display_name[key])

    return mapping, pd.DataFrame(audit)

def canonicalize_triples(raw_df, mapping):
    df = raw_df.copy()
    def canon(name, typ):
        n = norm_entity(name)
        return mapping.get((typ, n), MANUAL_ALIASES.get(n, name))

    df["source_name"] = [canon(n,t) for n,t in zip(df.source_raw, df.source_type)]
    df["target_name"] = [canon(n,t) for n,t in zip(df.target_raw, df.target_type)]
    df["source_name_norm"] = df.source_name.map(norm_entity)
    df["target_name_norm"] = df.target_name.map(norm_entity)
    df["source_id"] = [sha1(f"{t}:{n}".encode()).hexdigest()[:24] for t,n in zip(df.source_type, df.source_name_norm)]
    df["target_id"] = [sha1(f"{t}:{n}".encode()).hexdigest()[:24] for t,n in zip(df.target_type, df.target_name_norm)]
    return df[df.source_id != df.target_id].reset_index(drop=True)

entity_map, entity_resolution_audit_df = build_resolution_map(raw_triples_df)
triples_df = canonicalize_triples(raw_triples_df, entity_map)
display(entity_resolution_audit_df.head(20))

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 9395.47it/s]

,type,left,right,similarity,decision
0,Company,Fidelity National Information Services,Fidelity National Information Services Inc.,0.924524,MERGE_VECTOR
1,Company,L&T Technology Services Limited,L&T Technology Services,0.925773,MERGE_VECTOR
2,Company,L&T Technology Services Limited,L&T Technology Services Ltd,0.920202,MERGE_VECTOR
3,Company,L&T Technology Services,L&T Technology Services Ltd,0.902919,MERGE_VECTOR
4,Technology,healthcare information technology,healthcare information technology services,0.902359,REJECT_GUARD
5,Technology,X90A,X90,0.920579,REJECT_GUARD

In [11]:
#@title 2.3 — Node table + UNWIND bulk insert
def build_nodes(triples_df):
    rows = []
    for r in triples_df.itertuples(index=False):
        rows += [
            {"id":r.source_id,"name":r.source_name,"name_norm":r.source_name_norm,"type":r.source_type,"alias":r.source_raw},
            {"id":r.target_id,"name":r.target_name,"name_norm":r.target_name_norm,"type":r.target_type,"alias":r.target_raw},
        ]
    tmp = pd.DataFrame(rows)
    if tmp.empty:
        return tmp

    out = []
    for (node_id,name,name_norm,typ), g in tmp.groupby(["id","name","name_norm","type"]):
        aliases = sorted(set(g["alias"].map(norm_space)))
        out.append({
            "id":node_id, "name":name, "name_norm":name_norm, "type":typ,
            "aliases":aliases,
            "aliases_norm":sorted(set(norm_entity(x) for x in aliases))
        })
    return pd.DataFrame(out)

def batches(records, size=1000):
    for i in range(0, len(records), size):
        yield records[i:i+size]

def bulk_insert_nodes(nodes_df, batch_size=1000):
    for typ in sorted(ALLOWED_NODE_TYPES):
        part = nodes_df[nodes_df.type == typ]
        if part.empty:
            continue
        query = f"""
        UNWIND $rows AS row
        MERGE (n:Entity {{id: row.id}})
        SET n:{typ},
            n.name=row.name,
            n.name_norm=row.name_norm,
            n.entity_type=row.type,
            n.aliases=row.aliases,
            n.aliases_norm=row.aliases_norm
        """
        for b in batches(part.to_dict("records"), batch_size):
            run_cypher(query, rows=b)

def bulk_insert_edges(triples_df, batch_size=1000):
    required = {"source_chunk_id","published_date"}
    if not required.issubset(triples_df.columns):
        raise ValueError("Missing edge provenance.")

    for rel in sorted(ALLOWED_RELATIONS):
        part = triples_df[triples_df.relation == rel]
        if part.empty:
            continue

        query = f"""
        UNWIND $rows AS row
        MATCH (s:Entity {{id: row.source_id}})
        MATCH (t:Entity {{id: row.target_id}})
        MERGE (s)-[r:{rel} {{source_chunk_id: row.source_chunk_id}}]->(t)
        SET r.published_date=row.published_date,
            r.evidence=row.evidence,
            r.confidence=row.confidence
        """

        cols = ["source_id","target_id","source_chunk_id","published_date","evidence","confidence"]
        for b in batches(part[cols].to_dict("records"), batch_size):
            run_cypher(query, rows=b)

nodes_df = build_nodes(triples_df)
bulk_insert_nodes(nodes_df)
bulk_insert_edges(triples_df)

In [12]:
#@title 2.4 — Sanity checks
def graph_checks():
    invalid = run_cypher("""
    MATCH ()-[r]->()
    WHERE r.source_chunk_id IS NULL OR r.published_date IS NULL
    RETURN count(r) AS n
    """)[0]["n"]

    counts = {
        "nodes": run_cypher("MATCH (n:Entity) RETURN count(n) AS n")[0]["n"],
        "edges": run_cypher("MATCH ()-[r]->() RETURN count(r) AS n")[0]["n"],
        "invalid_provenance_edges": invalid,
    }
    print(counts)
    assert invalid == 0

    top = pd.DataFrame(run_cypher("""
    MATCH (n:Entity)
    OPTIONAL MATCH (n)-[r]-()
    WITH n, count(r) AS degree
    RETURN n.id AS id, n.name AS name, n.entity_type AS type, degree
    ORDER BY degree DESC LIMIT 15
    """))
    display(top)
    return counts, top

graph_counts, top_degree_df = graph_checks()

{'nodes': 368, 'edges': 237, 'invalid_provenance_edges': 0}

                          id                             name     type  degree
0   af61c9129da522c49e916ec6  L&T Technology Services Limited  Company       7
1   cc9c6ee3857729e221d3f6de                       ServiceNow  Company       5
2   adc0f89fca852dd3fb0443bb                             Citi  Company       4
3   bc18d55f3997314f76b638e5                           Senser  Company       4
4   261a323bf5773a8433c812a6                        DriveNets  Company       4
5   44d14f66663379fb5a148405                         Tim Grey   Person       3
6   d3375cc1a631efa9976e8d53                        Synechron  Company       3
7   6763840dfe2e4e1d3562e71e                 Chris Derbyshire   Person       3
8   8568cefc2b16b1699bc0d89f                            Aqara  Company       3
9   af2cc43aae380d2715acfeff                           Syndio  Company       3
10  33e26345a3f61f0bc587821f       Hyperion Defense Solutions  Company       3
11  68b0f1e1adc856f11ca32dba    Cass Information Systems Inc.  Company       3
12  482e949a0b6c21ca2b8da03e                         Infineon  Company       3
13  f4a26eedddc593a6915d7fa2                             ILUS  Company       3
14  6ffdac611f8523c6b41c1e7e                        Ann Lewis   Person       3

# PHẦN 3 — FLAT RAG & HYBRID GRAPHRAG (45–75')

## Flat RAG baseline
Dùng cùng embedding/generator để comparison tập trung vào retrieval architecture.

In [13]:
#@title 3.1 — Flat RAG
flat_index = None
flat_store = None
entity_match_vectors = None
entity_match_store = None

def build_flat_index(chunks_df):
    global flat_index, flat_store
    vecs = get_embedder().encode(
        chunks_df.text.fillna("").tolist(),
        batch_size=128, show_progress_bar=True,
        normalize_embeddings=True
    ).astype("float32")

    flat_index = faiss.IndexFlatIP(vecs.shape[1])
    flat_index.add(vecs)
    flat_store = chunks_df.reset_index(drop=True).copy()
    print("Flat vectors:", flat_index.ntotal)

def retrieve_flat_context(query, k=6):
    qv = get_embedder().encode(
        [query], normalize_embeddings=True, show_progress_bar=False
    ).astype("float32")
    scores, ids = flat_index.search(qv, min(k, flat_index.ntotal))

    rows = []
    for score, idx in zip(scores[0], ids[0]):
        if idx < 0:
            continue
        r = flat_store.iloc[int(idx)]
        rows.append({
            "score":float(score), "chunk_id":r.chunk_id,
            "published_date":r.published_date, "text":r.text
        })

    df = pd.DataFrame(rows)
    context = "\n\n".join(
        f"[chunk_id={r.chunk_id} | date={r.published_date} | score={r.score:.3f}]\n{r.text}"
        for r in df.itertuples(index=False)
    )
    return context, df

build_flat_index(chunks_df)

Batches:   0%|          | 0/12 [00:00<?, ?it/s]

Batches:   8%|▊         | 1/12 [00:03<00:37,  3.43s/it]

Batches:  17%|█▋        | 2/12 [00:04<00:19,  1.95s/it]

Batches:  25%|██▌       | 3/12 [00:05<00:12,  1.43s/it]

Batches:  33%|███▎      | 4/12 [00:06<00:11,  1.41s/it]

Batches:  42%|████▏     | 5/12 [00:07<00:08,  1.20s/it]

Batches:  50%|█████     | 6/12 [00:08<00:06,  1.05s/it]

Batches:  58%|█████▊    | 7/12 [00:08<00:04,  1.03it/s]

Batches:  67%|██████▋   | 8/12 [00:09<00:03,  1.10it/s]

Batches:  75%|███████▌  | 9/12 [00:10<00:02,  1.17it/s]

Batches:  83%|████████▎ | 10/12 [00:11<00:01,  1.22it/s]

Batches:  92%|█████████▏| 11/12 [00:11<00:00,  1.37it/s]

Batches: 100%|██████████| 12/12 [00:12<00:00,  1.56it/s]

Batches: 100%|██████████| 12/12 [00:12<00:00,  1.01s/it]

Flat vectors: 1500

## Graph retrieval flow
1. LLM trích seed entities.
2. Match seed trong Neo4j; fuzzy fallback bằng embedding.
3. BFS tối đa `max_hops`.
4. Nếu node degree > 100 → chỉ lấy tối đa 50 edge mới nhất.
5. Global edge cap để tránh context explosion.
6. Textualize subgraph có provenance.

In [14]:
#@title 3.2 — Seed matching
SEED_SYSTEM = """
Extract useful seed entities for graph retrieval.
Allowed types: Company, Person, Technology.
Do not answer the question. Return strict JSON only.
""".strip()

def extract_seeds(query):
    obj, _ = groq_json(SEED_SYSTEM, f"""
Question: {query}
Return {{"seeds":[{{"name":"...","type":"Company|Person|Technology|null"}}]}}
""")
    return [
        {"name":norm_space(x.get("name")),
         "type":x.get("type") if x.get("type") in ALLOWED_NODE_TYPES else None}
        for x in obj.get("seeds", [])
        if norm_space(x.get("name"))
    ]

def build_entity_matcher(nodes_df):
    global entity_match_vectors, entity_match_store
    entity_match_store = nodes_df.reset_index(drop=True).copy()
    entity_match_vectors = get_embedder().encode(
        entity_match_store.name.tolist(),
        batch_size=128, show_progress_bar=False,
        normalize_embeddings=True
    ).astype("float32")

def match_seeds(query, fuzzy_threshold=0.66):
    matched = []
    for seed in extract_seeds(query):
        exact = run_cypher("""
        MATCH (n:Entity)
        WHERE (n.name_norm=$name OR $name IN coalesce(n.aliases_norm,[]))
          AND ($typ IS NULL OR n.entity_type=$typ)
        RETURN n.id AS id, n.name AS name, n.entity_type AS type
        LIMIT 5
        """, name=norm_entity(seed["name"]), typ=seed["type"])

        if exact:
            matched += exact
            continue

        if entity_match_vectors is None:
            continue

        mask = np.ones(len(entity_match_store), dtype=bool)
        if seed["type"]:
            mask = entity_match_store.type.eq(seed["type"]).to_numpy()
        idxs = np.flatnonzero(mask)
        if not len(idxs):
            continue

        qv = get_embedder().encode(
            [seed["name"]], normalize_embeddings=True, show_progress_bar=False
        ).astype("float32")[0]
        sims = entity_match_vectors[idxs] @ qv
        j = int(np.argmax(sims))
        if float(sims[j]) >= fuzzy_threshold:
            r = entity_match_store.iloc[int(idxs[j])]
            matched.append({"id":r.id,"name":r.name,"type":r.type})

    return list({x["id"]: x for x in matched}.values())

build_entity_matcher(nodes_df)

In [15]:
#@title 3.3 — Graph traversal + super-node mitigation
SUPER_NODE_DEGREE = 100
SUPER_NODE_EDGE_CAP = 50
GLOBAL_EDGE_CAP = 250
MAX_GRAPH_CONTEXT_CHARS = 14000

def node_degree(node_id):
    return int(run_cypher("""
    MATCH (n:Entity {id:$id})
    OPTIONAL MATCH (n)-[r]-()
    RETURN count(r) AS degree
    """, id=node_id)[0]["degree"])

def recent_edges(node_id, limit):
    return run_cypher("""
    MATCH (n:Entity {id:$id})
    MATCH (n)-[r]-(m:Entity)
    RETURN
      startNode(r).id AS source_id,
      startNode(r).name AS source_name,
      startNode(r).entity_type AS source_type,
      type(r) AS relation,
      endNode(r).id AS target_id,
      endNode(r).name AS target_name,
      endNode(r).entity_type AS target_type,
      r.source_chunk_id AS source_chunk_id,
      r.published_date AS published_date,
      r.evidence AS evidence,
      m.id AS neighbor_id
    ORDER BY coalesce(r.published_date,'') DESC
    LIMIT $limit
    """, id=node_id, limit=int(limit))

def textualize(edges):
    edges = sorted(edges, key=lambda e:e.get("published_date") or "", reverse=True)
    lines, used = [], 0
    for e in edges:
        line = (
            f"{e['source_name']} [{e['source_type']}] -{e['relation']}-> "
            f"{e['target_name']} [{e['target_type']}] "
            f"| date={e.get('published_date') or 'unknown'} "
            f"| chunk={e.get('source_chunk_id') or 'unknown'}"
        )
        if e.get("evidence"):
            line += f" | evidence={norm_space(e['evidence'])}"
        if used + len(line) + 1 > MAX_GRAPH_CONTEXT_CHARS:
            break
        lines.append(line)
        used += len(line) + 1
    return "\n".join(lines)

def retrieve_graph_context(query, max_hops=2, edge_limit=50, return_debug=False):
    seeds = match_seeds(query)
    if not seeds:
        out = {"context":"","edges":pd.DataFrame(),
               "diagnostics":{"reason":"NO_SEED","supernode_events":[]}}
        return out if return_debug else ""

    frontier = deque((x["id"],0) for x in seeds)
    expanded, seen_edges, collected = set(), set(), []
    supernode_events = []

    while frontier and len(collected) < GLOBAL_EDGE_CAP:
        node_id, hop = frontier.popleft()
        if node_id in expanded or hop >= max_hops:
            continue
        expanded.add(node_id)

        degree = node_degree(node_id)
        limit = int(edge_limit)
        if degree > SUPER_NODE_DEGREE:
            limit = min(limit, SUPER_NODE_EDGE_CAP)
            supernode_events.append({"node_id":node_id,"degree":degree,"limit":limit})

        for e in recent_edges(node_id, limit):
            key = (e["source_id"],e["relation"],e["target_id"],e["source_chunk_id"])
            if key in seen_edges:
                continue
            seen_edges.add(key)
            collected.append(e)
            if len(collected) >= GLOBAL_EDGE_CAP:
                break

            nb = e.get("neighbor_id")
            if nb and nb not in expanded and hop + 1 < max_hops:
                frontier.append((nb, hop+1))

    out = {
        "context": textualize(collected),
        "edges": pd.DataFrame(collected),
        "diagnostics": {
            "matched_seeds": seeds,
            "expanded_nodes": len(expanded),
            "collected_edges": len(collected),
            "supernode_events": supernode_events,
        }
    }
    return out if return_debug else out["context"]

In [16]:
#@title 3.4 — Flat answer vs Hybrid GraphRAG answer
ANSWER_SYSTEM = """
Answer only from supplied context.
Be concise but complete. Do not invent facts.
Cite provenance inline as [chunk_id=...] whenever possible.
If evidence is insufficient or conflicting, say so.
""".strip()

def generate_answer(question, context):
    prompt = f"QUESTION:\n{question}\n\nCONTEXT:\n{context}\n\nANSWER:"
    t0 = time.perf_counter()
    text, usage = groq_chat(
        [{"role":"system","content":ANSWER_SYSTEM},
         {"role":"user","content":prompt}],
        model=GROQ_MODEL
    )
    return {
        "answer": text.strip(),
        "latency_s": time.perf_counter()-t0,
        "total_tokens": usage.get("total_tokens"),
    }

def answer_flat_rag(question):
    context, retrieved = retrieve_flat_context(question, k=6)
    out = generate_answer(question, context)
    out.update({"context":context,"retrieved":retrieved})
    return out

def answer_graph_rag(question):
    g = retrieve_graph_context(question, max_hops=2, edge_limit=50, return_debug=True)
    vctx, vdocs = retrieve_flat_context(question, k=4)
    context = f"=== GRAPH ===\n{g['context']}\n\n=== VECTOR ===\n{vctx}"
    out = generate_answer(question, context)
    out.update({"context":context,"graph_debug":g,"vector_docs":vdocs})
    return out

# PHẦN 4 — GOLDEN DATASET & LLM-AS-A-JUDGE (75–105')

## Golden schema
`id`, `group`, `question`, `reference_answer`, optional `reference_evidence`.

Notebook có 5 câu starter. Các câu phụ thuộc data dump phải điền gold answer thật trước final evaluation.

In [17]:
#@title 4.1 — 5 câu Golden starter
GOLDEN_PATH = "/content/golden_dataset.csv"

starter_golden = pd.DataFrame([
    {
        "id":"G01","group":"factoid",
        "question":"Who was the CEO of Hugging Face in 2023?",
        "reference_answer":"Clément Delangue",
        "reference_evidence":"Validate against instructor dump."
    },
    {
        "id":"G02","group":"multi-hop",
        "question":"Which startups were founded by former Microsoft employees and later received investment from Google?",
        "reference_answer":"Placeholder answer",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G03","group":"cross-doc",
        "question":"Compare the direction of AI-related investments by Meta and Apple during 2023 using evidence from multiple articles.",
        "reference_answer":"Placeholder answer",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G04","group":"multi-hop",
        "question":"Find a company invested in by a major technology company that also developed a named AI technology; identify both relations and dates.",
        "reference_answer":"Placeholder answer",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G05","group":"cross-doc",
        "question":"Identify one technology connected to the same company in at least two news chunks and summarize how the relationship changed over time.",
        "reference_answer":"Placeholder answer",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
])

golden_df = pd.read_csv(GOLDEN_PATH) if Path(GOLDEN_PATH).exists() else starter_golden.copy()
display(golden_df)

def validate_golden(df, require_answers=True):
    required = {"id","group","question","reference_answer"}
    if not required.issubset(df.columns):
        raise ValueError(f"Missing columns: {required-set(df.columns)}")
    if require_answers and df.reference_answer.fillna("").str.strip().eq("").any():
        display(df[df.reference_answer.fillna("").str.strip().eq("")][["id","question"]])
        raise ValueError("Điền reference_answer trước final evaluation.")
    print("✅ Golden Dataset valid.")

,id,group,question,reference_answer,reference_evidence
0,G01,factoid,Who was the CEO of Hugging Face in 2023?,Clément Delangue,Validate against instructor dump.
1,G02,multi-hop,Which startups were founded by former Microsoft employees and later received investment from Google?,Placeholder answer,TO_BE_FILLED_FROM_DATASET
2,G03,cross-doc,Compare the direction of AI-related investments by Meta and Apple during 2023 using evidence from multiple articles.,Placeholder answer,TO_BE_FILLED_FROM_DATASET
3,G04,multi-hop,Find a company invested in by a major technology company that also developed a named AI technology; identify both re...,Placeholder answer,TO_BE_FILLED_FROM_DATASET
4,G05,cross-doc,Identify one technology connected to the same company in at least two news chunks and summarize how the relationship...,Placeholder answer,TO_BE_FILLED_FROM_DATASET

In [18]:
#@title 4.2 — LLM-as-a-Judge
JUDGE_SYSTEM = """
You are a strict evaluator of RAG answers.
Score 1-5:
- comprehensiveness
- faithfulness to supplied candidate context
- multi_hop_reasoning accuracy
Use the reference answer as correctness anchor.
Return strict JSON only.
""".strip()

def judge_json(system, user):
    if not JUDGE_MODEL:
        raise RuntimeError("Thiếu JUDGE_MODEL.")

    if JUDGE_PROVIDER == "groq":
        return groq_json(system, user, model=JUDGE_MODEL)[0]

    if JUDGE_PROVIDER == "openai":
        if not OPENAI_API_KEY:
            raise RuntimeError("Thiếu OPENAI_API_KEY.")
        from openai import OpenAI
        client = OpenAI(api_key=OPENAI_API_KEY)
        resp = client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[{"role":"system","content":system},
                      {"role":"user","content":user}],
            temperature=0.0,
            response_format={"type":"json_object"}
        )
        return parse_json_object(resp.choices[0].message.content)

    raise ValueError("JUDGE_PROVIDER must be openai or groq.")

def judge_answer(question, reference, answer, context):
    prompt = f"""
QUESTION:
{question}

REFERENCE:
{reference}

CANDIDATE:
{answer}

CANDIDATE CONTEXT:
{context[:18000]}

Return:
{{
 "comprehensiveness":1,
 "faithfulness":1,
 "multi_hop_reasoning":1,
 "rationale":"2-5 sentences"
}}
"""
    obj = judge_json(JUDGE_SYSTEM, prompt)
    out = {}
    for k in ["comprehensiveness","faithfulness","multi_hop_reasoning"]:
        out[k] = max(1, min(5, int(obj.get(k,1))))
    out["rationale"] = norm_space(obj.get("rationale"))
    return out

In [19]:
#@title 4.3 — Evaluation runner + checkpoint
CHECKPOINT = "/content/graphrag_eval_checkpoint.csv"

def run_evaluation(golden_df):
    rows = []
    for q in tqdm(golden_df.itertuples(index=False), total=len(golden_df), desc="Evaluation"):
        flat = answer_flat_rag(q.question)
        graph = answer_graph_rag(q.question)

        jf = judge_answer(q.question, q.reference_answer, flat["answer"], flat["context"])
        jg = judge_answer(q.question, q.reference_answer, graph["answer"], graph["context"])

        rows.append({
            "id":q.id, "group":q.group, "question":q.question,
            "reference_answer":q.reference_answer,
            "flat_answer":flat["answer"], "graph_answer":graph["answer"],
            "flat_comprehensiveness":jf["comprehensiveness"],
            "graph_comprehensiveness":jg["comprehensiveness"],
            "flat_faithfulness":jf["faithfulness"],
            "graph_faithfulness":jg["faithfulness"],
            "flat_multi_hop_reasoning":jf["multi_hop_reasoning"],
            "graph_multi_hop_reasoning":jg["multi_hop_reasoning"],
            "flat_latency_s":flat["latency_s"],
            "graph_latency_s":graph["latency_s"],
            "flat_total_tokens":flat.get("total_tokens"),
            "graph_total_tokens":graph.get("total_tokens"),
            "flat_judge_rationale":jf["rationale"],
            "graph_judge_rationale":jg["rationale"],
            "graph_supernode_events":len(
                graph["graph_debug"]["diagnostics"].get("supernode_events",[])
            )
        })
        pd.DataFrame(rows).to_csv(CHECKPOINT, index=False)
    return pd.DataFrame(rows)

validate_golden(golden_df, require_answers=False)
eval_results_df = run_evaluation(golden_df)
display(eval_results_df)

✅ Golden Dataset valid.

Evaluation:   0%|          | 0/5 [00:00<?, ?it/s]

Evaluation:  20%|██        | 1/5 [00:11<00:47, 11.92s/it]

Evaluation:  40%|████      | 2/5 [00:23<00:34, 11.54s/it]

Evaluation:  60%|██████    | 3/5 [00:37<00:25, 12.78s/it]

Evaluation:  80%|████████  | 4/5 [00:49<00:12, 12.54s/it]

Evaluation: 100%|██████████| 5/5 [01:01<00:00, 12.30s/it]

Evaluation: 100%|██████████| 5/5 [01:01<00:00, 12.30s/it]

,id,group,question,reference_answer,flat_answer,graph_answer,flat_comprehensiveness,graph_comprehensiveness,flat_faithfulness,graph_faithfulness,flat_multi_hop_reasoning,graph_multi_hop_reasoning,flat_latency_s,graph_latency_s,flat_total_tokens,graph_total_tokens,flat_judge_rationale,graph_judge_rationale,graph_supernode_events
0,G01,factoid,Who was the CEO of Hugging Face in 2023?,Clément Delangue,"The context provided does not contain information about the CEO of Hugging Face in 2023. Therefore, I cannot answer ...","The context provided does not contain information about the CEO of Hugging Face in 2023. Therefore, I cannot answer ...",1,1,1,1,1,1,1.274115,1.183862,568,426,"The candidate answer does not provide any information about the CEO of Hugging Face in 2023, which is the specific q...","The candidate answer does not provide any information about the CEO of Hugging Face in 2023, which is the main quest...",0
1,G02,multi-hop,Which startups were founded by former Microsoft employees and later received investment from Google?,Placeholder answer,The provided context does not contain specific information about startups founded by former Microsoft employees that...,The provided context does not contain any information about startups founded by former Microsoft employees that late...,1,1,1,1,1,1,1.124437,1.341014,528,585,The candidate answer correctly identifies that the provided context does not contain relevant information to answer ...,The candidate answer correctly identifies that the provided context does not contain any relevant information regard...,0
2,G03,cross-doc,Compare the direction of AI-related investments by Meta and Apple during 2023 using evidence from multiple articles.,Placeholder answer,"In 2023, Meta and Apple have taken distinct approaches to AI-related investments. \n\nMeta has been actively expandi...","In 2023, Meta and Apple exhibited different approaches to AI-related investments.\n\nMeta has been actively focusing...",2,3,3,4,2,3,2.437578,2.563428,691,839,"The candidate provides a basic comparison of Meta's AI investments but lacks sufficient detail on Apple's direction,...","The candidate provides a basic comparison of Meta and Apple's AI investments, highlighting their different focuses. ...",0
3,G04,multi-hop,Find a company invested in by a major technology company that also developed a named AI technology; identify both re...,Placeholder answer,"One example is the startup Cohere, which developed AI technology for building conversational customer-service agents...",A company invested in by a major technology company that developed a named AI technology is OpenAI. OpenAI is partne...,3,2,4,3,3,2,1.276992,1.331419,555,719,The candidate identifies Cohere as a startup that developed AI technology for conversational customer-service agents...,The candidate identifies OpenAI as a company invested in by a major technology company (Microsoft) and mentions its ...,0
4,G05,cross-doc,Identify one technology connected to the same company in at least two news chunks and summarize how the relationship...,Placeholder answer,"One technology connected to Thomson Reuters Corp, as indicated in the news chunks, is information services. Initiall...","One technology connected to Amazon Web Services (AWS) is its cloud computing services. Initially, AWS was developed ...",3,3,4,4,3,3,2.157188,2.056904,606,693,"The candidate provides a summary of the relationship between Thomson Reuters and information services, noting the in...",The candidate provides a summary of AWS's evolution from a collaborative development phase to a leading provider of ...,0

In [20]:
#@title 4.4 — Comparison table + export
def comparison_table(eval_df):
    metric_map = {
        "Comprehensiveness":("flat_comprehensiveness","graph_comprehensiveness"),
        "Faithfulness":("flat_faithfulness","graph_faithfulness"),
        "Multi-hop reasoning":("flat_multi_hop_reasoning","graph_multi_hop_reasoning"),
        "Latency (s)":("flat_latency_s","graph_latency_s"),
        "Token usage":("flat_total_tokens","graph_total_tokens"),
    }

    rows = []
    for group, g in eval_df.groupby("group"):
        for metric, (fc,gc) in metric_map.items():
            f = pd.to_numeric(g[fc], errors="coerce").mean()
            gr = pd.to_numeric(g[gc], errors="coerce").mean()

            if metric in {"Latency (s)","Token usage"}:
                comment = "Flat RAG thường rẻ/nhanh hơn." if f < gr else "GraphRAG không đắt hơn trong sample này."
            else:
                delta = gr - f
                if delta >= .75:
                    comment = "GraphRAG cải thiện rõ; kiểm tra rationale và provenance."
                elif delta <= -.5:
                    comment = "Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu."
                else:
                    comment = "Hai phương pháp gần nhau."

            rows.append({
                "Loại câu hỏi":group, "Metric":metric,
                "Flat RAG":round(f,3) if pd.notna(f) else np.nan,
                "GraphRAG":round(gr,3) if pd.notna(gr) else np.nan,
                "Nhận xét phân tích":comment
            })
    return pd.DataFrame(rows)

comparison_df = comparison_table(eval_results_df)
display(comparison_df)
eval_results_df.to_csv("/content/graphrag_eval_results.csv", index=False)
comparison_df.to_csv("/content/graphrag_vs_flatrag_summary.csv", index=False)

,Loại câu hỏi,Metric,Flat RAG,GraphRAG,Nhận xét phân tích
0,cross-doc,Comprehensiveness,2.500,3.000,Hai phương pháp gần nhau.
1,cross-doc,Faithfulness,3.500,4.000,Hai phương pháp gần nhau.
2,cross-doc,Multi-hop reasoning,2.500,3.000,Hai phương pháp gần nhau.
3,cross-doc,Latency (s),2.297,2.310,Flat RAG thường rẻ/nhanh hơn.
4,cross-doc,Token usage,648.500,766.000,Flat RAG thường rẻ/nhanh hơn.
5,factoid,Comprehensiveness,1.000,1.000,Hai phương pháp gần nhau.
6,factoid,Faithfulness,1.000,1.000,Hai phương pháp gần nhau.
7,factoid,Multi-hop reasoning,1.000,1.000,Hai phương pháp gần nhau.
8,factoid,Latency (s),1.274,1.184,GraphRAG không đắt hơn trong sample này.
9,factoid,Token usage,568.000,426.000,GraphRAG không đắt hơn trong sample này.
10,multi-hop,Comprehensiveness,2.000,1.500,Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu.
11,multi-hop,Faithfulness,2.500,2.000,Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu.
12,multi-hop,Multi-hop reasoning,2.000,1.500,Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu.
13,multi-hop,Latency (s),1.201,1.336,Flat RAG thường rẻ/nhanh hơn.
14,multi-hop,Token usage,541.500,652.000,Flat RAG thường rẻ/nhanh hơn.

# PHẦN 5 — FAILURE-MODE CHECKS & SUBMISSION (105–120')

Bắt buộc chứng minh:
1. Edge provenance không thiếu.
2. Entity Resolution có audit.
3. Super-node degree > 100 chỉ expand tối đa 50 edge.
4. Có comparison table.

In [21]:
#@title 5.1 — Super-node check + entity audit
def test_supernode_policy():
    rows = run_cypher("""
    MATCH (n:Entity)-[r]-()
    WITH n, count(r) AS degree
    ORDER BY degree DESC LIMIT 1
    RETURN n.id AS id, n.name AS name, degree
    """)
    if not rows:
        print("Graph empty.")
        return

    n = rows[0]
    limit = 50 if n["degree"] > SUPER_NODE_DEGREE else 1000
    edges = recent_edges(n["id"], limit)
    print(n, "fetched=", len(edges))
    if n["degree"] > SUPER_NODE_DEGREE:
        assert len(edges) <= 50
        print("✅ Super-node cap OK.")

def show_resolution_audit(audit_df):
    if audit_df.empty:
        print("No audit rows.")
        return
    display(
        audit_df.sort_values("similarity", ascending=False).head(30)
    )
    print("High-similarity rejected pairs:")
    display(
        audit_df[audit_df.decision=="REJECT_GUARD"]
        .sort_values("similarity", ascending=False)
        .head(20)
    )

test_supernode_policy()
show_resolution_audit(entity_resolution_audit_df)

{'id': 'af61c9129da522c49e916ec6', 'name': 'L&T Technology Services Limited', 'degree': 7} fetched= 7

,type,left,right,similarity,decision
1,Company,L&T Technology Services Limited,L&T Technology Services,0.925773,MERGE_VECTOR
0,Company,Fidelity National Information Services,Fidelity National Information Services Inc.,0.924524,MERGE_VECTOR
5,Technology,X90A,X90,0.920579,REJECT_GUARD
2,Company,L&T Technology Services Limited,L&T Technology Services Ltd,0.920202,MERGE_VECTOR
3,Company,L&T Technology Services,L&T Technology Services Ltd,0.902919,MERGE_VECTOR
4,Technology,healthcare information technology,healthcare information technology services,0.902359,REJECT_GUARD

High-similarity rejected pairs:

,type,left,right,similarity,decision
5,Technology,X90A,X90,0.920579,REJECT_GUARD
4,Technology,healthcare information technology,healthcare information technology services,0.902359,REJECT_GUARD

## 5.2 — Thuyết minh kỹ thuật: học viên tự điền

1. Coreference sai ở tình huống nào?
2. Entity threshold bao nhiêu, vì sao?
3. Candidate nào similarity cao nhưng không nên merge?
4. Top 3 super-node và degree?
5. Vì sao ưu tiên edge mới nhất có thể đúng/sai?
6. Flat RAG thắng nhóm nào?
7. GraphRAG thắng nhóm nào?
8. Latency/token trade-off?
9. AI Coding Agent đề xuất gì mà bạn **không dùng**, vì sao?
10. Scale 350MB: bottleneck đầu tiên là gì?

# 🎁 BONUS

## A — Low-level / High-level
Tạo local entities và high-level topics/community reports; query router chọn tầng retrieval.

## B — Global Search via Community Reports
Nếu Neo4j instance không có GDS phù hợp, fallback:
1. export edges,
2. NetworkX community detection,
3. `UNWIND` write `community_id`,
4. LLM summarize community,
5. query global trên reports.

## C — Self-Correction Graph Retrieval
- hop 2 → LLM kiểm tra context đủ chưa,
- thiếu → hop 3,
- vẫn thiếu → vector fallback,
- bắt buộc stop condition.

In [22]:
#@title Bonus — NetworkX community fallback
import networkx as nx

def build_communities(limit_edges=20000):
    edge_df = pd.DataFrame(run_cypher("""
    MATCH (a:Entity)-[r]->(b:Entity)
    RETURN a.id AS source, b.id AS target
    LIMIT $limit
    """, limit=int(limit_edges)))

    G = nx.Graph()
    G.add_edges_from(edge_df[["source","target"]].itertuples(index=False, name=None))
    communities = nx.algorithms.community.greedy_modularity_communities(G)

    rows = []
    for cid, members in enumerate(communities):
        rows += [{"id":node_id,"community_id":int(cid)} for node_id in members]

    for b in batches(rows, 1000):
        run_cypher("""
        UNWIND $rows AS row
        MATCH (n:Entity {id:row.id})
        SET n.community_id=row.community_id
        """, rows=b)

    return pd.DataFrame(rows)

community_df = build_communities()

In [23]:
#@title Bonus — Self-correction scaffold
SUFFICIENCY_SYSTEM = """
Decide whether the supplied retrieval context is sufficient to answer the question faithfully.
Do not answer the question. Return strict JSON only.
""".strip()

def context_sufficient(question, context):
    obj, _ = groq_json(
        SUFFICIENCY_SYSTEM,
        f"""QUESTION: {question}
CONTEXT:
{context[:16000]}
Return {{"sufficient":true,"missing":"..."}}"""
    )
    return bool(obj.get("sufficient")), norm_space(obj.get("missing"))

def self_correcting_context(question):
    g2 = retrieve_graph_context(question, 2, 50, True)
    ok, missing = context_sufficient(question, g2["context"])
    if ok:
        return {"route":"hop2","context":g2["context"],"missing":""}

    g3 = retrieve_graph_context(question, 3, 50, True)
    ok, missing2 = context_sufficient(question, g3["context"])
    if ok:
        return {"route":"hop3","context":g3["context"],"missing":missing}

    flat, _ = retrieve_flat_context(question, k=8)
    return {
        "route":"hop3+vector",
        "context":f"=== GRAPH ===\n{g3['context']}\n\n=== VECTOR ===\n{flat}",
        "missing":missing2
    }

# ✅ RUBRIC

- **30% Chạy được code:** graph nạp thành công, schema đúng, xuất bảng.
- **30% Failure modes:** xử lý ít nhất 2/3 vấn đề Super-node, Entity Resolution, Coreference.
- **20% Evaluation:** chạy hết Golden Dataset, phân tích hợp lý.
- **20% Thuyết minh:** giải thích kiến trúc và cách kiểm soát AI Coding Agent.

## Submission checklist
- [ ] Neo4j connected
- [ ] Dedup/chunking đã chạy
- [ ] Coreference spot-check
- [ ] Entity resolution audit
- [ ] `UNWIND` bulk insert
- [ ] 0 edge thiếu provenance
- [ ] Flat RAG chạy
- [ ] GraphRAG chạy
- [ ] Super-node check
- [ ] Golden Dataset có gold answers thật
- [ ] Evaluation chạy hết
- [ ] Export results + summary CSV
- [ ] Thuyết minh kỹ thuật
- [ ] Bonus (nếu có) có định lượng trước/sau