# 🚀 LAB GUIDE — PRODUCTION-GRADE GRAPHRAG VS FLAT RAG

**Thời lượng:** 120 phút  
**Môi trường:** Google Colab (T4 GPU khuyến nghị) + Neo4j AuraDB  
**Dữ liệu:** HackerNoon Tech Company News Data Dump (bản thu gọn do giảng viên cung cấp)  
**Công cụ:** Học viên được dùng AI Coding Agent, nhưng phải tự thiết kế, kiểm thử và giải thích logic.

## 🎯 Mục tiêu
1. Xây dựng Hybrid GraphRAG end-to-end.
2. Xử lý Coreference Resolution, Entity Resolution và Super-node Mitigation.
3. Bulk insert bằng `UNWIND`, không insert từng row.
4. So sánh Flat RAG và GraphRAG bằng Golden Dataset + LLM-as-a-Judge.
5. Đo quality, latency và token usage.
6. Giải thích kiến trúc và failure modes.

> Notebook là **reference lab guide**: có code khung chạy được nhưng vẫn yêu cầu học viên thay prompt/threshold/retrieval policy và thuyết minh lựa chọn.

## ⏳ Timeline

| Phút | Nội dung |
|---|---|
| 00–15 | Setup, load, dedup, chunk, coreference |
| 15–45 | NER/RE, entity resolution, Neo4j bulk insert |
| 45–75 | Flat RAG, graph traversal, hybrid retrieval |
| 75–105 | Golden Dataset, LLM-as-a-Judge, comparison |
| 105–120 | Failure-mode tests, bonus, export, thuyết minh |

### Scale guard
Trong lab 2 giờ, không nên gửi toàn bộ 350MB qua LLM. Mặc định dùng subset:
- `LAB_MAX_ARTICLES = 1500`
- `LAB_MAX_CHUNKS = 3000`
- `EXTRACTION_MAX_CHUNKS = 400`

Kiến trúc phải scale được; volume trong giờ lab chỉ dùng để chứng minh pipeline.

# PHẦN 1 — SETUP & PREPROCESSING

### Secrets trên Colab
Tạo:
- `NEO4J_URI`, `NEO4J_USER`, `NEO4J_PASSWORD`
- `GROQ_API_KEY`, `GROQ_MODEL`
- `HF_TOKEN` để stream dataset từ Hugging Face
- cho judge: `JUDGE_PROVIDER`, `JUDGE_MODEL`, và `OPENAI_API_KEY` nếu dùng OpenAI

Không hard-code API key vào notebook nộp bài.

In [1]:
#@title 1.1 — Install
%pip -q install neo4j pandas numpy pyarrow sentence-transformers faiss-cpu groq openai tqdm networkx spacy datasets langchain-community llama-index

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\NapoleDong\Documents\Vinuni\LABS\Day19-2A202601851-LeVanDong\.venv\Scripts\python.exe -m pip install --upgrade pip

In [2]:
#@title 1.2 — Imports & config
import os, re, json, time, random, hashlib, unicodedata
from pathlib import Path
from collections import defaultdict, Counter, deque
from difflib import SequenceMatcher

import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from neo4j import GraphDatabase
from sentence_transformers import SentenceTransformer
import faiss

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
pd.set_option("display.max_colwidth", 120)

def get_secret(name, default=None):
    try:
        from google.colab import userdata
        value = userdata.get(name)
        if value is not None:
            return value
    except Exception:
        pass
    return os.environ.get(name, default)

NEO4J_URI = get_secret("NEO4J_URI", "")
NEO4J_USER = get_secret("NEO4J_USER", "neo4j")
NEO4J_PASSWORD = get_secret("NEO4J_PASSWORD", "")
NEO4J_DATABASE = get_secret("NEO4J_DATABASE", "neo4j")

GROQ_API_KEY = get_secret("GROQ_API_KEY", "")
GROQ_MODEL = get_secret("GROQ_MODEL", "")

JUDGE_PROVIDER = get_secret("JUDGE_PROVIDER", "openai").lower()
JUDGE_MODEL = get_secret("JUDGE_MODEL", "")
OPENAI_API_KEY = get_secret("OPENAI_API_KEY", "")
HF_TOKEN = get_secret("HF_TOKEN", "")

DATA_PATH = "hackernoon_subset.csv"
LAB_MAX_ARTICLES = 1500
LAB_MAX_CHUNKS = 3000
EXTRACTION_MAX_CHUNKS = 400
CHUNK_WORDS = 220
CHUNK_OVERLAP_WORDS = 40

C:\Users\NapoleDong\Documents\Vinuni\LABS\Day19-2A202601851-LeVanDong\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## 1.3 — Download HackerNoon Dataset bằng Hugging Face Streaming

Cell dưới đây stream trực tiếp dataset **`HackerNoon/tech-company-news-data-dump`** và ghi dần ra CSV, nên không cần tải toàn bộ dataset vào RAM.

### Hai cơ chế giới hạn

- `LIMIT_ROWS`: số dòng tối đa.
- `LIMIT_MB`: dung lượng file tối đa.
- `PRIORITIZE_MB = True`: ưu tiên dừng theo dung lượng MB.
- `PRIORITIZE_MB = False`: thanh tiến trình theo số dòng, nhưng **vẫn giữ hard-stop `LIMIT_ROWS`**.

### Lưu ý

- Đặt `HF_TOKEN` trong **Colab Secrets**, không hard-code token vào notebook.
- Nếu dataset yêu cầu quyền truy cập/gated access, hãy mở trang dataset trên Hugging Face và hoàn tất bước **Agree/Request access** trước.
- Sau khi cell hoàn tất, `DATA_PATH` mặc định đã trỏ tới `/content/hackernoon_subset.csv`, nên cell loader kế tiếp có thể chạy trực tiếp.

In [3]:
#@title 1.3 — Stream HackerNoon dataset -> CSV
import csv
import os
from datasets import load_dataset
from tqdm.auto import tqdm

DATASET_NAME = "HackerNoon/tech-company-news-data-dump"
OUTPUT_CSV = "hackernoon_subset.csv"

# Giới hạn cho bản lab. Có thể tăng sau buổi học.
LIMIT_ROWS = 5000
LIMIT_MB = 300

# True  -> progress/dừng ưu tiên theo MB
# False -> progress theo rows; vẫn có hard-stop LIMIT_ROWS
PRIORITIZE_MB = True

# Đọc từ Colab Secrets qua get_secret() ở cell config.
if not HF_TOKEN:
    raise ValueError(
        "Thiếu HF_TOKEN. Hãy thêm Hugging Face Access Token vào Colab Secrets với tên HF_TOKEN."
    )

print("Đang kết nối luồng dữ liệu (streaming)...")

try:
    dataset = load_dataset(
        DATASET_NAME,
        split="train",
        streaming=True,
        token=HF_TOKEN,
    )
    iterator = iter(dataset)

    first_row = next(iterator)
    headers = list(first_row.keys())

    print(f"Đang ghi dữ liệu vào: {OUTPUT_CSV}")

    rows_written = 0
    total_progress = LIMIT_MB if PRIORITIZE_MB else LIMIT_ROWS
    unit_progress = "MB" if PRIORITIZE_MB else "row"

    with open(OUTPUT_CSV, mode="w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers, extrasaction="ignore")
        writer.writeheader()
        writer.writerow(first_row)
        rows_written += 1

        # Flush để kích thước file phản ánh dữ liệu vừa ghi.
        f.flush()
        file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)

        with tqdm(
            total=total_progress,
            desc=f"Đang tải ({unit_progress})",
            unit=unit_progress,
        ) as pbar:
            if PRIORITIZE_MB:
                pbar.n = min(file_size_mb, LIMIT_MB)
                pbar.refresh()
            else:
                pbar.update(1)

            for row in iterator:
                writer.writerow(row)
                rows_written += 1

                # Kiểm tra dung lượng định kỳ để giảm overhead I/O.
                # Khi gần LIMIT_MB, kiểm tra mỗi row để dừng sát ngưỡng hơn.
                should_check_size = (
                    PRIORITIZE_MB
                    and (
                        rows_written % 100 == 0
                        or file_size_mb >= LIMIT_MB * 0.95
                    )
                )

                if should_check_size:
                    f.flush()
                    file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
                    pbar.n = min(round(file_size_mb, 2), LIMIT_MB)
                    pbar.refresh()
                elif not PRIORITIZE_MB:
                    pbar.update(1)

                # Hard-stop theo MB nếu đang ưu tiên dung lượng.
                if PRIORITIZE_MB and file_size_mb >= LIMIT_MB:
                    print(
                        f"\n[DỪNG] Đã đạt giới hạn dung lượng: "
                        f"{file_size_mb:.2f} MB "
                        f"(Tổng: {rows_written:,} dòng)"
                    )
                    break

                # Hard-stop theo số dòng trong mọi chế độ.
                if rows_written >= LIMIT_ROWS:
                    f.flush()
                    file_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
                    print(
                        f"\n[DỪNG] Đã đạt giới hạn số dòng: "
                        f"{rows_written:,} dòng "
                        f"(Dung lượng: {file_size_mb:.2f} MB)"
                    )
                    break

        f.flush()

    final_size_mb = os.path.getsize(OUTPUT_CSV) / (1024 * 1024)
    print(
        f"✅ Hoàn thành: {os.path.abspath(OUTPUT_CSV)}\n"
        f"   Rows: {rows_written:,}\n"
        f"   Size: {final_size_mb:.2f} MB"
    )

    # Đồng bộ đường dẫn cho cell loader tiếp theo.
    DATA_PATH = OUTPUT_CSV

except StopIteration:
    raise RuntimeError("Dataset stream rỗng: không lấy được dòng đầu tiên.")
except Exception as e:
    print(f"\n❌ Có lỗi xảy ra: {e}")
    print(
        "Kiểm tra: (1) HF_TOKEN, (2) quyền Agree/Access trên Hugging Face, "
        "(3) kết nối mạng của Colab."
    )
    raise

Đang kết nối luồng dữ liệu (streaming)...

Đang ghi dữ liệu vào: hackernoon_subset.csv

Đang tải (MB):   0%|          | 0/300 [00:00<?, ?MB/s]

Đang tải (MB):   0%|          | 0.0006494522094726562/300 [00:00<00:07, 42.56MB/s]

Đang tải (MB):   0%|          | 0.06/300 [00:00<00:11, 26.20MB/s]

Đang tải (MB):   0%|          | 0.12/300 [00:00<00:10, 27.97MB/s]

Đang tải (MB):   0%|          | 0.18/300 [00:00<00:10, 29.02MB/s]

Đang tải (MB):   0%|          | 0.24/300 [00:00<00:10, 29.30MB/s]

Đang tải (MB):   0%|          | 0.3/300 [00:00<00:09, 30.55MB/s]

Đang tải (MB):   0%|          | 0.35/300 [00:00<00:10, 29.83MB/s]

Đang tải (MB):   0%|          | 0.41/300 [00:00<00:09, 29.99MB/s]

Đang tải (MB):   0%|          | 0.47/300 [00:00<00:09, 30.28MB/s]

Đang tải (MB):   0%|          | 0.53/300 [00:00<00:10, 29.74MB/s]

Đang tải (MB):   0%|          | 0.59/300 [00:00<00:10, 29.90MB/s]

Đang tải (MB):   0%|          | 0.65/300 [00:00<00:09, 29.95MB/s]

Đang tải (MB):   0%|          | 0.71/300 [00:00<00:09, 30.00MB/s]

Đang tải (MB):   0%|          | 0.77/300 [00:00<00:09, 30.40MB/s]

Đang tải (MB):   0%|          | 0.83/300 [00:00<00:09, 30.33MB/s]

Đang tải (MB):   0%|          | 0.89/300 [00:00<00:09, 30.41MB/s]

Đang tải (MB):   0%|          | 0.95/300 [00:00<00:09, 30.31MB/s]

Đang tải (MB):   0%|          | 1.01/300 [00:00<00:09, 30.26MB/s]

Đang tải (MB):   0%|          | 1.07/300 [00:00<00:09, 29.97MB/s]

Đang tải (MB):   0%|          | 1.13/300 [00:00<00:10, 29.81MB/s]

Đang tải (MB):   0%|          | 1.19/300 [00:00<00:10, 29.62MB/s]

Đang tải (MB):   0%|          | 1.24/300 [00:00<00:10, 29.26MB/s]

Đang tải (MB):   0%|          | 1.3/300 [00:00<00:10, 29.35MB/s]

Đang tải (MB):   0%|          | 1.36/300 [00:00<00:10, 29.43MB/s]

Đang tải (MB):   0%|          | 1.42/300 [00:00<00:10, 29.37MB/s]

Đang tải (MB):   0%|          | 1.47/300 [00:00<00:10, 29.17MB/s]

Đang tải (MB):   1%|          | 1.53/300 [00:00<00:10, 29.00MB/s]

Đang tải (MB):   1%|          | 1.59/300 [00:00<00:10, 28.84MB/s]

Đang tải (MB):   1%|          | 1.64/300 [00:00<00:10, 28.75MB/s]

Đang tải (MB):   1%|          | 1.7/300 [00:00<00:10, 28.71MB/s]

Đang tải (MB):   1%|          | 1.76/300 [00:00<00:10, 28.73MB/s]

Đang tải (MB):   1%|          | 1.82/300 [00:00<00:10, 28.68MB/s]

Đang tải (MB):   1%|          | 1.87/300 [00:00<00:10, 28.48MB/s]

Đang tải (MB):   1%|          | 1.93/300 [00:00<00:10, 28.48MB/s]

Đang tải (MB):   1%|          | 1.99/300 [00:00<00:10, 28.39MB/s]

Đang tải (MB):   1%|          | 2.05/300 [00:00<00:10, 28.41MB/s]

Đang tải (MB):   1%|          | 2.1/300 [00:00<00:10, 28.37MB/s]

Đang tải (MB):   1%|          | 2.16/300 [00:00<00:10, 28.38MB/s]

Đang tải (MB):   1%|          | 2.22/300 [00:00<00:10, 28.27MB/s]

Đang tải (MB):   1%|          | 2.28/300 [00:00<00:10, 28.26MB/s]

Đang tải (MB):   1%|          | 2.34/300 [00:00<00:10, 28.24MB/s]

Đang tải (MB):   1%|          | 2.4/300 [00:00<00:10, 28.24MB/s]

Đang tải (MB):   1%|          | 2.46/300 [00:00<00:10, 28.12MB/s]

Đang tải (MB):   1%|          | 2.52/300 [00:00<00:10, 28.05MB/s]

Đang tải (MB):   1%|          | 2.58/300 [00:00<00:10, 28.09MB/s]

Đang tải (MB):   1%|          | 2.63/300 [00:00<00:10, 27.89MB/s]

Đang tải (MB):   1%|          | 2.69/300 [00:00<00:10, 27.86MB/s]

Đang tải (MB):   1%|          | 2.75/300 [00:00<00:10, 27.86MB/s]

Đang tải (MB):   1%|          | 2.81/300 [00:00<00:10, 27.83MB/s]

Đang tải (MB):   1%|          | 2.87/300 [00:00<00:10, 27.84MB/s]

Đang tải (MB):   1%|          | 2.92/300 [00:00<00:10, 27.74MB/s]

Đang tải (MB):   1%|          | 2.92/300 [00:00<00:10, 27.56MB/s]

[DỪNG] Đã đạt giới hạn số dòng: 5,000 dòng (Dung lượng: 2.92 MB)
✅ Hoàn thành: C:\Users\NapoleDong\Documents\Vinuni\LABS\Day19-2A202601851-LeVanDong\hackernoon_subset.csv
   Rows: 5,000
   Size: 2.92 MB

In [4]:
#@title 1.4 — Neo4j connection + schema
driver = None

def connect_neo4j():
    global driver
    if not NEO4J_URI or not NEO4J_PASSWORD:
        raise ValueError("Thiếu Neo4j secrets.")
    driver = GraphDatabase.driver(
        NEO4J_URI,
        auth=(NEO4J_USER, NEO4J_PASSWORD),
    )
    driver.verify_connectivity()
    print("✅ Neo4j connected.")

def run_cypher(query, **params):
    if driver is None:
        raise RuntimeError("Hãy chạy connect_neo4j() trước.")
    with driver.session(database=NEO4J_DATABASE) as session:
        result = session.run(query, **params)
        rows = [r.data() for r in result]
        result.consume()
    return rows

def setup_graph_schema():
    for stmt in [
        """
        CREATE CONSTRAINT entity_id IF NOT EXISTS
        FOR (n:Entity) REQUIRE n.id IS UNIQUE
        """,
        """
        CREATE INDEX entity_name_norm IF NOT EXISTS
        FOR (n:Entity) ON (n.name_norm)
        """,
        """
        CREATE INDEX company_name_norm IF NOT EXISTS
        FOR (n:Company) ON (n.name_norm)
        """,
        """
        CREATE INDEX person_name_norm IF NOT EXISTS
        FOR (n:Person) ON (n.name_norm)
        """,
        """
        CREATE INDEX technology_name_norm IF NOT EXISTS
        FOR (n:Technology) ON (n.name_norm)
        """,
    ]:
        run_cypher(stmt)
    print("✅ Schema ready.")

connect_neo4j()
setup_graph_schema()

✅ Neo4j connected.

✅ Schema ready.

In [5]:
#@title 1.5 — Loader + exact dedup + chunking
def norm_space(x):
    return re.sub(r"\s+", " ", str(x or "")).strip()

def sha1(x):
    return hashlib.sha1(str(x).encode("utf-8", errors="ignore")).hexdigest()

def pick_col(df, candidates, required=True):
    lookup = {str(c).lower(): c for c in df.columns}
    for c in candidates:
        if c.lower() in lookup:
            return lookup[c.lower()]
    if required:
        raise KeyError(f"Missing one of columns: {candidates}")
    return None

def load_news(path):
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(path)
    if path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    if path.suffix.lower() in {".jsonl", ".ndjson"}:
        return pd.read_json(path, lines=True)
    if path.suffix.lower() == ".json":
        return pd.read_json(path)
    if path.suffix.lower() in {".parquet", ".pq"}:
        return pd.read_parquet(path)
    raise ValueError(f"Unsupported: {path.suffix}")

def standardize_news(raw):
    text_col = pick_col(raw, ["text", "content", "article", "body", "story", "description"])
    title_col = pick_col(raw, ["title", "headline"], required=False)
    date_col = pick_col(raw, ["published_date", "date", "published_at", "created_at"], required=False)
    id_col = pick_col(raw, ["id", "article_id", "story_id", "uuid"], required=False)

    df = pd.DataFrame()
    df["text"] = raw[text_col].fillna("").map(norm_space)
    df["title"] = raw[title_col].fillna("").map(norm_space) if title_col else ""

    if date_col:
        df["published_date"] = (
            pd.to_datetime(raw[date_col], errors="coerce", utc=True)
            .dt.strftime("%Y-%m-%d")
            .fillna("")
        )
    else:
        df["published_date"] = ""

    if id_col:
        df["article_id"] = raw[id_col].astype(str)
    else:
        df["article_id"] = [
            sha1(f"{t}\n{x}")[:20] for t, x in zip(df["title"], df["text"])
        ]

    df = df[df["text"].str.len() >= 80].copy()
    df["dedup_key"] = [
        sha1(norm_space(f"{t}\n{x}").lower())
        for t, x in zip(df["title"], df["text"])
    ]
    before = len(df)
    df = df.drop_duplicates("dedup_key").drop(columns="dedup_key").reset_index(drop=True)
    print(f"Exact dedup: {before:,} -> {len(df):,}")

    # --- Challenge A: Near Dedup (AnnoyAnn / FAISS) ---
    print("Running Near Dedup with faiss for Challenge A...")
    embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
    texts_to_embed = df["title"].fillna("") + " " + df["text"].fillna("")
    vecs = embedder.encode(texts_to_embed.tolist(), batch_size=128, show_progress_bar=False, normalize_embeddings=True).astype("float32")
    
    index = faiss.IndexFlatIP(vecs.shape[1])
    index.add(vecs)
    sims, nbrs = index.search(vecs, 2)
    to_drop = set()
    for i in range(len(df)):
        if i in to_drop:
            continue
        j = nbrs[i][1]
        score = sims[i][1]
        if j != -1 and j != i and score >= 0.95:
            to_drop.add(j)
            
    df = df.drop(index=list(to_drop)).reset_index(drop=True)
    print(f"Near dedup: dropped {len(to_drop)} near-duplicates. -> {len(df):,}")
    # --- End Challenge A ---

    if LAB_MAX_ARTICLES and len(df) > LAB_MAX_ARTICLES:
        df = df.sample(LAB_MAX_ARTICLES, random_state=SEED).sort_index().reset_index(drop=True)
    return df

def chunk_text(text, size=220, overlap=40):
    words = norm_space(text).split()
    step = max(1, size - overlap)
    out = []
    for start in range(0, len(words), step):
        part = words[start:start+size]
        if not part:
            break
        out.append(" ".join(part))
        if start + size >= len(words):
            break
    return out

def build_chunks(news_df):
    rows = []
    for r in tqdm(news_df.itertuples(index=False), total=len(news_df), desc="Chunking"):
        for i, text in enumerate(chunk_text(r.text, CHUNK_WORDS, CHUNK_OVERLAP_WORDS)):
            rows.append({
                "chunk_id": f"{r.article_id}::c{i:04d}",
                "article_id": r.article_id,
                "title": r.title,
                "published_date": r.published_date,
                "text": text,
            })
            if LAB_MAX_CHUNKS and len(rows) >= LAB_MAX_CHUNKS:
                return pd.DataFrame(rows)
    return pd.DataFrame(rows)

raw_df = load_news(DATA_PATH)
news_df = standardize_news(raw_df)
chunks_df = build_chunks(news_df)
display(chunks_df.head())

Exact dedup: 2,675 -> 2,105
Running Near Dedup with faiss for Challenge A...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 3175.40it/s]

Near dedup: dropped 32 near-duplicates. -> 2,073

Chunking:   0%|          | 0/1500 [00:00<?, ?it/s]

Chunking: 100%|██████████| 1500/1500 [00:00<00:00, 30437.47it/s]

,chunk_id,article_id,title,published_date,text
0,1a05beb7aa3071be6fd7::c0000,1a05beb7aa3071be6fd7,onsemi and Sineng Electric Spearhead the Development of Sustainable Energy Applications,2023-05-16,(Nasdaq: ON) a leader in intelligent power and sensing technologies today announced that Sineng Electric will integr...
1,8e922bc62b578e73e815::c0000,8e922bc62b578e73e815,Modernizing State Services: Harnessing Technology for Enhanced Public Service Delivery,2023-05-01,To deliver 21st-century government services Governors and cabinet members need leaders with technology expertise to ...
2,4bd7afdba71243b0dbcd::c0000,4bd7afdba71243b0dbcd,Terry Richardson On Why He Left AMD GreenPages’ Technology Chops And The AI Opportunity,2023-05-02,In February GreenPages acquired Toronto-based Zanaris an IT automation cloud and DevOps services firm ... Steve Burk...
3,6633c15d86f5e81f47b8::c0000,6633c15d86f5e81f47b8,5 Kubernetes technology vendors hot right now,2023-02-28,Kubernetes is a technology that has created a whole new ecosystem around itself and it is now a key plank in the Dev...
4,4ce72a4490a6a618e2d5::c0000,4ce72a4490a6a618e2d5,Bachelor of Science in Health Information Management,2023-08-16,Health information management (HIM) is a diverse yet evolving field that incorporates medicine management finance in...

### 🎯 AI Coding Agent Challenge A — Near Dedup
Exact hash không bắt được bài repost/near-duplicate.

Hãy dùng AI Agent thiết kế thêm **MinHash/LSH, SimHash hoặc embedding+ANN**.  
**Không chấp nhận** pairwise cosine `O(N²)` trên toàn dataset.

Trong báo cáo nêu:
1. threshold,
2. false positive,
3. cách audit cặp bị merge.

In [6]:
#@title 1.6 - LLM wrapper (Patched to use OpenAI for speed)
import openai, time, random, json
def parse_json_object(text):
    import re
    text = str(text).strip()
    text = re.sub(r'^```(?:json)?\s*', '', text, flags=re.I)
    text = re.sub(r'\s*```$', '', text)
    a, b = text.find('{'), text.rfind('}')
    if a < 0 or b <= a:
        raise ValueError('No JSON object found.')
    return json.loads(text[a:b+1])

def groq_chat(messages, model=None, json_mode=False, max_retries=4):
    client = openai.OpenAI(api_key=OPENAI_API_KEY)
    model = model or 'gpt-4o-mini'
    last = None
    for attempt in range(max_retries):
        try:
            kwargs = {'model': model, 'messages': messages, 'temperature': 0.0}
            if json_mode:
                kwargs['response_format'] = {'type': 'json_object'}
            resp = client.chat.completions.create(**kwargs)
            usage = {}
            if getattr(resp, 'usage', None):
                usage = {'total_tokens': getattr(resp.usage, 'total_tokens', None)}
            return resp.choices[0].message.content, usage
        except Exception as e:
            last = e
            print(f'OpenAI API error: {e}, retrying...')
            if attempt == max_retries - 1: break
            time.sleep(min(20, 2**attempt + random.random()))
    raise RuntimeError(last)

def groq_json(system, user, model=None):
    text, usage = groq_chat([{'role': 'system', 'content': system}, {'role': 'user', 'content': user}], model=model, json_mode=True)
    return parse_json_object(text), usage

## 1.7 — Coreference Resolution

Yêu cầu:
- chỉ resolve đại từ khi antecedent rõ trong cùng chunk,
- không invent fact,
- giữ nguyên số/ngày/ticker/product,
- ambiguity → giữ nguyên và log `unresolved_mentions`.

**Failure mode quan trọng:** false coreference → false edge.

In [7]:
#@title 1.7 — Coreference resolution theo batch
COREF_SYSTEM = """
You are a conservative coreference-resolution component for a knowledge-graph pipeline.
Resolve pronouns and generic references only when the antecedent is clearly supported in the same chunk.
Never invent facts. Preserve dates, numbers, tickers and product names.
Return strict JSON only.
""".strip()

def resolve_coref_batch(batch_df):
    payload = [{"chunk_id": r.chunk_id, "text": r.text}
               for r in batch_df.itertuples(index=False)]

    prompt = f"""
Resolve coreferences.

Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "resolved_text": "...",
      "unresolved_mentions": ["..."]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()

    obj, usage = groq_json(COREF_SYSTEM, prompt)
    by_id = {x.get("chunk_id"): x for x in obj.get("items", [])}

    rows = []
    for r in batch_df.itertuples(index=False):
        item = by_id.get(r.chunk_id, {})
        rows.append({
            "chunk_id": r.chunk_id,
            "resolved_text": norm_space(item.get("resolved_text") or r.text),
            "unresolved_mentions": item.get("unresolved_mentions", []),
        })
    return pd.DataFrame(rows), usage

def run_coref(chunks_subset, batch_size=5):
    out = []
    for start in tqdm(range(0, len(chunks_subset), batch_size), desc="Coref"):
        batch = chunks_subset.iloc[start:start+batch_size]
        try:
            df, _ = resolve_coref_batch(batch)
        except Exception:
            df = pd.DataFrame({
                "chunk_id": batch["chunk_id"].tolist(),
                "resolved_text": batch["text"].tolist(),
                "unresolved_mentions": [["COREF_BATCH_FAILED"] for _ in range(len(batch))],
            })
        out.append(df)
    return pd.concat(out, ignore_index=True)

extraction_source = chunks_df.head(EXTRACTION_MAX_CHUNKS).copy()
coref_df = run_coref(extraction_source)
extraction_source = extraction_source.merge(coref_df, on="chunk_id", how="left")

Coref:   0%|          | 0/80 [00:00<?, ?it/s]

Coref:   1%|▏         | 1/80 [00:08<10:46,  8.19s/it]

Coref:   2%|▎         | 2/80 [00:12<07:53,  6.07s/it]

Coref:   4%|▍         | 3/80 [00:18<07:42,  6.01s/it]

Coref:   5%|▌         | 4/80 [00:25<08:05,  6.39s/it]

Coref:   6%|▋         | 5/80 [00:31<07:37,  6.10s/it]

Coref:   8%|▊         | 6/80 [00:36<07:21,  5.97s/it]

Coref:   9%|▉         | 7/80 [00:42<07:15,  5.97s/it]

Coref:  10%|█         | 8/80 [00:50<07:51,  6.54s/it]

Coref:  11%|█▏        | 9/80 [00:55<06:58,  5.90s/it]

Coref:  12%|█▎        | 10/80 [01:01<07:05,  6.08s/it]

Coref:  14%|█▍        | 11/80 [01:09<07:25,  6.46s/it]

Coref:  15%|█▌        | 12/80 [01:13<06:44,  5.95s/it]

Coref:  16%|█▋        | 13/80 [01:18<06:10,  5.53s/it]

Coref:  18%|█▊        | 14/80 [01:22<05:45,  5.24s/it]

Coref:  19%|█▉        | 15/80 [01:26<05:13,  4.82s/it]

Coref:  20%|██        | 16/80 [01:31<05:01,  4.70s/it]

Coref:  21%|██▏       | 17/80 [01:35<04:51,  4.62s/it]

Coref:  22%|██▎       | 18/80 [01:41<05:10,  5.00s/it]

Coref:  24%|██▍       | 19/80 [01:47<05:31,  5.43s/it]

Coref:  25%|██▌       | 20/80 [01:52<05:02,  5.04s/it]

Coref:  26%|██▋       | 21/80 [02:01<06:16,  6.38s/it]

Coref:  28%|██▊       | 22/80 [02:06<05:44,  5.95s/it]

Coref:  29%|██▉       | 23/80 [02:14<06:12,  6.53s/it]

Coref:  30%|███       | 24/80 [02:20<06:02,  6.48s/it]

Coref:  31%|███▏      | 25/80 [02:26<05:40,  6.18s/it]

Coref:  32%|███▎      | 26/80 [02:33<05:46,  6.41s/it]

Coref:  34%|███▍      | 27/80 [02:38<05:14,  5.93s/it]

Coref:  35%|███▌      | 28/80 [02:42<04:37,  5.34s/it]

Coref:  36%|███▋      | 29/80 [02:47<04:34,  5.38s/it]

Coref:  38%|███▊      | 30/80 [02:53<04:33,  5.48s/it]

Coref:  39%|███▉      | 31/80 [02:59<04:36,  5.64s/it]

Coref:  40%|████      | 32/80 [03:09<05:34,  6.98s/it]

Coref:  41%|████▏     | 33/80 [03:17<05:51,  7.48s/it]

Coref:  42%|████▎     | 34/80 [03:23<05:19,  6.94s/it]

Coref:  44%|████▍     | 35/80 [03:28<04:49,  6.42s/it]

Coref:  45%|████▌     | 36/80 [03:33<04:12,  5.75s/it]

Coref:  46%|████▋     | 37/80 [03:37<03:49,  5.34s/it]

Coref:  48%|████▊     | 38/80 [03:42<03:36,  5.15s/it]

Coref:  49%|████▉     | 39/80 [03:52<04:38,  6.78s/it]

Coref:  50%|█████     | 40/80 [04:13<07:20, 11.02s/it]

Coref:  51%|█████▏    | 41/80 [04:20<06:19,  9.73s/it]

Coref:  52%|█████▎    | 42/80 [04:27<05:41,  9.00s/it]

Coref:  54%|█████▍    | 43/80 [04:34<05:09,  8.37s/it]

Coref:  55%|█████▌    | 44/80 [04:39<04:24,  7.34s/it]

Coref:  56%|█████▋    | 45/80 [04:46<04:10,  7.17s/it]

Coref:  57%|█████▊    | 46/80 [04:52<03:49,  6.76s/it]

Coref:  59%|█████▉    | 47/80 [04:56<03:25,  6.21s/it]

Coref:  60%|██████    | 48/80 [05:01<03:03,  5.73s/it]

Coref:  61%|██████▏   | 49/80 [05:11<03:33,  6.89s/it]

Coref:  62%|██████▎   | 50/80 [05:15<03:06,  6.23s/it]

Coref:  64%|██████▍   | 51/80 [05:20<02:48,  5.82s/it]

Coref:  65%|██████▌   | 52/80 [05:25<02:33,  5.49s/it]

Coref:  66%|██████▋   | 53/80 [05:30<02:25,  5.38s/it]

Coref:  68%|██████▊   | 54/80 [05:35<02:15,  5.23s/it]

Coref:  69%|██████▉   | 55/80 [05:40<02:09,  5.17s/it]

Coref:  70%|███████   | 56/80 [05:49<02:28,  6.18s/it]

Coref:  71%|███████▏  | 57/80 [05:53<02:09,  5.62s/it]

Coref:  72%|███████▎  | 58/80 [05:58<02:03,  5.61s/it]

Coref:  74%|███████▍  | 59/80 [06:04<01:54,  5.46s/it]

Coref:  75%|███████▌  | 60/80 [06:08<01:42,  5.13s/it]

Coref:  76%|███████▋  | 61/80 [06:18<02:03,  6.50s/it]

Coref:  78%|███████▊  | 62/80 [06:23<01:49,  6.07s/it]

Coref:  79%|███████▉  | 63/80 [06:28<01:39,  5.86s/it]

Coref:  80%|████████  | 64/80 [06:33<01:29,  5.58s/it]

Coref:  81%|████████▏ | 65/80 [06:39<01:24,  5.63s/it]

Coref:  82%|████████▎ | 66/80 [06:43<01:14,  5.32s/it]

Coref:  84%|████████▍ | 67/80 [06:51<01:18,  6.05s/it]

Coref:  85%|████████▌ | 68/80 [06:57<01:11,  5.93s/it]

Coref:  86%|████████▋ | 69/80 [07:01<00:59,  5.45s/it]

Coref:  88%|████████▊ | 70/80 [07:07<00:56,  5.65s/it]

Coref:  89%|████████▉ | 71/80 [07:12<00:48,  5.34s/it]

Coref:  90%|█████████ | 72/80 [07:21<00:52,  6.51s/it]

Coref:  91%|█████████▏| 73/80 [07:25<00:40,  5.85s/it]

Coref:  92%|█████████▎| 74/80 [07:31<00:34,  5.75s/it]

Coref:  94%|█████████▍| 75/80 [07:40<00:33,  6.69s/it]

Coref:  95%|█████████▌| 76/80 [07:46<00:26,  6.61s/it]

Coref:  96%|█████████▋| 77/80 [08:00<00:26,  8.82s/it]

Coref:  98%|█████████▊| 78/80 [08:07<00:16,  8.12s/it]

Coref:  99%|█████████▉| 79/80 [08:14<00:07,  7.92s/it]

Coref: 100%|██████████| 80/80 [08:20<00:00,  7.40s/it]

Coref: 100%|██████████| 80/80 [08:20<00:00,  6.26s/it]

# PHẦN 2 — TRIPLE EXTRACTION & NEO4J BULK INSERT (15–45')

## Graph schema
**Nodes:** `Company`, `Person`, `Technology` + base label `Entity`.

**Relations:** `ACQUIRED`, `DEVELOPED`, `INVESTED_IN`, `FOUNDED`, `WORKED_AT`, `PARTNERED_WITH`, `USES`, `LEADS`.

**Mỗi edge bắt buộc:** `source_chunk_id`, `published_date`; khuyến nghị thêm `evidence`, `confidence`.

> Relation type phải qua allowlist trước khi ghép vào Cypher.

In [8]:
#@title 2.1 — NER + RE extraction
ALLOWED_NODE_TYPES = {"Company", "Person", "Technology"}
ALLOWED_RELATIONS = {
    "ACQUIRED", "DEVELOPED", "INVESTED_IN", "FOUNDED",
    "WORKED_AT", "PARTNERED_WITH", "USES", "LEADS"
}

EXTRACT_SYSTEM = f"""
Extract a high-precision knowledge graph from tech-news text.
Allowed node types: {sorted(ALLOWED_NODE_TYPES)}
Allowed relations: {sorted(ALLOWED_RELATIONS)}
Use only explicitly supported facts. Prefer precision over recall.
Every relation needs short evidence. Return strict JSON only.
""".strip()

def extract_batch(batch_df):
    payload = [{
        "chunk_id": r.chunk_id,
        "published_date": r.published_date,
        "text": getattr(r, "resolved_text", None) or r.text,
    } for r in batch_df.itertuples(index=False)]

    prompt = f"""
Return:
{{
  "items": [
    {{
      "chunk_id": "...",
      "relations": [
        {{
          "source": "...",
          "source_type": "Company|Person|Technology",
          "relation": "ALLOWED_RELATION",
          "target": "...",
          "target_type": "Company|Person|Technology",
          "evidence": "...",
          "confidence": 0.0
        }}
      ]
    }}
  ]
}}

INPUT:
{json.dumps(payload, ensure_ascii=False)}
""".strip()
    return groq_json(EXTRACT_SYSTEM, prompt)

def run_extraction(source_df, batch_size=4):
    meta = source_df.set_index("chunk_id")["published_date"].to_dict()
    triples, errors = [], []

    for start in tqdm(range(0, len(source_df), batch_size), desc="NER+RE"):
        batch = source_df.iloc[start:start+batch_size]
        try:
            obj, _ = extract_batch(batch)
        except Exception as e:
            errors.append({"start": start, "error": str(e)})
            continue

        for item in obj.get("items", []):
            cid = item.get("chunk_id")
            if cid not in meta:
                continue
            for x in item.get("relations", []):
                s, t = norm_space(x.get("source")), norm_space(x.get("target"))
                st, tt, rel = x.get("source_type"), x.get("target_type"), x.get("relation")
                if not s or not t:
                    continue
                if st not in ALLOWED_NODE_TYPES or tt not in ALLOWED_NODE_TYPES:
                    continue
                if rel not in ALLOWED_RELATIONS:
                    continue
                triples.append({
                    "source_raw": s,
                    "source_type": st,
                    "relation": rel,
                    "target_raw": t,
                    "target_type": tt,
                    "source_chunk_id": cid,
                    "published_date": meta[cid] or "",
                    "evidence": norm_space(x.get("evidence")),
                    "confidence": float(x.get("confidence") or 0.0),
                })

    return pd.DataFrame(triples), pd.DataFrame(errors)

raw_triples_df, extraction_errors_df = run_extraction(extraction_source)
display(raw_triples_df.head())

NER+RE:   0%|          | 0/100 [00:00<?, ?it/s]

NER+RE:   1%|          | 1/100 [00:05<09:37,  5.84s/it]

NER+RE:   2%|▏         | 2/100 [00:06<04:37,  2.83s/it]

NER+RE:   3%|▎         | 3/100 [00:11<06:05,  3.77s/it]

NER+RE:   4%|▍         | 4/100 [00:12<04:05,  2.55s/it]

NER+RE:   5%|▌         | 5/100 [00:17<05:22,  3.39s/it]

NER+RE:   6%|▌         | 6/100 [00:24<07:14,  4.62s/it]

NER+RE:   7%|▋         | 7/100 [00:30<08:00,  5.17s/it]

NER+RE:   8%|▊         | 8/100 [00:37<08:52,  5.78s/it]

NER+RE:   9%|▉         | 9/100 [00:41<08:02,  5.30s/it]

NER+RE:  10%|█         | 10/100 [00:42<05:49,  3.89s/it]

NER+RE:  11%|█         | 11/100 [00:55<09:52,  6.65s/it]

NER+RE:  12%|█▏        | 12/100 [00:57<07:54,  5.39s/it]

NER+RE:  13%|█▎        | 13/100 [00:58<05:44,  3.96s/it]

NER+RE:  14%|█▍        | 14/100 [00:59<04:15,  2.97s/it]

NER+RE:  15%|█▌        | 15/100 [01:03<04:41,  3.32s/it]

NER+RE:  16%|█▌        | 16/100 [01:06<04:26,  3.18s/it]

NER+RE:  17%|█▋        | 17/100 [01:08<04:01,  2.91s/it]

NER+RE:  18%|█▊        | 18/100 [01:16<05:55,  4.34s/it]

NER+RE:  19%|█▉        | 19/100 [01:23<06:58,  5.16s/it]

NER+RE:  20%|██        | 20/100 [01:25<05:40,  4.25s/it]

NER+RE:  21%|██        | 21/100 [01:30<05:46,  4.39s/it]

NER+RE:  22%|██▏       | 22/100 [01:34<05:42,  4.39s/it]

NER+RE:  23%|██▎       | 23/100 [01:38<05:36,  4.37s/it]

NER+RE:  24%|██▍       | 24/100 [01:44<06:14,  4.93s/it]

NER+RE:  25%|██▌       | 25/100 [01:47<05:07,  4.10s/it]

NER+RE:  26%|██▌       | 26/100 [01:51<05:08,  4.17s/it]

NER+RE:  27%|██▋       | 27/100 [01:54<04:41,  3.86s/it]

NER+RE:  28%|██▊       | 28/100 [02:00<05:20,  4.45s/it]

NER+RE:  29%|██▉       | 29/100 [02:06<05:44,  4.85s/it]

NER+RE:  30%|███       | 30/100 [02:10<05:21,  4.59s/it]

NER+RE:  31%|███       | 31/100 [02:14<05:15,  4.58s/it]

NER+RE:  32%|███▏      | 32/100 [02:15<03:56,  3.47s/it]

NER+RE:  33%|███▎      | 33/100 [02:16<03:00,  2.69s/it]

NER+RE:  34%|███▍      | 34/100 [02:19<03:09,  2.87s/it]

NER+RE:  35%|███▌      | 35/100 [02:20<02:26,  2.25s/it]

NER+RE:  36%|███▌      | 36/100 [02:24<02:59,  2.80s/it]

NER+RE:  37%|███▋      | 37/100 [02:28<03:12,  3.06s/it]

NER+RE:  38%|███▊      | 38/100 [02:29<02:27,  2.39s/it]

NER+RE:  39%|███▉      | 39/100 [02:32<02:41,  2.65s/it]

NER+RE:  40%|████      | 40/100 [02:35<02:40,  2.68s/it]

NER+RE:  41%|████      | 41/100 [02:39<03:09,  3.22s/it]

NER+RE:  42%|████▏     | 42/100 [02:40<02:24,  2.49s/it]

NER+RE:  43%|████▎     | 43/100 [02:41<01:54,  2.01s/it]

NER+RE:  44%|████▍     | 44/100 [02:42<01:32,  1.65s/it]

NER+RE:  45%|████▌     | 45/100 [02:44<01:46,  1.93s/it]

NER+RE:  46%|████▌     | 46/100 [02:46<01:49,  2.02s/it]

NER+RE:  47%|████▋     | 47/100 [02:51<02:27,  2.79s/it]

NER+RE:  48%|████▊     | 48/100 [02:52<01:54,  2.20s/it]

NER+RE:  49%|████▉     | 49/100 [02:53<01:32,  1.80s/it]

NER+RE:  50%|█████     | 50/100 [02:54<01:16,  1.54s/it]

NER+RE:  51%|█████     | 51/100 [02:58<01:52,  2.29s/it]

NER+RE:  52%|█████▏    | 52/100 [03:01<02:06,  2.64s/it]

NER+RE:  53%|█████▎    | 53/100 [03:02<01:40,  2.13s/it]

NER+RE:  54%|█████▍    | 54/100 [03:06<02:03,  2.69s/it]

NER+RE:  55%|█████▌    | 55/100 [03:11<02:37,  3.49s/it]

NER+RE:  56%|█████▌    | 56/100 [03:19<03:22,  4.60s/it]

NER+RE:  57%|█████▋    | 57/100 [03:19<02:27,  3.44s/it]

NER+RE:  58%|█████▊    | 58/100 [03:23<02:25,  3.45s/it]

NER+RE:  59%|█████▉    | 59/100 [03:32<03:27,  5.07s/it]

NER+RE:  60%|██████    | 60/100 [03:36<03:12,  4.82s/it]

NER+RE:  61%|██████    | 61/100 [03:37<02:22,  3.65s/it]

NER+RE:  62%|██████▏   | 62/100 [03:41<02:25,  3.84s/it]

NER+RE:  63%|██████▎   | 63/100 [03:46<02:34,  4.16s/it]

NER+RE:  64%|██████▍   | 64/100 [03:52<02:50,  4.73s/it]

NER+RE:  65%|██████▌   | 65/100 [03:53<02:05,  3.59s/it]

NER+RE:  66%|██████▌   | 66/100 [03:55<01:49,  3.23s/it]

NER+RE:  67%|██████▋   | 67/100 [04:00<01:56,  3.55s/it]

NER+RE:  68%|██████▊   | 68/100 [04:04<01:59,  3.74s/it]

NER+RE:  69%|██████▉   | 69/100 [04:10<02:19,  4.51s/it]

NER+RE:  70%|███████   | 70/100 [04:11<01:42,  3.41s/it]

NER+RE:  71%|███████   | 71/100 [04:13<01:21,  2.82s/it]

NER+RE:  72%|███████▏  | 72/100 [04:14<01:04,  2.29s/it]

NER+RE:  73%|███████▎  | 73/100 [04:17<01:10,  2.60s/it]

NER+RE:  74%|███████▍  | 74/100 [04:24<01:43,  3.99s/it]

NER+RE:  75%|███████▌  | 75/100 [04:27<01:31,  3.67s/it]

NER+RE:  76%|███████▌  | 76/100 [04:30<01:23,  3.49s/it]

NER+RE:  77%|███████▋  | 77/100 [04:38<01:49,  4.74s/it]

NER+RE:  78%|███████▊  | 78/100 [04:46<02:07,  5.78s/it]

NER+RE:  79%|███████▉  | 79/100 [04:52<02:01,  5.79s/it]

NER+RE:  80%|████████  | 80/100 [04:55<01:37,  4.89s/it]

NER+RE:  81%|████████  | 81/100 [05:02<01:44,  5.52s/it]

NER+RE:  82%|████████▏ | 82/100 [05:07<01:37,  5.44s/it]

NER+RE:  83%|████████▎ | 83/100 [05:12<01:32,  5.45s/it]

NER+RE:  84%|████████▍ | 84/100 [05:15<01:13,  4.57s/it]

NER+RE:  85%|████████▌ | 85/100 [05:17<00:57,  3.86s/it]

NER+RE:  86%|████████▌ | 86/100 [05:18<00:42,  3.01s/it]

NER+RE:  87%|████████▋ | 87/100 [05:19<00:31,  2.41s/it]

NER+RE:  88%|████████▊ | 88/100 [05:21<00:28,  2.41s/it]

NER+RE:  89%|████████▉ | 89/100 [05:22<00:21,  1.96s/it]

NER+RE:  90%|█████████ | 90/100 [05:25<00:22,  2.26s/it]

NER+RE:  91%|█████████ | 91/100 [05:27<00:20,  2.22s/it]

NER+RE:  92%|█████████▏| 92/100 [05:37<00:35,  4.46s/it]

NER+RE:  93%|█████████▎| 93/100 [05:47<00:42,  6.05s/it]

NER+RE:  94%|█████████▍| 94/100 [05:56<00:41,  6.92s/it]

NER+RE:  95%|█████████▌| 95/100 [06:02<00:33,  6.71s/it]

NER+RE:  96%|█████████▌| 96/100 [06:04<00:21,  5.33s/it]

NER+RE:  97%|█████████▋| 97/100 [06:14<00:19,  6.64s/it]

NER+RE:  98%|█████████▊| 98/100 [06:23<00:14,  7.24s/it]

NER+RE:  99%|█████████▉| 99/100 [06:23<00:05,  5.27s/it]

NER+RE: 100%|██████████| 100/100 [06:28<00:00,  5.21s/it]

NER+RE: 100%|██████████| 100/100 [06:28<00:00,  3.89s/it]

,source_raw,source_type,relation,target_raw,target_type,source_chunk_id,published_date,evidence,confidence
0,GreenPages,Company,ACQUIRED,Zanaris,Company,4bd7afdba71243b0dbcd::c0000,2023-05-02,"GreenPages acquired Toronto-based Zanaris, an IT automation cloud and DevOps services firm",1.0
1,Sineng Electric,Company,PARTNERED_WITH,onsemi,Company,1a05beb7aa3071be6fd7::c0000,2023-05-16,Sineng Electric will integrate onsemi EliteSiC silic,1.0
2,Kubernetes,Technology,DEVELOPED,DevOps movement,Technology,6633c15d86f5e81f47b8::c0000,2023-02-28,Kubernetes is now a key plank in the DevOps movement,1.0
3,Aeris Communications,Company,PARTNERED_WITH,Ericsson,Company,4f1346392056a403277d::c0000,2022-12-07,Aeris Communications and Ericsson are joining together,1.0
4,Stewart Information Services Corporation,Company,WORKED_AT,property and casualty insurance industry,Technology,e6f458adb39e8a23889e::c0000,2023-08-14,Stewart Information Services Corporation is in the property and casualty insurance industry.,1.0

## 2.2 — Entity Resolution bằng Vector Similarity

Pipeline:
1. Manual aliases cho ticker/tên rất phổ biến.
2. Embedding ANN candidate.
3. Lexical guard để giảm false merge.
4. Xuất audit table.

### 🎯 AI Coding Agent Challenge B
Cải tiến guard cho:
- ticker,
- suffix `Inc./Corp./Ltd.`,
- product chứa company name,
- người trùng họ/tên gần giống.

In [9]:
display(extraction_errors_df)

Empty DataFrame
Columns: []
Index: []

In [10]:
#@title 2.2 â‌— Entity resolution
import unicodedata, re
from collections import Counter, defaultdict
from difflib import SequenceMatcher
from sentence_transformers import SentenceTransformer
import faiss
import pandas as pd
from hashlib import sha1

CORP_SUFFIXES = {"inc","incorporated","corp","corporation","ltd","limited","llc","plc","co","company", "group", "holdings", "technologies", "tech"}
MANUAL_ALIASES = {
    "msft": "Microsoft", "microsoft corp": "Microsoft", "microsoft corporation": "Microsoft",
    "goog": "Google", "googl": "Google", "google llc": "Google", "alphabet": "Google", "alphabet inc": "Google",
    "meta platforms": "Meta", "meta platforms inc": "Meta", "fb": "Meta", "facebook": "Meta",
    "aapl": "Apple", "apple inc": "Apple",
    "amzn": "Amazon", "amazon.com": "Amazon", "amazon com inc": "Amazon",
    "tsla": "Tesla", "tesla inc": "Tesla",
    "nvda": "Nvidia", "nvidia corp": "Nvidia",
    "nflx": "Netflix", "netflix inc": "Netflix"
}

def norm_entity(name):
    s = unicodedata.normalize("NFKC", str(name)).lower()
    s = re.sub(r'%[^\w\s\-\.]', " ", s)
    return re.sub(r'\s+', " ", s).strip()

def strip_suffix(name):
    toks = norm_entity(name).replace(".", "").split()
    while toks and toks[-1] in CORP_SUFFIXES:
        toks.pop()
    return " ".join(toks)


def merge_guard(a, b):
    na, nb = strip_suffix(a), strip_suffix(b)
    if na == nb:
        return True
        
    wa, wb = na.split(), nb.split()
    
    # 1. Ticker guard: if one is a short ticker (<=4 chars without spaces) 
    # and the other is also short but different, or if it's not a known alias, reject.
    if (len(na) <= 4 and " " not in na) or (len(nb) <= 4 and " " not in nb):
        if na != nb:
            return False
            
    # 2. Product guard / subset guard: e.g. "apple" vs "apple vision pro"
    if set(wa).issubset(set(wb)) and len(wa) < len(wb):
        return False
    if set(wb).issubset(set(wa)) and len(wb) < len(wa):
        return False
        
    # 3. Person name guard: e.g. "john smith" vs "jane smith"
    if len(wa) == len(wb) and len(wa) > 1:
        # If they share the same length of words, but have a completely different word (e.g. first name mismatch)
        diff_count = sum(1 for x, y in zip(wa, wb) if x != y)
        if diff_count > 0:
            return False
            
    # Fallback lexical similarity
    return SequenceMatcher(None, na, nb).ratio() >= 0.72

EMBED_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
embedder = None

def get_embedder():
    global embedder
    if embedder is None:
        embedder = SentenceTransformer(EMBED_MODEL)
    return embedder

class UF:
    def __init__(self, n):
        self.p = list(range(n))
    def find(self, x):
        if self.p[x] != x:
            self.p[x] = self.find(self.p[x])
        return self.p[x]
    def union(self, a, b):
        a, b = self.find(a), self.find(b)
        if a != b:
            self.p[b] = a

def build_resolution_map(raw_triples_df, threshold=0.90, top_k=5):
    mentions = []
    for r in raw_triples_df.itertuples(index=False):
        mentions += [(r.source_type, r.source_raw), (r.target_type, r.target_raw)]

    counts = Counter((t, norm_entity(n)) for t, n in mentions)
    display_name = {}
    for t, n in mentions:
        display_name.setdefault((t, norm_entity(n)), n)

    mapping, audit = {}, []

    for key in counts:
        t, norm = key
        if norm in MANUAL_ALIASES:
            mapping[key] = MANUAL_ALIASES[norm]
            audit.append({
                "type": t, "left": display_name[key],
                "right": MANUAL_ALIASES[norm],
                "similarity": 1.0, "decision": "MERGE_MANUAL"
            })

    for typ in sorted(ALLOWED_NODE_TYPES):
        keys = [k for k in counts if k[0] == typ and k not in mapping]
        if not keys:
            continue
        names = [display_name[k] for k in keys]
        vecs = get_embedder().encode(
            names, batch_size=128, show_progress_bar=False,
            normalize_embeddings=True
        ).astype("float32")

        index = faiss.IndexFlatIP(vecs.shape[1])
        index.add(vecs)
        sims, nbrs = index.search(vecs, min(top_k, len(names)))
        uf = UF(len(names))

        for i in range(len(names)):
            for score, j in zip(sims[i], nbrs[i]):
                if j < 0 or i >= j or float(score) < threshold:
                    continue
                ok = merge_guard(names[i], names[j])
                audit.append({
                    "type": typ, "left": names[i], "right": names[j],
                    "similarity": float(score),
                    "decision": "MERGE_VECTOR" if ok else "REJECT_GUARD"
                })
                if ok:
                    uf.union(i, j)

        groups = defaultdict(list)
        for i in range(len(names)):
            groups[uf.find(i)].append(i)

        for idxs in groups.values():
            best = sorted(
                idxs,
                key=lambda i: (-counts[keys[i]], len(names[i]), names[i].lower())
            )[0]
            canonical = names[best]
            for i in idxs:
                mapping[keys[i]] = canonical

    for key in counts:
        mapping.setdefault(key, display_name[key])

    return mapping, pd.DataFrame(audit)

def canonicalize_triples(raw_df, mapping):
    df = raw_df.copy()
    def canon(name, typ):
        n = norm_entity(name)
        return mapping.get((typ, n), MANUAL_ALIASES.get(n, name))

    df["source_name"] = [canon(n,t) for n,t in zip(df.source_raw, df.source_type)]
    df["target_name"] = [canon(n,t) for n,t in zip(df.target_raw, df.target_type)]
    df["source_name_norm"] = df.source_name.map(norm_entity)
    df["target_name_norm"] = df.target_name.map(norm_entity)
    df["source_id"] = [sha1(f"{t}:{n}".encode()).hexdigest()[:24] for t,n in zip(df.source_type, df.source_name_norm)]
    df["target_id"] = [sha1(f"{t}:{n}".encode()).hexdigest()[:24] for t,n in zip(df.target_type, df.target_name_norm)]
    return df[df.source_id != df.target_id].reset_index(drop=True)

entity_map, entity_resolution_audit_df = build_resolution_map(raw_triples_df)
triples_df = canonicalize_triples(raw_triples_df, entity_map)
display(entity_resolution_audit_df.head(20))

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 2685.86it/s]

,type,left,right,similarity,decision
0,Company,Fidelity National Information Services,Fidelity National Information Services Inc.,0.924524,MERGE_VECTOR
1,Company,L&T Technology Services Limited,L&T Technology Services Ltd,0.920202,MERGE_VECTOR
2,Technology,healthcare information technology,healthcare information technology services,0.902359,REJECT_GUARD
3,Technology,X90A,X90,0.920579,REJECT_GUARD

In [11]:
#@title 2.3 — Node table + UNWIND bulk insert
def build_nodes(triples_df):
    rows = []
    for r in triples_df.itertuples(index=False):
        rows += [
            {"id":r.source_id,"name":r.source_name,"name_norm":r.source_name_norm,"type":r.source_type,"alias":r.source_raw},
            {"id":r.target_id,"name":r.target_name,"name_norm":r.target_name_norm,"type":r.target_type,"alias":r.target_raw},
        ]
    tmp = pd.DataFrame(rows)
    if tmp.empty:
        return tmp

    out = []
    for (node_id,name,name_norm,typ), g in tmp.groupby(["id","name","name_norm","type"]):
        aliases = sorted(set(g["alias"].map(norm_space)))
        out.append({
            "id":node_id, "name":name, "name_norm":name_norm, "type":typ,
            "aliases":aliases,
            "aliases_norm":sorted(set(norm_entity(x) for x in aliases))
        })
    return pd.DataFrame(out)

def batches(records, size=1000):
    for i in range(0, len(records), size):
        yield records[i:i+size]

def bulk_insert_nodes(nodes_df, batch_size=1000):
    for typ in sorted(ALLOWED_NODE_TYPES):
        part = nodes_df[nodes_df.type == typ]
        if part.empty:
            continue
        query = f"""
        UNWIND $rows AS row
        MERGE (n:Entity {{id: row.id}})
        SET n:{typ},
            n.name=row.name,
            n.name_norm=row.name_norm,
            n.entity_type=row.type,
            n.aliases=row.aliases,
            n.aliases_norm=row.aliases_norm
        """
        for b in batches(part.to_dict("records"), batch_size):
            run_cypher(query, rows=b)

def bulk_insert_edges(triples_df, batch_size=1000):
    required = {"source_chunk_id","published_date"}
    if not required.issubset(triples_df.columns):
        raise ValueError("Missing edge provenance.")

    for rel in sorted(ALLOWED_RELATIONS):
        part = triples_df[triples_df.relation == rel]
        if part.empty:
            continue

        query = f"""
        UNWIND $rows AS row
        MATCH (s:Entity {{id: row.source_id}})
        MATCH (t:Entity {{id: row.target_id}})
        MERGE (s)-[r:{rel} {{source_chunk_id: row.source_chunk_id}}]->(t)
        SET r.published_date=row.published_date,
            r.evidence=row.evidence,
            r.confidence=row.confidence
        """

        cols = ["source_id","target_id","source_chunk_id","published_date","evidence","confidence"]
        for b in batches(part[cols].to_dict("records"), batch_size):
            run_cypher(query, rows=b)

nodes_df = build_nodes(triples_df)
bulk_insert_nodes(nodes_df)
bulk_insert_edges(triples_df)

In [12]:
#@title 2.4 — Sanity checks
def graph_checks():
    invalid = run_cypher("""
    MATCH ()-[r]->()
    WHERE r.source_chunk_id IS NULL OR r.published_date IS NULL
    RETURN count(r) AS n
    """)[0]["n"]

    counts = {
        "nodes": run_cypher("MATCH (n:Entity) RETURN count(n) AS n")[0]["n"],
        "edges": run_cypher("MATCH ()-[r]->() RETURN count(r) AS n")[0]["n"],
        "invalid_provenance_edges": invalid,
    }
    print(counts)
    assert invalid == 0

    top = pd.DataFrame(run_cypher("""
    MATCH (n:Entity)
    OPTIONAL MATCH (n)-[r]-()
    WITH n, count(r) AS degree
    RETURN n.id AS id, n.name AS name, n.entity_type AS type, degree
    ORDER BY degree DESC LIMIT 15
    """))
    display(top)
    return counts, top

graph_counts, top_degree_df = graph_checks()

{'nodes': 380, 'edges': 259, 'invalid_provenance_edges': 0}

                          id                             name     type  degree
0   af61c9129da522c49e916ec6  L&T Technology Services Limited  Company       7
1   33e26345a3f61f0bc587821f       Hyperion Defense Solutions  Company       5
2   cc9c6ee3857729e221d3f6de                       ServiceNow  Company       5
3   adc0f89fca852dd3fb0443bb                             Citi  Company       4
4   bc18d55f3997314f76b638e5                           Senser  Company       4
5   261a323bf5773a8433c812a6                        DriveNets  Company       4
6   44d14f66663379fb5a148405                         Tim Grey   Person       4
7   68b0f1e1adc856f11ca32dba    Cass Information Systems Inc.  Company       4
8   6763840dfe2e4e1d3562e71e                 Chris Derbyshire   Person       4
9   d3375cc1a631efa9976e8d53                        Synechron  Company       3
10  f4a26eedddc593a6915d7fa2                             ILUS  Company       3
11  97a848cd7c0c35ec1666edd4                        BroadStar  Company       3
12  6a5d372d7ba49540d8a00beb                          Revolut  Company       3
13  482e949a0b6c21ca2b8da03e                         Infineon  Company       3
14  8568cefc2b16b1699bc0d89f                            Aqara  Company       3

# PHẦN 3 — FLAT RAG & HYBRID GRAPHRAG (45–75')

## Flat RAG baseline
Dùng cùng embedding/generator để comparison tập trung vào retrieval architecture.

In [13]:
#@title 3.1 — Flat RAG
flat_index = None
flat_store = None
entity_match_vectors = None
entity_match_store = None

def build_flat_index(chunks_df):
    global flat_index, flat_store
    vecs = get_embedder().encode(
        chunks_df.text.fillna("").tolist(),
        batch_size=128, show_progress_bar=True,
        normalize_embeddings=True
    ).astype("float32")

    flat_index = faiss.IndexFlatIP(vecs.shape[1])
    flat_index.add(vecs)
    flat_store = chunks_df.reset_index(drop=True).copy()
    print("Flat vectors:", flat_index.ntotal)

def retrieve_flat_context(query, k=6):
    qv = get_embedder().encode(
        [query], normalize_embeddings=True, show_progress_bar=False
    ).astype("float32")
    scores, ids = flat_index.search(qv, min(k, flat_index.ntotal))

    rows = []
    for score, idx in zip(scores[0], ids[0]):
        if idx < 0:
            continue
        r = flat_store.iloc[int(idx)]
        rows.append({
            "score":float(score), "chunk_id":r.chunk_id,
            "published_date":r.published_date, "text":r.text
        })

    df = pd.DataFrame(rows)
    context = "\n\n".join(
        f"[chunk_id={r.chunk_id} | date={r.published_date} | score={r.score:.3f}]\n{r.text}"
        for r in df.itertuples(index=False)
    )
    return context, df

build_flat_index(chunks_df)

Batches:   0%|          | 0/12 [00:00<?, ?it/s]

Batches:   8%|▊         | 1/12 [00:03<00:43,  3.92s/it]

Batches:  17%|█▋        | 2/12 [00:05<00:22,  2.27s/it]

Batches:  25%|██▌       | 3/12 [00:06<00:15,  1.69s/it]

Batches:  33%|███▎      | 4/12 [00:07<00:13,  1.65s/it]

Batches:  42%|████▏     | 5/12 [00:08<00:09,  1.40s/it]

Batches:  50%|█████     | 6/12 [00:09<00:07,  1.21s/it]

Batches:  58%|█████▊    | 7/12 [00:10<00:05,  1.09s/it]

Batches:  67%|██████▋   | 8/12 [00:11<00:04,  1.02s/it]

Batches:  75%|███████▌  | 9/12 [00:11<00:02,  1.06it/s]

Batches:  83%|████████▎ | 10/12 [00:12<00:01,  1.10it/s]

Batches:  92%|█████████▏| 11/12 [00:13<00:00,  1.22it/s]

Batches: 100%|██████████| 12/12 [00:13<00:00,  1.39it/s]

Batches: 100%|██████████| 12/12 [00:13<00:00,  1.16s/it]

Flat vectors: 1500

## Graph retrieval flow
1. LLM trích seed entities.
2. Match seed trong Neo4j; fuzzy fallback bằng embedding.
3. BFS tối đa `max_hops`.
4. Nếu node degree > 100 → chỉ lấy tối đa 50 edge mới nhất.
5. Global edge cap để tránh context explosion.
6. Textualize subgraph có provenance.

In [14]:
#@title 3.2 — Seed matching
SEED_SYSTEM = """
Extract useful seed entities for graph retrieval.
Allowed types: Company, Person, Technology.
Do not answer the question. Return strict JSON only.
""".strip()

def extract_seeds(query):
    obj, _ = groq_json(SEED_SYSTEM, f"""
Question: {query}
Return {{"seeds":[{{"name":"...","type":"Company|Person|Technology|null"}}]}}
""")
    return [
        {"name":norm_space(x.get("name")),
         "type":x.get("type") if x.get("type") in ALLOWED_NODE_TYPES else None}
        for x in obj.get("seeds", [])
        if norm_space(x.get("name"))
    ]

def build_entity_matcher(nodes_df):
    global entity_match_vectors, entity_match_store
    entity_match_store = nodes_df.reset_index(drop=True).copy()
    entity_match_vectors = get_embedder().encode(
        entity_match_store.name.tolist(),
        batch_size=128, show_progress_bar=False,
        normalize_embeddings=True
    ).astype("float32")

def match_seeds(query, fuzzy_threshold=0.66):
    matched = []
    for seed in extract_seeds(query):
        exact = run_cypher("""
        MATCH (n:Entity)
        WHERE (n.name_norm=$name OR $name IN coalesce(n.aliases_norm,[]))
          AND ($typ IS NULL OR n.entity_type=$typ)
        RETURN n.id AS id, n.name AS name, n.entity_type AS type
        LIMIT 5
        """, name=norm_entity(seed["name"]), typ=seed["type"])

        if exact:
            matched += exact
            continue

        if entity_match_vectors is None:
            continue

        mask = np.ones(len(entity_match_store), dtype=bool)
        if seed["type"]:
            mask = entity_match_store.type.eq(seed["type"]).to_numpy()
        idxs = np.flatnonzero(mask)
        if not len(idxs):
            continue

        qv = get_embedder().encode(
            [seed["name"]], normalize_embeddings=True, show_progress_bar=False
        ).astype("float32")[0]
        sims = entity_match_vectors[idxs] @ qv
        j = int(np.argmax(sims))
        if float(sims[j]) >= fuzzy_threshold:
            r = entity_match_store.iloc[int(idxs[j])]
            matched.append({"id":r.id,"name":r.name,"type":r.type})

    return list({x["id"]: x for x in matched}.values())

build_entity_matcher(nodes_df)

In [15]:
#@title 3.3 — Graph traversal + super-node mitigation
SUPER_NODE_DEGREE = 100
SUPER_NODE_EDGE_CAP = 50
GLOBAL_EDGE_CAP = 250
MAX_GRAPH_CONTEXT_CHARS = 14000

def node_degree(node_id):
    return int(run_cypher("""
    MATCH (n:Entity {id:$id})
    OPTIONAL MATCH (n)-[r]-()
    RETURN count(r) AS degree
    """, id=node_id)[0]["degree"])

def recent_edges(node_id, limit):
    return run_cypher("""
    MATCH (n:Entity {id:$id})
    MATCH (n)-[r]-(m:Entity)
    RETURN
      startNode(r).id AS source_id,
      startNode(r).name AS source_name,
      startNode(r).entity_type AS source_type,
      type(r) AS relation,
      endNode(r).id AS target_id,
      endNode(r).name AS target_name,
      endNode(r).entity_type AS target_type,
      r.source_chunk_id AS source_chunk_id,
      r.published_date AS published_date,
      r.evidence AS evidence,
      m.id AS neighbor_id
    ORDER BY coalesce(r.published_date,'') DESC
    LIMIT $limit
    """, id=node_id, limit=int(limit))

def textualize(edges):
    edges = sorted(edges, key=lambda e:e.get("published_date") or "", reverse=True)
    lines, used = [], 0
    for e in edges:
        line = (
            f"{e['source_name']} [{e['source_type']}] -{e['relation']}-> "
            f"{e['target_name']} [{e['target_type']}] "
            f"| date={e.get('published_date') or 'unknown'} "
            f"| chunk={e.get('source_chunk_id') or 'unknown'}"
        )
        if e.get("evidence"):
            line += f" | evidence={norm_space(e['evidence'])}"
        if used + len(line) + 1 > MAX_GRAPH_CONTEXT_CHARS:
            break
        lines.append(line)
        used += len(line) + 1
    return "\n".join(lines)

def retrieve_graph_context(query, max_hops=2, edge_limit=50, return_debug=False):
    seeds = match_seeds(query)
    if not seeds:
        out = {"context":"","edges":pd.DataFrame(),
               "diagnostics":{"reason":"NO_SEED","supernode_events":[]}}
        return out if return_debug else ""

    frontier = deque((x["id"],0) for x in seeds)
    expanded, seen_edges, collected = set(), set(), []
    supernode_events = []

    while frontier and len(collected) < GLOBAL_EDGE_CAP:
        node_id, hop = frontier.popleft()
        if node_id in expanded or hop >= max_hops:
            continue
        expanded.add(node_id)

        degree = node_degree(node_id)
        limit = int(edge_limit)
        if degree > SUPER_NODE_DEGREE:
            limit = min(limit, SUPER_NODE_EDGE_CAP)
            supernode_events.append({"node_id":node_id,"degree":degree,"limit":limit})

        for e in recent_edges(node_id, limit):
            key = (e["source_id"],e["relation"],e["target_id"],e["source_chunk_id"])
            if key in seen_edges:
                continue
            seen_edges.add(key)
            collected.append(e)
            if len(collected) >= GLOBAL_EDGE_CAP:
                break

            nb = e.get("neighbor_id")
            if nb and nb not in expanded and hop + 1 < max_hops:
                frontier.append((nb, hop+1))

    out = {
        "context": textualize(collected),
        "edges": pd.DataFrame(collected),
        "diagnostics": {
            "matched_seeds": seeds,
            "expanded_nodes": len(expanded),
            "collected_edges": len(collected),
            "supernode_events": supernode_events,
        }
    }
    return out if return_debug else out["context"]

In [16]:
#@title 3.4 — Flat answer vs Hybrid GraphRAG answer
ANSWER_SYSTEM = """
Answer only from supplied context.
Be concise but complete. Do not invent facts.
Cite provenance inline as [chunk_id=...] whenever possible.
If evidence is insufficient or conflicting, say so.
""".strip()

def generate_answer(question, context):
    prompt = f"QUESTION:\n{question}\n\nCONTEXT:\n{context}\n\nANSWER:"
    t0 = time.perf_counter()
    text, usage = groq_chat(
        [{"role":"system","content":ANSWER_SYSTEM},
         {"role":"user","content":prompt}],
        model=GROQ_MODEL
    )
    return {
        "answer": text.strip(),
        "latency_s": time.perf_counter()-t0,
        "total_tokens": usage.get("total_tokens"),
    }

def answer_flat_rag(question):
    context, retrieved = retrieve_flat_context(question, k=6)
    out = generate_answer(question, context)
    out.update({"context":context,"retrieved":retrieved})
    return out

def answer_graph_rag(question):
    g = retrieve_graph_context(question, max_hops=2, edge_limit=50, return_debug=True)
    vctx, vdocs = retrieve_flat_context(question, k=4)
    context = f"=== GRAPH ===\n{g['context']}\n\n=== VECTOR ===\n{vctx}"
    out = generate_answer(question, context)
    out.update({"context":context,"graph_debug":g,"vector_docs":vdocs})
    return out

# PHẦN 4 — GOLDEN DATASET & LLM-AS-A-JUDGE (75–105')

## Golden schema
`id`, `group`, `question`, `reference_answer`, optional `reference_evidence`.

Notebook có 5 câu starter. Các câu phụ thuộc data dump phải điền gold answer thật trước final evaluation.

In [17]:
#@title 4.1 — 5 câu Golden starter
GOLDEN_PATH = "data/graphrag_golden_50_first5000.csv"

starter_golden = pd.DataFrame([
    {
        "id":"G01","group":"factoid",
        "question":"Who was the CEO of Hugging Face in 2023?",
        "reference_answer":"Clément Delangue",
        "reference_evidence":"Validate against instructor dump."
    },
    {
        "id":"G02","group":"multi-hop",
        "question":"Which startups were founded by former Microsoft employees and later received investment from Google?",
        "reference_answer":"Placeholder answer",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G03","group":"cross-doc",
        "question":"Compare the direction of AI-related investments by Meta and Apple during 2023 using evidence from multiple articles.",
        "reference_answer":"Placeholder answer",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G04","group":"multi-hop",
        "question":"Find a company invested in by a major technology company that also developed a named AI technology; identify both relations and dates.",
        "reference_answer":"Placeholder answer",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
    {
        "id":"G05","group":"cross-doc",
        "question":"Identify one technology connected to the same company in at least two news chunks and summarize how the relationship changed over time.",
        "reference_answer":"Placeholder answer",
        "reference_evidence":"TO_BE_FILLED_FROM_DATASET"
    },
])

golden_df = pd.read_csv(GOLDEN_PATH) if Path(GOLDEN_PATH).exists() else starter_golden.copy()
display(golden_df)

def validate_golden(df, require_answers=True):
    required = {"id","group","question","reference_answer"}
    if not required.issubset(df.columns):
        raise ValueError(f"Missing columns: {required-set(df.columns)}")
    if require_answers and df.reference_answer.fillna("").str.strip().eq("").any():
        display(df[df.reference_answer.fillna("").str.strip().eq("")][["id","question"]])
        raise ValueError("Điền reference_answer trước final evaluation.")
    print("✅ Golden Dataset valid.")

,id,group,question,reference_answer,reference_evidence
0,G5000-01,multi-hop,Reconstruct the Aeris–Ericsson IoT transaction across the available reports: which Ericsson businesses moved to Aeri...,"Ericsson's IoT Accelerator and Connected Vehicle Cloud businesses, together with related assets, were to be transfer...",row 33 (2022-12-07 13:45:00): Aeris to Acquire IoT Business from Ericsson | row 1746 (2023-01-10 06:19:00): Aeris to...
1,G5000-02,cross-doc,"Did the first two Aeris/Ericsson reports describe a completed acquisition or a planned transfer, and what later evid...",The first reports describe a planned transaction: Aeris was to acquire Ericsson's IoT Accelerator and Connected Vehi...,row 33 (2022-12-07 13:45:00): Aeris to Acquire IoT Business from Ericsson | row 1746 (2023-01-10 06:19:00): Aeris to...
2,G5000-03,factoid,"After the Aeris–Ericsson IoT deal progressed, how many IoT devices, enterprises, and countries were cited in the lat...","More than 100 million IoT devices, 9,000 enterprises, and 190 countries.",row 935 (2023-01-18 22:37:00): A Leap in Connectivity: Aeris Acquires Technologies from Ericsson to Support Cellular...
3,G5000-04,cross-doc,"Which two named Ericsson IoT businesses recur across multiple reports of the Aeris transaction, and why should Graph...",The recurring businesses are Ericsson IoT Accelerator and Connected Vehicle Cloud. The reports describe the same Aer...,row 33 (2022-12-07 13:45:00): Aeris to Acquire IoT Business from Ericsson | row 1746 (2023-01-10 06:19:00): Aeris to...
4,G5000-05,multi-hop,"Starting from Ericsson, follow the graph to the acquirer and then to the reported IoT reach. What path and scale sho...",Ericsson -> (IoT Accelerator and Connected Vehicle Cloud transferred/acquired by) Aeris -> supports/connects more th...,row 33 (2022-12-07 13:45:00): Aeris to Acquire IoT Business from Ericsson | row 935 (2023-01-18 22:37:00): A Leap in...
5,G5000-06,multi-hop,Trace ServiceNow's generative-AI product/partner evolution from May through July 2023: what partnership began in May...,"In May, ServiceNow partnered with NVIDIA to build enterprise-grade generative AI for workflow automation. In June, S...",row 746 (2023-05-17 18:58:00): ServiceNow and NVIDIA Announce Partnership to Build Generative AI Across Enterprise I...
6,G5000-07,cross-doc,How did ServiceNow's July generative-AI expansion differ between its platform features and its ecosystem program wit...,ServiceNow expanded the Now Assist feature set with case summarization and text-to-code inside its workflow platform...,row 1435 (2023-07-26 20:30:00): ServiceNow Expands Generative AI Capabilities With Case Summarization and Text-to-Co...
7,G5000-08,multi-hop,"Which external organizations are connected to ServiceNow's generative-AI efforts in the selected data, and what dist...",NVIDIA is ServiceNow's generative-AI technology partner and later co-launch partner for AI Lighthouse; Accenture joi...,row 746 (2023-05-17 18:58:00): ServiceNow and NVIDIA Announce Partnership to Build Generative AI Across Enterprise I...
8,G5000-09,cross-doc,Two June 13 reports describe Now Assist for Virtual Agent. What should a deduplicated graph store as the core event ...,A single ServiceNow product event: Now Assist for Virtual Agent extends ServiceNow's generative-AI capabilities for ...,row 1742 (2023-06-13 13:50:00): ServiceNow Unveils Generative AI Solution With Real-Time Conversational Experiences ...
9,G5000-10,multi-hop,What sequence shows ServiceNow moving from domain-specific generative-AI exploration to concrete workflow features?,"At Knowledge 2023, ServiceNow emphasized domain-specific generative-AI/LLM use cases; in June it introduced Now Assi...",row 752 (2023-05-18 00:32:00): Knowledge 2023 - ServiceNow looks beyond general purpose generative AI to domain-spec...
10,G5000-11,cross-doc,Compare the May ServiceNow–NVIDIA announcement with the July AI Lighthouse announcement. What new entity and new pro...,"The May announcement is a bilateral ServiceNow–NVIDIA partnership to build enterprise-grade generative AI. In July, ...",row 746 (2023-05-17 18:58:00): ServiceNow and NVIDIA Announce Partnership to Build Generative AI Across Enterprise I...
11,G5000-12,multi-hop,"Starting from Now Assist, connect it to both a July platform enhancement and an October services alliance. What are ...","In July, the Now Assist family was expanded with case summarization and text-to-code. In October, Deloitte and Servi...",row 1435 (2023-07-26 20:30:00): ServiceNow Expands Generative AI Capabilities With Case Summarization and Text-to-Co...
12,G5000-13,factoid,"Which three companies launched AI Lighthouse in the selected 5,000-row scope?","ServiceNow, NVIDIA, and Accenture.",row 648 (2023-07-27 18:43:00): ServiceNow NVIDIA and Accenture Partner to Accelerate Generative AI Adoption for Ente...
13,G5000-14,multi-hop,"Compare Microsoft's ChatGPT/OpenAI delivery to three customer contexts in 2023: a utility, private businesses, and U...",DEWA said it was enriching utility services with ChatGPT technology supported by Microsoft; a May report said Micros...,row 215 (2023-02-09 11:20:00): DEWA is the first utility in the world to enrich its services with ChatGPT technology...
14,G5000-15,cross-doc,How did Microsoft's Copilot surface area change between March and September 2023?,"In March, Copilot was described as AI functionality being infused into Office apps including Word, Excel, and Outloo...",row 2471 (2023-03-17 15:48:00): Microsoft adds AI tools to Outlook Word | row 3043 (2023-09-21 18:25:00): Microsoft’...
15,G5000-16,cross-doc,Which Microsoft AI offering in the selected data was explicitly described as potentially running on dedicated server...,The private ChatGPT offering for businesses was described as potentially running on dedicated servers and as somethi...,row 4944 (2023-05-02 17:49:00): Microsoft could offer private ChatGPT to businesses for “10 times” the normal cost |...
16,G5000-17,multi-hop,"Reconstruct the early-June Microsoft outage incident from the three reports: what attack type was claimed, and which...",The reports describe the same early-June Microsoft disruption as cyberattacks; a hacktivist group claimed it used di...,row 1943 (2023-06-18 00:19:00): Microsoft says early June service outages were cyberattacks | row 2566 (2023-06-18 0...
17,G5000-18,cross-doc,"Why should rows 1943, 2566, and 3284 be treated as duplicate/follow-up evidence for one Microsoft incident rather th...","All three are dated June 18, refer to the same early-June disruptions of Microsoft services/Outlook cloud platform, ...",row 1943 (2023-06-18 00:19:00): Microsoft says early June service outages were cyberattacks | row 2566 (2023-06-18 0...
18,G5000-19,multi-hop,"What did KPMG commit to spend, on what two technology areas, and through which partner relationship?",KPMG said it would spend $2 billion on artificial intelligence and cloud services through an expanded partnership wi...,row 3054 (2023-07-11 23:31:00): KPMG to invest $2 billion in AI cloud services
19,G5000-20,cross-doc,How did Options Technology's Microsoft partner designations expand from May to June 2023?,"In May, Options Technology announced Microsoft Solutions Partner status for Infrastructure. In June, it announced Mi...",row 1187 (2023-05-10 09:54:00): Options Announces Achievement of Microsoft Infrastructure Solutions Partner Status |...
20,G5000-21,multi-hop,Combine Microsoft's Poland infrastructure story with KPMG's July AI/cloud investment story. What two distinct kinds ...,"Microsoft launched a cloud data storage/processing hub in central Poland, representing physical cloud infrastructure...",row 3337 (2023-04-26 22:23:00): Microsoft opens top cloud data processing hub in Poland | row 3054 (2023-07-11 23:31...
21,G5000-22,multi-hop,"From Office Copilot to unified Windows Copilot, what entities and surfaces form the product-expansion path?","Microsoft Copilot first appears across Office applications such as Word, Excel, and Outlook; later Microsoft describ...",row 2471 (2023-03-17 15:48:00): Microsoft adds AI tools to Outlook Word | row 3043 (2023-09-21 18:25:00): Microsoft’...
22,G5000-23,cross-doc,"Which Microsoft-related story is a confirmed external customer use of ChatGPT, and which is only a reported potentia...",DEWA's February announcement is a confirmed customer use case: it said it was working to enrich services with ChatGP...,row 215 (2023-02-09 11:20:00): DEWA is the first utility in the world to enrich its services with ChatGPT technology...
23,G5000-24,factoid,What Microsoft settlement amount is reported for illegally collecting children's personal information?,$20 million.,row 2511 (2023-06-07 09:36:00): Microsoft pays $20 million settlement for collecting children’s data
24,G5000-25,cross-doc,"Was AWS reported to have adopted AMD's new AI chips, or only to be evaluating them? What evidence in the selected da...","AWS was reported to be considering AMD's new AI chips, and an AWS executive said no final decision had been made. Th...",row 2905 (2023-06-14 08:47:00): Exclusive: Amazon's cloud unit is considering AMD's new AI chips
25,G5000-26,multi-hop,"What external technology provider is named inside Amazon's July AI-service expansion, and what other new AI capabili...",Amazon's AI-service story names access to technology from Cohere. It also mentions a program for building more conve...,row 2532 (2023-07-26 20:19:00): Exclusive: Amazon has drawn thousands to try its AI service competing with Microsoft...
26,G5000-27,cross-doc,How should the graph reconcile the statement that AMD powers multiple cloud services with the later Reuters report a...,The June 1 investment article broadly says AMD powers multiple cloud services through its chips. The June 14 Reuters...,row 3357 (2023-06-01 13:16:00): 3 Best Cloud Stocks to Buy in June | row 2905 (2023-06-14 08:47:00): Exclusive: Amaz...
27,G5000-28,multi-hop,"Which model providers are connected to Google Cloud Next '23 in the selected data, and which models are associated w...",Meta is connected via Llama 2 and Code Llama; the Technology Innovation Institute is connected via Falcon LLM; Anthr...,row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud
28,G5000-29,cross-doc,How did participation in White House AI commitments broaden from July to September 2023 according to the selected re...,"The July report names seven companies including Google, Meta, and OpenAI as making voluntary AI commitments. The Sep...",row 3380 (2023-07-21 13:01:00): The White House and big tech companies release commitments on managing AI | row 3330...
29,G5000-30,multi-hop,"Meta appears in two different AI contexts in the selected data. What are they, and what distinct relation should the...","At Google Cloud Next, Meta is the provider/source of Llama 2 and Code Llama models made available on Google Cloud. S...",row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud | row 3380 (2023-07-21 13:01...
30,G5000-31,multi-hop,"Order OpenAI's ecosystem moves from March through July 2023 using the selected sources: plug-ins, open-source model ...",March: ChatGPT gained support for about a dozen application plug-ins. May: OpenAI was reported to be preparing a new...,row 3938 (2023-03-24 15:58:00): OpenAI's ChatGPT gets support for a dozen application plug-ins | row 946 (2023-05-15...
31,G5000-32,cross-doc,What is the difference between OpenAI's March plug-in development and its June reported app-store plan?,The March story describes ChatGPT gaining support for application plug-ins so companies can expose product functiona...,row 3938 (2023-03-24 15:58:00): OpenAI's ChatGPT gets support for a dozen application plug-ins | row 2449 (2023-06-2...
32,G5000-33,cross-doc,"Which July OpenAI-related event is a content/technology collaboration, and which July event is a voluntary governanc...",The AP–OpenAI agreement is a collaboration to share access to select news content and technology for generative-AI u...,row 366 (2023-07-13 00:00:00): AP Open AI agree to share select news content and technology in new collaboration | r...
33,G5000-34,multi-hop,Compare how Google Cloud and Amazon expanded their AI ecosystems in the selected data. Which third-party model/techn...,"Google Cloud announced models from Meta (Llama 2 and Code Llama), the Technology Innovation Institute (Falcon LLM), ...",row 3395 (2023-08-29 18:07:00): Google Cloud Kicks Off Next '23 with a New Way to Cloud | row 2532 (2023-07-26 20:19...
34,G5000-35,cross-doc,Contrast AWS's AMD-chip posture with HPE's AI-cloud posture. Which is a tentative hardware sourcing decision and whi...,"AWS was only considering AMD's new AI chips, with no final decision. HPE said it would offer a cloud computing servi...",row 2905 (2023-06-14 08:47:00): Exclusive: Amazon's cloud unit is considering AMD's new AI chips | row 3289 (2023-06...
35,G5000-36,cross-doc,"Rows 2532 and 2537 have near-identical Amazon AI headlines. What single event should be stored, and what details can...",They should be stored as one Amazon AI-service expansion story competing with Microsoft and Google. Safe unioned det...,row 2532 (2023-07-26 20:19:00): Exclusive: Amazon has drawn thousands to try its AI service competing with Microsoft...
36,G5000-37,cross-doc,What evidence shows Dell NativeEdge moving from a May product announcement to a July use-case description?,The May Dell Technologies World report says Dell released NativeEdge. A July networking article describes NativeEdge...,row 4407 (2023-05-24 02:49:00): Projects become products: Dell unveils its long-term game plan for the edge | row 49...
37,G5000-38,multi-hop,How do Dell's APEX Cloud Platforms and NativeEdge represent two different infrastructure layers in its portfolio?,APEX Cloud Platforms are presented as part of Dell's cloud-smart/multicloud strategy and integrate services from Mic...,row 1808 (2023-05-26 14:56:00): From multicloud challenges to ‘cloud-smart’ solutions: How Dell is simplifying multi...
38,G5000-39,multi-hop,What two strategic capability areas did HPE expand in 2023 through the Axis Security deal and its later AI cloud ann...,"HPE moved to expand edge-to-cloud security by agreeing to acquire Axis Security, enabling a unified SASE offering. L...",row 4762 (2023-03-02 22:32:00): Hewlett Packard Enterprise Fortifies Network Security With Acquisition of Security S...
39,G5000-40,cross-doc,Compare Dell and HPE's cloud strategies in the selected scope: which one explicitly integrates Microsoft Azure servi...,Dell's APEX Cloud Platforms story explicitly says the platform integrates services from Microsoft Azure. HPE's story...,row 1808 (2023-05-26 14:56:00): From multicloud challenges to ‘cloud-smart’ solutions: How Dell is simplifying multi...
40,G5000-41,factoid,"Which company did HPE agree to acquire to expand edge-to-cloud security, and what unified security architecture did ...",Axis Security; a unified Secure Access Service Edge (SASE) solution.,row 4762 (2023-03-02 22:32:00): Hewlett Packard Enterprise Fortifies Network Security With Acquisition of Security S...
41,G5000-42,multi-hop,"Starting from the edge-computing concept, connect one Dell product and one HPE transaction to two different edge-rel...",Dell NativeEdge is described as helping deploy and manage edge computing applications and infrastructure. HPE's plan...,row 4997 (2023-07-17 00:00:00): Networking and communication | row 4762 (2023-03-02 22:32:00): Hewlett Packard Enter...
42,G5000-43,cross-doc,Which came first in the selected HPE timeline: the Axis Security acquisition agreement or the LLM-focused cloud serv...,"The Axis Security acquisition agreement came first on March 2, 2023; the HPE LLM-focused cloud service story followe...",row 4762 (2023-03-02 22:32:00): Hewlett Packard Enterprise Fortifies Network Security With Acquisition of Security S...
43,G5000-44,multi-hop,What two distinct partner ecosystems connect L&T Technology Services to advanced infrastructure in 2023: one for urb...,"For urban-rail private 5G, Thales selected L&T Technology Services and Qualcomm. For OT security, L&T Technology Ser...",row 261 (2023-02-23 10:51:00): L&T Technology Services and Qualcomm Selected by Thales for Enabling 5G Private Netwo...
44,G5000-45,cross-doc,Rows 261 and 891 describe L&T Technology Services and Qualcomm being selected by Thales. How should a production gra...,The two reports describe the same Thales selection of L&T Technology Services and Qualcomm for enabling 5G private n...,row 261 (2023-02-23 10:51:00): L&T Technology Services and Qualcomm Selected by Thales for Enabling 5G Private Netwo...
45,G5000-46,cross-doc,Distinguish the cybersecurity relationships in the Keysight–Synopsys article and the LTTS–Palo Alto Networks article...,Keysight and Synopsys are the partners in the IoT-device cybersecurity article. L&T Technology Services and Palo Alt...,row 272 (2023-09-21 16:15:00): Keysight and Synopsys Partner for IoT Device Cybersecurity | row 471 (2023-06-30 08:5...
46,G5000-47,factoid,"In the Keysight–Synopsys IoT cybersecurity record, does the mention of Palo Alto Networks establish Palo Alto as a p...",No. The title identifies Keysight and Synopsys as the partners. Palo Alto Networks appears only as the source of an ...,row 272 (2023-09-21 16:15:00): Keysight and Synopsys Partner for IoT Device Cybersecurity
47,G5000-48,multi-hop,Combine the three Snowflake-related records to summarize Snowflake's role in the 2023 cloud/data ecosystem: what AI ...,H2O.ai launched H2O AI Cloud as a pre-built solution for Snowflake's Manufacturing Data Cloud; Snowflake was listed ...,row 3498 (2023-04-13 16:02:00): H2O.ai Brings H2O AI Cloud to the Snowflake Manufacturing Data Cloud | row 2589 (202...
48,G5000-49,multi-hop,"Across the selected Samsung records, identify three distinct technology domains Samsung is connected to and the spec...",Display/biometric sensing: Samsung unveiled a Sensor OLED Display with an embedded light-sensing organic photodiode ...,row 472 (2023-05-23 22:48:00): Samsung unveils OLED display with embedded heart rate sensor | row 395 (2023-10-05 23...
49,G5000-50,multi-hop,"Compare the chip-related AI positioning of NVIDIA, AMD, and Intel in the selected 5,000-row scope. What distinct sig...",NVIDIA reported that use of its chips for AI services such as chatbots had gone 'through the roof' and its sales out...,row 3432 (2023-02-22 23:36:00): As chatbots boom Nvidia sales outlook beats Wall Street expectations | row 2905 (202...

In [18]:
#@title 4.2 — LLM-as-a-Judge
JUDGE_SYSTEM = """
You are a strict evaluator of RAG answers.
Score 1-5:
- comprehensiveness
- faithfulness to supplied candidate context
- multi_hop_reasoning accuracy
Use the reference answer as correctness anchor.
Return strict JSON only.
""".strip()

def judge_json(system, user):
    if not JUDGE_MODEL:
        raise RuntimeError("Thiếu JUDGE_MODEL.")

    if JUDGE_PROVIDER == "groq":
        return groq_json(system, user, model=JUDGE_MODEL)[0]

    if JUDGE_PROVIDER == "openai":
        if not OPENAI_API_KEY:
            raise RuntimeError("Thiếu OPENAI_API_KEY.")
        from openai import OpenAI
        client = OpenAI(api_key=OPENAI_API_KEY)
        resp = client.chat.completions.create(
            model=JUDGE_MODEL,
            messages=[{"role":"system","content":system},
                      {"role":"user","content":user}],
            temperature=0.0,
            response_format={"type":"json_object"}
        )
        return parse_json_object(resp.choices[0].message.content)

    raise ValueError("JUDGE_PROVIDER must be openai or groq.")

def judge_answer(question, reference, answer, context):
    prompt = f"""
QUESTION:
{question}

REFERENCE:
{reference}

CANDIDATE:
{answer}

CANDIDATE CONTEXT:
{context[:18000]}

Return:
{{
 "comprehensiveness":1,
 "faithfulness":1,
 "multi_hop_reasoning":1,
 "rationale":"2-5 sentences"
}}
"""
    obj = judge_json(JUDGE_SYSTEM, prompt)
    out = {}
    for k in ["comprehensiveness","faithfulness","multi_hop_reasoning"]:
        out[k] = max(1, min(5, int(obj.get(k,1))))
    out["rationale"] = norm_space(obj.get("rationale"))
    return out

In [19]:
#@title 4.3 — Evaluation runner + checkpoint
CHECKPOINT = "outputs/graphrag_eval_checkpoint.csv"

def run_evaluation(golden_df):
    rows = []
    for q in tqdm(golden_df.itertuples(index=False), total=len(golden_df), desc="Evaluation"):
        flat = answer_flat_rag(q.question)
        graph = answer_graph_rag(q.question)

        jf = judge_answer(q.question, q.reference_answer, flat["answer"], flat["context"])
        jg = judge_answer(q.question, q.reference_answer, graph["answer"], graph["context"])

        rows.append({
            "id":q.id, "group":q.group, "question":q.question,
            "reference_answer":q.reference_answer,
            "flat_answer":flat["answer"], "graph_answer":graph["answer"],
            "flat_comprehensiveness":jf["comprehensiveness"],
            "graph_comprehensiveness":jg["comprehensiveness"],
            "flat_faithfulness":jf["faithfulness"],
            "graph_faithfulness":jg["faithfulness"],
            "flat_multi_hop_reasoning":jf["multi_hop_reasoning"],
            "graph_multi_hop_reasoning":jg["multi_hop_reasoning"],
            "flat_latency_s":flat["latency_s"],
            "graph_latency_s":graph["latency_s"],
            "flat_total_tokens":flat.get("total_tokens"),
            "graph_total_tokens":graph.get("total_tokens"),
            "flat_judge_rationale":jf["rationale"],
            "graph_judge_rationale":jg["rationale"],
            "graph_supernode_events":len(
                graph["graph_debug"]["diagnostics"].get("supernode_events",[])
            )
        })
        pd.DataFrame(rows).to_csv(CHECKPOINT, index=False)
    return pd.DataFrame(rows)

validate_golden(golden_df, require_answers=False)
eval_results_df = run_evaluation(golden_df)
display(eval_results_df)

✅ Golden Dataset valid.

Evaluation:   0%|          | 0/50 [00:00<?, ?it/s]

Evaluation:   2%|▏         | 1/50 [00:15<12:49, 15.70s/it]

Evaluation:   4%|▍         | 2/50 [00:37<15:19, 19.16s/it]

Evaluation:   6%|▌         | 3/50 [00:48<12:06, 15.46s/it]

Evaluation:   8%|▊         | 4/50 [01:04<11:58, 15.62s/it]

Evaluation:  10%|█         | 5/50 [01:18<11:17, 15.06s/it]

Evaluation:  12%|█▏        | 6/50 [01:32<10:48, 14.75s/it]

Evaluation:  14%|█▍        | 7/50 [01:55<12:24, 17.32s/it]

Evaluation:  16%|█▌        | 8/50 [02:11<11:52, 16.97s/it]

Evaluation:  18%|█▊        | 9/50 [02:18<09:35, 14.04s/it]

Evaluation:  20%|██        | 10/50 [02:37<10:17, 15.43s/it]

Evaluation:  22%|██▏       | 11/50 [02:51<09:50, 15.14s/it]

Evaluation:  24%|██▍       | 12/50 [03:03<08:54, 14.06s/it]

Evaluation:  26%|██▌       | 13/50 [03:12<07:48, 12.66s/it]

Evaluation:  28%|██▊       | 14/50 [03:27<07:59, 13.32s/it]

Evaluation:  30%|███       | 15/50 [03:39<07:25, 12.72s/it]

Evaluation:  32%|███▏      | 16/50 [03:48<06:43, 11.88s/it]

Evaluation:  34%|███▍      | 17/50 [04:02<06:45, 12.29s/it]

Evaluation:  36%|███▌      | 18/50 [04:15<06:39, 12.48s/it]

Evaluation:  38%|███▊      | 19/50 [04:25<06:04, 11.75s/it]

Evaluation:  40%|████      | 20/50 [04:33<05:23, 10.77s/it]

Evaluation:  42%|████▏     | 21/50 [04:51<06:15, 12.95s/it]

Evaluation:  44%|████▍     | 22/50 [05:01<05:38, 12.08s/it]

Evaluation:  46%|████▌     | 23/50 [05:16<05:45, 12.80s/it]

Evaluation:  48%|████▊     | 24/50 [05:25<05:05, 11.75s/it]

Evaluation:  50%|█████     | 25/50 [05:37<04:55, 11.81s/it]

Evaluation:  52%|█████▏    | 26/50 [05:45<04:18, 10.79s/it]

Evaluation:  54%|█████▍    | 27/50 [05:58<04:17, 11.21s/it]

Evaluation:  56%|█████▌    | 28/50 [06:09<04:05, 11.16s/it]

Evaluation:  58%|█████▊    | 29/50 [06:17<03:37, 10.37s/it]

Evaluation:  60%|██████    | 30/50 [06:28<03:28, 10.43s/it]

Evaluation:  62%|██████▏   | 31/50 [06:42<03:42, 11.71s/it]

Evaluation:  64%|██████▍   | 32/50 [06:52<03:19, 11.09s/it]

Evaluation:  66%|██████▌   | 33/50 [06:59<02:46,  9.77s/it]

Evaluation:  68%|██████▊   | 34/50 [07:11<02:47, 10.46s/it]

Evaluation:  70%|███████   | 35/50 [07:24<02:49, 11.30s/it]

Evaluation:  72%|███████▏  | 36/50 [07:33<02:27, 10.53s/it]

Evaluation:  74%|███████▍  | 37/50 [07:42<02:11, 10.13s/it]

Evaluation:  76%|███████▌  | 38/50 [07:53<02:05, 10.47s/it]

Evaluation:  78%|███████▊  | 39/50 [08:05<01:59, 10.88s/it]

Evaluation:  80%|████████  | 40/50 [08:14<01:43, 10.37s/it]

Evaluation:  82%|████████▏ | 41/50 [08:22<01:26,  9.64s/it]

Evaluation:  84%|████████▍ | 42/50 [08:33<01:20, 10.04s/it]

Evaluation:  86%|████████▌ | 43/50 [08:44<01:10, 10.13s/it]

Evaluation:  88%|████████▊ | 44/50 [08:56<01:05, 10.90s/it]

Evaluation:  90%|█████████ | 45/50 [09:13<01:03, 12.64s/it]

Evaluation:  92%|█████████▏| 46/50 [09:26<00:50, 12.65s/it]

Evaluation:  94%|█████████▍| 47/50 [09:35<00:34, 11.61s/it]

Evaluation:  96%|█████████▌| 48/50 [09:50<00:25, 12.80s/it]

Evaluation:  98%|█████████▊| 49/50 [10:05<00:13, 13.31s/it]

Evaluation: 100%|██████████| 50/50 [10:20<00:00, 13.79s/it]

Evaluation: 100%|██████████| 50/50 [10:20<00:00, 12.41s/it]

,id,group,question,reference_answer,flat_answer,graph_answer,flat_comprehensiveness,graph_comprehensiveness,flat_faithfulness,graph_faithfulness,flat_multi_hop_reasoning,graph_multi_hop_reasoning,flat_latency_s,graph_latency_s,flat_total_tokens,graph_total_tokens,flat_judge_rationale,graph_judge_rationale,graph_supernode_events
0,G5000-01,multi-hop,Reconstruct the Aeris–Ericsson IoT transaction across the available reports: which Ericsson businesses moved to Aeri...,"Ericsson's IoT Accelerator and Connected Vehicle Cloud businesses, together with related assets, were to be transfer...",The Aeris–Ericsson IoT transaction involved the transfer of Ericsson's IoT Accelerator and Connected Vehicle Cloud b...,"Aeris acquired Ericsson's IoT Accelerator and Connected Vehicle Cloud businesses on January 18, 2023 [chunk_id=e0ebf...",5,5,5,5,5,5,1.610601,2.081888,620,670,The candidate accurately reconstructs the Aeris–Ericsson IoT transaction by detailing the specific Ericsson business...,The candidate accurately reconstructs the transaction by specifying the acquisition of Ericsson's IoT Accelerator an...,0
1,G5000-02,cross-doc,"Did the first two Aeris/Ericsson reports describe a completed acquisition or a planned transfer, and what later evid...",The first reports describe a planned transaction: Aeris was to acquire Ericsson's IoT Accelerator and Connected Vehi...,The first two Aeris/Ericsson reports described a planned transfer of Ericsson's IoT Accelerator and Connected Vehicl...,The first two Aeris/Ericsson reports describe a planned transfer of Ericsson's IoT Accelerator and Connected Vehicle...,5,5,5,5,5,5,3.022673,2.030259,677,657,The candidate accurately describes the initial reports as detailing a planned transfer of Ericsson's IoT Accelerator...,The candidate accurately describes the initial reports as indicating a planned transfer of Ericsson's IoT Accelerato...,0
2,G5000-03,factoid,"After the Aeris–Ericsson IoT deal progressed, how many IoT devices, enterprises, and countries were cited in the lat...","More than 100 million IoT devices, 9,000 enterprises, and 190 countries.","The later connectivity report cited more than 100 million IoT devices, 9,000 enterprises, and 190 countries followin...","The later connectivity report cited more than 100 million IoT devices, 9,000 enterprises, and 190 countries [chunk_i...",5,5,5,5,5,5,1.513280,1.042091,591,553,"The candidate answer accurately reflects the information provided in the reference, stating the exact numbers of IoT...","The candidate accurately cites the numbers of IoT devices, enterprises, and countries as stated in the reference. It...",0
3,G5000-04,cross-doc,"Which two named Ericsson IoT businesses recur across multiple reports of the Aeris transaction, and why should Graph...",The recurring businesses are Ericsson IoT Accelerator and Connected Vehicle Cloud. The reports describe the same Aer...,The two named Ericsson IoT businesses that recur across multiple reports of the Aeris transaction are Ericsson's IoT...,"The two named Ericsson IoT businesses that recur across multiple reports of the Aeris transaction are the ""IoT Accel...",4,5,5,5,4,5,4.716100,2.410828,673,598,The candidate provides a clear identification of the two businesses involved and explains why they should be conside...,The candidate accurately identifies the two recurring Ericsson IoT businesses and explains why they should be collap...,0
4,G5000-05,multi-hop,"Starting from Ericsson, follow the graph to the acquirer and then to the reported IoT reach. What path and scale sho...",Ericsson -> (IoT Accelerator and Connected Vehicle Cloud transferred/acquired by) Aeris -> supports/connects more th...,The path from Ericsson to the acquirer and the reported IoT reach is as follows:\n\n1. **Starting Point**: Ericsson\...,The path from Ericsson to the acquirer is as follows: Ericsson transferred its IoT Accelerator and Connected Vehicle...,5,4,5,5,5,4,2.170601,2.466961,655,579,"The candidate provides a clear and complete path from Ericsson to Aeris, accurately detailing the acquisition of Eri...","The candidate provides a clear path from Ericsson to Aeris, accurately reflecting the acquisition of the IoT Acceler...",0
5,G5000-06,multi-hop,Trace ServiceNow's generative-AI product/partner evolution from May through July 2023: what partnership began in May...,"In May, ServiceNow partnered with NVIDIA to build enterprise-grade generative AI for workflow automation. In June, S...","In May 2023, ServiceNow announced a partnership with the startup Cohere to enhance its generative AI capabilities fo...","In May 2023, ServiceNow partnered with Accenture and NVIDIA, marking the beginning of their collaboration in generat...",1,2,1,2,1,2,2.128144,2.798395,660,948,"The candidate incorrectly states that ServiceNow partnered with Cohere in May, while the reference specifies a partn...","The candidate incorrectly states that ServiceNow partnered with Accenture in May, while the reference specifies that...",0
6,G5000-07,cross-doc,How did ServiceNow's July generative-AI expansion differ between its platform features and its ecosystem program wit...,ServiceNow expanded the Now Assist feature set with case summarization and text-to-code inside its workflow platform...,"In July, ServiceNow's generative-AI expansion included two distinct initiatives: enhancements to its platform featur...","In July 2023, ServiceNow's generative-AI expansion included two distinct initiatives: enhancements to its platform f...",3,3,4,4,3,3,3.166148,8.544855,765,1068,"The candidate provides a general overview of ServiceNow's generative-AI expansion, mentioning both the platform feat...","The candidate provides a general overview of ServiceNow's generative-AI expansion, mentioning both platform features...",0
7,G5000-08,multi-hop,"Which external organizations are connected to ServiceNow's generative-AI efforts in the selected data, and what dist...",NVIDIA is ServiceNow's generative-AI technology partner and later co-launch partner for AI Lighthouse; Accenture joi...,The context does not provide specific external organizations directly connected to ServiceNow's generative-AI effort...,ServiceNow's generative-AI efforts are connected to the following external organizations:\n\n1. **Accenture**: Partn...,1,2,1,2,1,2,2.555105,4.492068,666,1181,"The candidate fails to identify the specific external organizations connected to ServiceNow's generative-AI efforts,...","The candidate answer includes some relevant organizations but inaccurately includes OpenAI and Associated Press, whi...",0
8,G5000-09,cross-doc,Two June 13 reports describe Now Assist for Virtual Agent. What should a deduplicated graph store as the core event ...,A single ServiceNow product event: Now Assist for Virtual Agent extends ServiceNow's generative-AI capabilities for ...,"The deduplicated graph should store the core event as the introduction of Now Assist for Virtual Agent, which builds...","The deduplicated graph should store the core event as the introduction of Now Assist for Virtual Agent, which builds...",3,3,4,4,3,3,1.618007,1.324456,622,490,The candidate captures the core event of introducing Now Assist for Virtual Agent and mentions its generative AI fea...,The candidate identifies the core event and capability but lacks detail on the specific generative AI features menti...,0
9,G5000-10,multi-hop,What sequence shows ServiceNow moving from domain-specific generative-AI exploration to concrete workflow features?,"At Knowledge 2023, ServiceNow emphasized domain-specific generative-AI/LLM use cases; in June it introduced Now Assi...",The sequence showing ServiceNow's transition from domain-specific generative-AI exploration to concrete workflow fea...,The sequence showing ServiceNow's transition from domain-specific generative-AI exploration to concrete workflow fea...,3,4,4,4,3,4,3.145517,3.657784,838,1171,"The candidate provides a sequence that generally aligns with the reference answer, but it introduces elements like e...","The candidate provides a detailed sequence of events that aligns closely with the reference answer, covering the exp...",0
10,G5000-11,cross-doc,Compare the May ServiceNow–NVIDIA announcement with the July AI Lighthouse announcement. What new entity and new pro...,"The May announcement is a bilateral ServiceNow–NVIDIA partnership to build enterprise-grade generative AI. In July, ...","In the May announcement, ServiceNow and NVIDIA, along with Accenture, launched a collaboration focused on AI solutio...","In the May announcement, ServiceNow partnered with NVIDIA to leverage large language models (LLMs) for advancements ...",2,5,2,5,2,5,1.692299,2.408193,617,835,The candidate mentions the AI Lighthouse program but fails to accurately identify Accenture as the new entity involv...,"The candidate accurately captures the essence of both announcements, clearly stating the partnership between Service...",0
11,G5000-12,multi-hop,"Starting from Now Assist, connect it to both a July platform enhancement and an October services alliance. What are ...","In July, the Now Assist family was expanded with case summarization and text-to-code. In October, Deloitte and Servi...",The two outcomes connected to Now Assist are:\n\n1. **July Platform Enhancement**: The enhancement likely involves n...,"The two outcomes connected to Now Assist, a July platform enhancement, and an October services alliance are:\n\n1. *...",1,2,1,2,1,2,3.158090,2.159182,642,517,The candidate fails to accurately identify the specific enhancements introduced in July and the nature of the Octobe...,The candidate provides outcomes that are somewhat related to the July enhancement and October alliance but lacks spe...,0
12,G5000-13,factoid,"Which three companies launched AI Lighthouse in the selected 5,000-row scope?","ServiceNow, NVIDIA, and Accenture.","The three companies that launched AI Lighthouse are ServiceNow, NVIDIA, and Accenture [chunk_id=a5a8b0ece135c638d4f0...","The three companies that launched AI Lighthouse are ServiceNow, NVIDIA, and Accenture [chunk_id=a5a8b0ece135c638d4f0...",5,5,5,5,5,5,1.024614,1.237473,504,610,"The candidate accurately identifies the three companies that launched AI Lighthouse as ServiceNow, NVIDIA, and Accen...","The candidate answer accurately lists the three companies that launched AI Lighthouse as ServiceNow, NVIDIA, and Acc...",0
13,G5000-14,multi-hop,"Compare Microsoft's ChatGPT/OpenAI delivery to three customer contexts in 2023: a utility, private businesses, and U...",DEWA said it was enriching utility services with ChatGPT technology supported by Microsoft; a May report said Micros...,"In 2023, Microsoft's delivery of ChatGPT/OpenAI technology varies across different customer contexts:\n\n1. **Utilit...","In 2023, Microsoft's delivery of ChatGPT/OpenAI technology varies across different customer contexts:\n\n1. **Utilit...",2,2,2,2,2,2,3.233297,2.593548,808,897,The candidate provides a basic overview of the delivery modes for each customer context but lacks specific details a...,The candidate provides some information about the delivery modes for private businesses but lacks specific details f...,0
14,G5000-15,cross-doc,How did Microsoft's Copilot surface area change between March and September 2023?,"In March, Copilot was described as AI functionality being infused into Office apps including Word, Excel, and Outloo...","Between March and September 2023, Microsoft's Copilot surface area expanded significantly. In March, Copilot was pri...","Between March and September 2023, Microsoft's Copilot surface area expanded significantly. In March, Copilot was pri...",5,4,5,5,5,4,1.984600,2.710416,657,631,The candidate provides a clear and detailed account of how Microsoft's Copilot surface area changed from March to Se...,The candidate provides a clear overview of the changes in Microsoft's Copilot surface area from March to September 2...,0
15,G5000-16,cross-doc,Which Microsoft AI offering in the selected data was explicitly described as potentially running on dedicated server...,The private ChatGPT offering for businesses was described as potentially running on dedicated servers and as somethi...,The Microsoft AI offering explicitly described as potentially running on dedicated servers is Azure OpenAI. Its stat...,The Microsoft AI offering explicitly described as potentially running on dedicated servers is Azure OpenAI. Its stat...,2,2,2,2,2,2,1.492225,1.656448,578,588,"The candidate incorrectly identifies Azure OpenAI as the offering that could run on dedicated servers, while the ref...","The candidate incorrectly identifies Azure OpenAI as the offering that could run on dedicated servers, while the ref...",0
16,G5000-17,multi-hop,"Reconstruct the early-June Microsoft outage incident from the three reports: what attack type was claimed, and which...",The reports describe the same early-June Microsoft disruption as cyberattacks; a hacktivist group claimed it used di...,"In early June, Microsoft experienced significant service disruptions attributed to distributed denial-of-service (DD...","In early June, Microsoft experienced significant service disruptions attributed to distributed denial-of-service (DD...",4,4,5,5,4,4,2.281473,2.561575,663,655,The candidate accurately identifies the attack type as distributed denial-of-service (DDoS) and mentions the affecte...,The candidate accurately identifies the attack type as distributed denial-of-service (DDoS) and mentions the affecte...,0
17,G5000-18,cross-doc,"Why should rows 1943, 2566, and 3284 be treated as duplicate/follow-up evidence for one Microsoft incident rather th...","All three are dated June 18, refer to the same early-June disruptions of Microsoft services/Outlook cloud platform, ...","Rows 1943, 2566, and 3284 should be treated as duplicate/follow-up evidence for one Microsoft incident rather than t...","Rows 1943, 2566, and 3284 should be treated as duplicate/follow-up evidence for one Microsoft incident rather than t...",2,3,3,4,2,3,2.142652,2.755335,630,640,"The candidate provides a general explanation for why the rows should be treated as duplicates, mentioning the same s...","The candidate provides a reasonable explanation for treating the rows as duplicates, mentioning the same timeframe a...",0
18,G5000-19,multi-hop,"What did KPMG commit to spend, on what two technology areas, and through which partner relationship?",KPMG said it would spend $2 billion on artificial intelligence and cloud services through an expanded partnership wi...,KPMG committed to spend $2 billion on artificial intelligence and cloud services through an expanded partnership wit...,KPMG committed to spend $2 billion on artificial intelligence and cloud services through an expanded partnership wit...,5,5,5,5,5,5,1.291924,1.657809,561,524,"The candidate answer accurately captures all key elements from the reference answer, including the amount KPMG commi...","The candidate provides a complete and accurate answer, directly matching the reference. It specifies the amount KPMG...",0
19,G5000-20,cross-doc,How did Options Technology's Microsoft partner designations expand from May to June 2023?,"In May, Options Technology announced Microsoft Solutions Partner status for Infrastructure. In June, it announced Mi...","In June 2023, Options Technology expanded its Microsoft partner designations by achieving the Microsoft Solutions Pa...","In June 2023, Options Technology expanded its Microsoft partner designations by achieving the Microsoft Solutions Pa...",4,2,5,3,4,2,1.301352,1.292184,598,455,The candidate provides a clear and accurate account of Options Technology's expansion of Microsoft partner designati...,The candidate mentions the expansion of Microsoft partner designations by achieving the Security designation in June...,0
20,G5000-21,multi-hop,Combine Microsoft's Poland infrastructure story with KPMG's July AI/cloud investment story. What two distinct kinds ...,"Microsoft launched a cloud data storage/processing hub in central Poland, representing physical cloud infrastructure...",The two distinct kinds of Microsoft cloud expansion represented are:\n\n1. **Infrastructure Development**: Microsoft...,The two distinct kinds of Microsoft cloud expansion represented are:\n\n1. **Infrastructure Development**: Microsoft...,5,5,5,5,5,5,2.996891,2.219143,656,935,The candidate accurately identifies the two distinct kinds of Microsoft cloud expansion: physical infrastructure dev...,The candidate accurately identifies the two distinct kinds of Microsoft cloud expansion: physical infrastructure dev...,0
21,G5000-22,multi-hop,"From Office Copilot to unified Windows Copilot, what entities and surfaces form the product-expansion path?","Microsoft Copilot first appears across Office applications such as Word, Excel, and Outlook; later Microsoft describ...",The product-expansion path from Office Copilot to unified Windows Copilot involves the integration of several former...,The product-expansion path from Office Copilot to unified Windows Copilot involves the integration of several former...,4,4,5,5,4,4,2.319980,2.065634,614,510,The candidate provides a clear overview of the product-expansion path from Office Copilot to unified Windows Copilot...,The candidate provides a clear overview of the product-expansion path from Office Copilot to unified Windows Copilot...,0
22,G5000-23,cross-doc,"Which Microsoft-related story is a confirmed external customer use of ChatGPT, and which is only a reported potentia...",DEWA's February announcement is a confirmed customer use case: it said it was working to enrich services with ChatGP...,"The confirmed external customer use of ChatGPT is by Novacoast, which reported that OpenAI’s GPT-3 technology has sa...","The confirmed external customer use of ChatGPT is represented by IFI Techsolutions, which is a global Microsoft part...",1,1,1,1,1,1,2.455953,5.214632,631,603,"The candidate incorrectly identifies Novacoast as the confirmed customer use of ChatGPT, while the reference states ...","The candidate incorrectly identifies IFI Techsolutions as the confirmed customer use of ChatGPT, whereas the referen...",0
23,G5000-24,factoid,What Microsoft settlement amount is reported for illegally collecting children's personal information?,$20 million.,Microsoft has agreed to pay $20 million to settle charges by the Federal Trade Commission (FTC) for illegally collec...,Microsoft has agreed to pay $20 million to settle charges by the Federal Trade Commission (FTC) for illegally collec...,5,5,5,5,5,5,1.492928,1.875254,566,548,"The candidate provides a complete and accurate answer to the question, stating the settlement amount of $20 million ...","The candidate provides a complete and accurate answer to the question, stating the settlement amount of $20 million ...",0
24,G5000-25,cross-doc,"Was AWS reported to have adopted AMD's new AI chips, or only to be evaluating them? What evidence in the selected da...","AWS was reported to be considering AMD's new AI chips, and an AWS executive said no final decision had been made. Th...","AWS has only been reported to be considering the use of AMD's new AI chips, not adopting them. An AWS executive stat...",AWS was reported to be considering the use of AMD's new AI chips but has not made a final decision on adoption. This...,5,5,5,5,5,5,1.526551,1.988090,594,819,"The candidate accurately reflects the information from the reference, stating that AWS is only considering AMD's new...","The candidate accurately reflects the information from the reference, stating that AWS is considering AMD's AI chips...",0

In [20]:
#@title 4.4 — Comparison table + export
def comparison_table(eval_df):
    metric_map = {
        "Comprehensiveness":("flat_comprehensiveness","graph_comprehensiveness"),
        "Faithfulness":("flat_faithfulness","graph_faithfulness"),
        "Multi-hop reasoning":("flat_multi_hop_reasoning","graph_multi_hop_reasoning"),
        "Latency (s)":("flat_latency_s","graph_latency_s"),
        "Token usage":("flat_total_tokens","graph_total_tokens"),
    }

    rows = []
    for group, g in eval_df.groupby("group"):
        for metric, (fc,gc) in metric_map.items():
            f = pd.to_numeric(g[fc], errors="coerce").mean()
            gr = pd.to_numeric(g[gc], errors="coerce").mean()

            if metric in {"Latency (s)","Token usage"}:
                comment = "Flat RAG thường rẻ/nhanh hơn." if f < gr else "GraphRAG không đắt hơn trong sample này."
            else:
                delta = gr - f
                if delta >= .75:
                    comment = "GraphRAG cải thiện rõ; kiểm tra rationale và provenance."
                elif delta <= -.5:
                    comment = "Flat RAG tốt hơn; graph extraction/retrieval có thể gây mất thông tin hoặc nhiễu."
                else:
                    comment = "Hai phương pháp gần nhau."

            rows.append({
                "Loại câu hỏi":group, "Metric":metric,
                "Flat RAG":round(f,3) if pd.notna(f) else np.nan,
                "GraphRAG":round(gr,3) if pd.notna(gr) else np.nan,
                "Nhận xét phân tích":comment
            })
    return pd.DataFrame(rows)

comparison_df = comparison_table(eval_results_df)
display(comparison_df)
eval_results_df.to_csv("outputs/graphrag_eval_results.csv", index=False)
comparison_df.to_csv("outputs/graphrag_vs_flatrag_summary.csv", index=False)

,Loại câu hỏi,Metric,Flat RAG,GraphRAG,Nhận xét phân tích
0,cross-doc,Comprehensiveness,3.000,3.136,Hai phương pháp gần nhau.
1,cross-doc,Faithfulness,3.409,3.591,Hai phương pháp gần nhau.
2,cross-doc,Multi-hop reasoning,3.000,3.091,Hai phương pháp gần nhau.
3,cross-doc,Latency (s),1.981,2.306,Flat RAG thường rẻ/nhanh hơn.
4,cross-doc,Token usage,637.955,689.909,Flat RAG thường rẻ/nhanh hơn.
5,factoid,Comprehensiveness,5.000,5.000,Hai phương pháp gần nhau.
6,factoid,Faithfulness,5.000,5.000,Hai phương pháp gần nhau.
7,factoid,Multi-hop reasoning,5.000,5.000,Hai phương pháp gần nhau.
8,factoid,Latency (s),1.300,1.428,Flat RAG thường rẻ/nhanh hơn.
9,factoid,Token usage,595.600,561.200,GraphRAG không đắt hơn trong sample này.
10,multi-hop,Comprehensiveness,3.043,3.174,Hai phương pháp gần nhau.
11,multi-hop,Faithfulness,3.304,3.478,Hai phương pháp gần nhau.
12,multi-hop,Multi-hop reasoning,3.043,3.174,Hai phương pháp gần nhau.
13,multi-hop,Latency (s),2.302,2.496,Flat RAG thường rẻ/nhanh hơn.
14,multi-hop,Token usage,683.739,780.522,Flat RAG thường rẻ/nhanh hơn.

# PHẦN 5 — FAILURE-MODE CHECKS & SUBMISSION (105–120')

Bắt buộc chứng minh:
1. Edge provenance không thiếu.
2. Entity Resolution có audit.
3. Super-node degree > 100 chỉ expand tối đa 50 edge.
4. Có comparison table.

In [21]:
#@title 5.1 — Super-node check + entity audit
def test_supernode_policy():
    rows = run_cypher("""
    MATCH (n:Entity)-[r]-()
    WITH n, count(r) AS degree
    ORDER BY degree DESC LIMIT 1
    RETURN n.id AS id, n.name AS name, degree
    """)
    if not rows:
        print("Graph empty.")
        return

    n = rows[0]
    limit = 50 if n["degree"] > SUPER_NODE_DEGREE else 1000
    edges = recent_edges(n["id"], limit)
    print(n, "fetched=", len(edges))
    if n["degree"] > SUPER_NODE_DEGREE:
        assert len(edges) <= 50
        print("✅ Super-node cap OK.")

def show_resolution_audit(audit_df):
    if audit_df.empty:
        print("No audit rows.")
        return
    display(
        audit_df.sort_values("similarity", ascending=False).head(30)
    )
    print("High-similarity rejected pairs:")
    display(
        audit_df[audit_df.decision=="REJECT_GUARD"]
        .sort_values("similarity", ascending=False)
        .head(20)
    )

test_supernode_policy()
show_resolution_audit(entity_resolution_audit_df)

{'id': 'af61c9129da522c49e916ec6', 'name': 'L&T Technology Services Limited', 'degree': 7} fetched= 7

,type,left,right,similarity,decision
0,Company,Fidelity National Information Services,Fidelity National Information Services Inc.,0.924524,MERGE_VECTOR
3,Technology,X90A,X90,0.920579,REJECT_GUARD
1,Company,L&T Technology Services Limited,L&T Technology Services Ltd,0.920202,MERGE_VECTOR
2,Technology,healthcare information technology,healthcare information technology services,0.902359,REJECT_GUARD

High-similarity rejected pairs:

,type,left,right,similarity,decision
3,Technology,X90A,X90,0.920579,REJECT_GUARD
2,Technology,healthcare information technology,healthcare information technology services,0.902359,REJECT_GUARD

## 5.2 — Thuyết minh kỹ thuật: học viên tự điền

1. Coreference sai ở tình huống nào?
2. Entity threshold bao nhiêu, vì sao?
3. Candidate nào similarity cao nhưng không nên merge?
4. Top 3 super-node và degree?
5. Vì sao ưu tiên edge mới nhất có thể đúng/sai?
6. Flat RAG thắng nhóm nào?
7. GraphRAG thắng nhóm nào?
8. Latency/token trade-off?
9. AI Coding Agent đề xuất gì mà bạn **không dùng**, vì sao?
10. Scale 350MB: bottleneck đầu tiên là gì?

# 🎁 BONUS

## A — Low-level / High-level
Tạo local entities và high-level topics/community reports; query router chọn tầng retrieval.

## B — Global Search via Community Reports
Nếu Neo4j instance không có GDS phù hợp, fallback:
1. export edges,
2. NetworkX community detection,
3. `UNWIND` write `community_id`,
4. LLM summarize community,
5. query global trên reports.

## C — Self-Correction Graph Retrieval
- hop 2 → LLM kiểm tra context đủ chưa,
- thiếu → hop 3,
- vẫn thiếu → vector fallback,
- bắt buộc stop condition.

In [22]:
#@title Bonus — NetworkX community fallback
import networkx as nx

def build_communities(limit_edges=20000):
    edge_df = pd.DataFrame(run_cypher("""
    MATCH (a:Entity)-[r]->(b:Entity)
    RETURN a.id AS source, b.id AS target
    LIMIT $limit
    """, limit=int(limit_edges)))

    G = nx.Graph()
    G.add_edges_from(edge_df[["source","target"]].itertuples(index=False, name=None))
    communities = nx.algorithms.community.greedy_modularity_communities(G)

    rows = []
    for cid, members in enumerate(communities):
        rows += [{"id":node_id,"community_id":int(cid)} for node_id in members]

    for b in batches(rows, 1000):
        run_cypher("""
        UNWIND $rows AS row
        MATCH (n:Entity {id:row.id})
        SET n.community_id=row.community_id
        """, rows=b)

    return pd.DataFrame(rows)

community_df = build_communities()

In [23]:
#@title Bonus — Self-correction scaffold
SUFFICIENCY_SYSTEM = """
Decide whether the supplied retrieval context is sufficient to answer the question faithfully.
Do not answer the question. Return strict JSON only.
""".strip()

def context_sufficient(question, context):
    obj, _ = groq_json(
        SUFFICIENCY_SYSTEM,
        f"""QUESTION: {question}
CONTEXT:
{context[:16000]}
Return {{"sufficient":true,"missing":"..."}}"""
    )
    return bool(obj.get("sufficient")), norm_space(obj.get("missing"))

def self_correcting_context(question):
    g2 = retrieve_graph_context(question, 2, 50, True)
    ok, missing = context_sufficient(question, g2["context"])
    if ok:
        return {"route":"hop2","context":g2["context"],"missing":""}

    g3 = retrieve_graph_context(question, 3, 50, True)
    ok, missing2 = context_sufficient(question, g3["context"])
    if ok:
        return {"route":"hop3","context":g3["context"],"missing":missing}

    flat, _ = retrieve_flat_context(question, k=8)
    return {
        "route":"hop3+vector",
        "context":f"=== GRAPH ===\n{g3['context']}\n\n=== VECTOR ===\n{flat}",
        "missing":missing2
    }

# ✅ RUBRIC

- **30% Chạy được code:** graph nạp thành công, schema đúng, xuất bảng.
- **30% Failure modes:** xử lý ít nhất 2/3 vấn đề Super-node, Entity Resolution, Coreference.
- **20% Evaluation:** chạy hết Golden Dataset, phân tích hợp lý.
- **20% Thuyết minh:** giải thích kiến trúc và cách kiểm soát AI Coding Agent.

## Submission checklist
- [ ] Neo4j connected
- [ ] Dedup/chunking đã chạy
- [ ] Coreference spot-check
- [ ] Entity resolution audit
- [ ] `UNWIND` bulk insert
- [ ] 0 edge thiếu provenance
- [ ] Flat RAG chạy
- [ ] GraphRAG chạy
- [ ] Super-node check
- [ ] Golden Dataset có gold answers thật
- [ ] Evaluation chạy hết
- [ ] Export results + summary CSV
- [ ] Thuyết minh kỹ thuật
- [ ] Bonus (nếu có) có định lượng trước/sau